# 한솥 도시락 메뉴이름 및 가격 수집

In [1]:
from selenium import webdriver as wb
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from tqdm import tqdm
import pandas as pd
import time   # 컴퓨터의 시간을 컨트롤하는 모듈

### 브라우저 창 켜기, 창 확대

In [2]:
driver = wb.Chrome()
driver.get("https://www.hsd.co.kr/menu/menu_list")

In [4]:
# 브라우저 화면 최대화
driver.maximize_window()

WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'
  (Session info: chrome=148.0.7778.217)
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7f78e7de5+14895]
	chromedriver!GetHandleVerifier [0x7ff7f78e7e50+14900]
	chromedriver!(No symbol) [0x7ff7f764d5ad]
	chromedriver!(No symbol) [0x7ff7f7629578]
	chromedriver!(No symbol) [0x7ff7f762672c]
	chromedriver!(No symbol) [0x7ff7f7625e85]
	chromedriver!(No symbol) [0x7ff7f770da0f]
	chromedriver!(No symbol) [0x7ff7f76d005a]
	chromedriver!(No symbol) [0x7ff7f76f486f]
	chromedriver!(No symbol) [0x7ff7f7699df8]
	chromedriver!(No symbol) [0x7ff7f769ace3]
	chromedriver!GetHandleVerifier [0x7ff7f7bfcc49+3296f9]
	chromedriver!GetHandleVerifier [0x7ff7f7bf7375+323e25]
	chromedriver!GetHandleVerifier [0x7ff7f7c1bc82+348732]
	chromedriver!GetHandleVerifier [0x7ff7f7906045+32af5]
	chromedriver!GetHandleVerifier [0x7ff7f790ecec+3b79c]
	chromedriver!GetHandleVerifier [0x7ff7f78f1bc4+1e674]
	chromedriver!GetHandleVerifier [0x7ff7f78f1d54+1e804]
	chromedriver!GetHandleVerifier [0x7ff7f78d60e7+2b97]
	KERNEL32!BaseThreadInitThunk [0x7ffc9bdee957+17]
	ntdll!RtlUserThreadStart [0x7ffc9c52427c+2c]

### 메뉴 이름과 가격 수집

In [5]:
# 메뉴 이름
titles = driver.find_elements(By.CSS_SELECTOR, "h4.h.fz_03")
titles

[<selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.487")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.500")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.510")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.520")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.530")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.540")>]

In [6]:
type(titles)

list

In [8]:
titles[0].text

'매화 연어'

In [9]:
# 반복문으로 출력
for i in titles :
    print(i.text)

매화 연어
불짬뽕 만두
열무 두부강된장 비빔밥
열무 감초고추장 비빔밥
오향 청양 소보로덮밥
소이 청양 소보로덮밥

In [10]:
# 가격 수집
prices = driver.find_elements(By.CSS_SELECTOR, "strong")   # strong태그: 텍스트를 굵게 표시
prices

[<selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.490")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.503")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.513")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.523")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.533")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.543")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.884")>]

In [11]:
# 반복문으로 출력
for i in prices :
    print(i.text)

12,500
2,500
5,500
5,000
5,500
5,500
개인정보처리방침

In [12]:
# strong태그에 우클릭해서 copy - copy selector로 가져온 코드
prices = driver.find_elements(By.CSS_SELECTOR, "#menuList_696 > div > div.item-text > div > strong")
prices

In [13]:
# menu에서 #은 아이디값을 뜻하며 유일한 값이므로 하나만 나왔음
# 따라서 가장 부모 선택자인 아이디값을 삭제하여 재 검색
prices = driver.find_elements(By.CSS_SELECTOR, "div > div.item-text > div > strong")
prices

[<selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.490")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.503")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.513")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.523")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.533")>,
 <selenium.webdriver.remote.webelement.WebElement (session="a5f0c8273ae7f62c780ede357da967a4", element="f.1C7EA3A05AC6A985F7890155CE754D09.d.118B607CF282BC4C8DBA55CAB8E1D69E.e.543")>]

In [14]:
for i in prices :
    print(i.text)

12,500
2,500
5,500
5,000
5,500
5,500

In [15]:
# 기존대로 태그 및 선택자를 맨 아래에서 보고 작성해도 무방함!
prices = driver.find_elements(By.CSS_SELECTOR, "div.item-price > strong")

for i in prices :
    print(i.text)

12,500
2,500
5,500
5,000
5,500
5,500

### 페이지 하단의 '더보기' 버튼을 눌러 메뉴를 확장

In [18]:
# 버튼 자체에 접근
btn = driver.find_element(By.CSS_SELECTOR, "a.c_05")

# 클릭
btn.click()

In [19]:
# 더보기 버튼이 몇번이나 더 있을지 모르기 때문에 while문을 통해서 계속 눌러주자
while True :
    btn = driver.find_element(By.CSS_SELECTOR, "a.c_05")
    btn.click()

    # 2초간 대기했다가 다음 코드 실행
    time.sleep(2)

    # 더보기 버튼을 누르고 페이지가 뜨는데 시간이 약간 걸릴 수 있는데 대기 코드가 없다면 페이지가 뜨기도 전에
    # 무한정 버튼을 클릭하라고 명령하게 되어서 서버의 입장에서는 과부하가 걸릴 수 있고, 우리도 제대로 정보를 수집하지 못할 수 있음
    # 더 심한 경우에는 서버 자체에서 보안 공격으로 판단하고 접속한 클라이언트 PC의 IP주소를 차단할 수도 있음

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=148.0.7778.217); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementnotinteractableexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7f78e7de5+14895]
	chromedriver!GetHandleVerifier [0x7ff7f78e7e50+14900]
	chromedriver!(No symbol) [0x7ff7f764d396]
	chromedriver!(No symbol) [0x7ff7f76a8dc4]
	chromedriver!(No symbol) [0x7ff7f769bce6]
	chromedriver!(No symbol) [0x7ff7f76d005a]
	chromedriver!(No symbol) [0x7ff7f769b566]
	chromedriver!(No symbol) [0x7ff7f76f486f]
	chromedriver!(No symbol) [0x7ff7f7699df8]
	chromedriver!(No symbol) [0x7ff7f769ace3]
	chromedriver!GetHandleVerifier [0x7ff7f7bfcc49+3296f9]
	chromedriver!GetHandleVerifier [0x7ff7f7bf7375+323e25]
	chromedriver!GetHandleVerifier [0x7ff7f7c1bc82+348732]
	chromedriver!GetHandleVerifier [0x7ff7f7906045+32af5]
	chromedriver!GetHandleVerifier [0x7ff7f790ecec+3b79c]
	chromedriver!GetHandleVerifier [0x7ff7f78f1bc4+1e674]
	chromedriver!GetHandleVerifier [0x7ff7f78f1d54+1e804]
	chromedriver!GetHandleVerifier [0x7ff7f78d60e7+2b97]
	KERNEL32!BaseThreadInitThunk [0x7ffc9bdee957+17]
	ntdll!RtlUserThreadStart [0x7ffc9c52427c+2c]

### Python 예외 처리 문법(try-except문)
- 코드가 제대로 동작할때와 동작하지 않을때를 구분해주는 파이썬 문법
- 웹 페이지는 항상 같은 구조로 코드가 짜여지 있지는 않기 때문에 크롤링 시 예외처리를 많이 사용하게 됨
- **try문** : 일반적으로 동작하는 코드
- **except문** : try문이 동작하지 않는 예외의 경우(에러 발생시) 작동되는 코드

In [20]:
# 일반적으로 동작하는 코드
try :
    while True :
        btn = driver.find_element(By.CSS_SELECTOR, "a.c_05")
        btn.click()
        time.sleep(2)

# try문이 동작하지 않는 예외의 경우에 동작하는 코드
except :
    print("더보기 버튼이 더이상 없네요 ㅠ_ㅠ 그래도 코드는 에러없이 이어서 동작합니다!")


# 더보기 버튼을 모두 누른 후(HTML요소를 모두 받아온 후) 메뉴와 가격정보를 추출
titles = driver.find_elements(By.CSS_SELECTOR, "h4.h.fz_03")
prices = driver.find_elements(By.CSS_SELECTOR, "div.item-price > strong")

titles_list, prices_list = [], []

for i in tqdm(range(len(titles))) :
    titles_list.append(titles[i].text)
    prices_list.append(prices[i].text + "원")

print("크롤링 완료!!!")

더보기 버튼이 더이상 없네요 ㅠ_ㅠ 그래도 코드는 에러없이 이어서 동작합니다!

100%|██████████████████████████████████████████████████████████████████████████████████| 88/88 [00:02<00:00, 40.13it/s]

크롤링 완료!!!

In [21]:
titles_list

['매화 연어',
 '불짬뽕 만두',
 '열무 두부강된장 비빔밥',
 '열무 감초고추장 비빔밥',
 '오향 청양 소보로덮밥',
 '소이 청양 소보로덮밥',
 '스페셜 한우함박스테이크 도시락',
 '스페셜 해바라기 도시락',
 '스페셜 숯불직화 진달래 도시락',
 '스페셜 송정식 떡갈비 도시락',
 '매화 고등어',
 '해바라기',
 '진달래',
 '카츠카츠 고기고기',
 '돈까스도련님 고기고기',
 '돈치 고기고기',
 '새치 고기고기',
 '동백',
 '돈치스팸',
 '칠리 찹쌀탕수육도련님',
 '돈까스도련님',
 '제육 돈까스도련님',
 '한우 함박스테이크& 청양 토네이도 소세지',
 '한우 함박스테이크&토네이도 소세지',
 '송정식 떡갈비',
 '치킨제육',
 '더블 돈까스도련님',
 '더블 칠리 찹쌀탕수육도련님',
 '메가치킨마요',
 '왕치킨마요',
 '빅치킨마요',
 '치킨마요',
 '스팸마요',
 '참치마요',
 '김치볶음밥&돼지불백',
 '스팸 김치볶음밥',
 '김치볶음밥',
 '부대찌개',
 '묵은지 김치찌개',
 '돼지불백 덮밥',
 '제많덮(제육 많이 덮밥)',
 '빅 제많덮(빅 제육 많이 덮밥)',
 '숯불직화구이 덮밥',
 '김치 제육 덮밥',
 '왕카레돈까스덮밥',
 '오리지널 치즈 닭갈비덮밥',
 '김치 참치 덮밥',
 '핫 치즈 닭갈비덮밥',
 '돈까스 카레',
 '돈까스 덮밥',
 '소불고기 감초고추장 비빔밥',
 '시골제육 두부강된장 비빔밥',
 '참치야채 감초고추장 비빔밥',
 '빅치킨마요 부대찌개 정식',
 '치킨마요 부대찌개 정식',
 '단품 부대찌개',
 '단품 묵은지 김치찌개',
 '단품 카레',
 '반찬 돈까스도련님',
 '반찬 치킨',
 '반찬 제육볶음',
 '반찬 돈까스',
 '반찬 토네이도 소세지',
 '반찬 고기고기',
 '반찬 고등어 데리야끼',
 '미니반찬 김치',
 '미니반찬 무말랭이 무침',
 '12곡밥',
 '발아현미밥',
 '한솥밥',
 '해시 포테이토 스틱',
 '치즈버터 해시 포테이토 스틱',
 '허니버터 해시 포테이토 스틱',
 '뉴 감자고로케',
 '미니 찹쌀핫도그',
 '미니 찹쌀탕수육',
 '케이준후라이',
 '김피탕',
 '크림 닭강정(소)',
 '크림 닭강정(중)',
 '한솥 닭강정(소)',
 '한솥 닭강정(중)',
 '후라이드 순살(소)_양념치킨소스',
 '후라이드 순살(소)_케이준소스',
 '후라이드 순살(중)',
 '치킹 반반순살(양념, 후라이드)',
 '치킹 반반순살(후라이드)',
 '제주녹차 미니꿀호떡']

In [22]:
prices_list

['12,500원',
 '2,500원',
 '5,500원',
 '5,000원',
 '5,500원',
 '5,500원',
 '14,000원',
 '13,000원',
 '12,000원',
 '11,000원',
 '11,500원',
 '10,300원',
 '8,800원',
 '8,000원',
 '7,300원',
 '6,800원',
 '7,800원',
 '6,700원',
 '5,500원',
 '5,000원',
 '5,200원',
 '5,200원',
 '9,000원',
 '9,000원',
 '7,200원',
 '5,500원',
 '10,500원',
 '8,500원',
 '6,600원',
 '5,600원',
 '4,600원',
 '3,900원',
 '4,400원',
 '3,800원',
 '7,900원',
 '5,200원',
 '4,400원',
 '6,500원',
 '6,000원',
 '5,900원',
 '6,500원',
 '7,500원',
 '6,500원',
 '5,200원',
 '6,700원',
 '6,500원',
 '4,900원',
 '6,500원',
 '5,100원',
 '4,700원',
 '6,000원',
 '6,500원',
 '4,000원',
 '8,800원',
 '8,100원',
 '5,200원',
 '4,700원',
 '2,900원',
 '4,200원',
 '4,000원',
 '3,900원',
 '2,900원',
 '3,200원',
 '3,900원',
 '3,900원',
 '500원',
 '600원',
 '2,100원',
 '1,900원',
 '1,200원',
 '2,000원',
 '2,200원',
 '2,200원',
 '2,700원',
 '2,800원',
 '2,300원',
 '1,900원',
 '6,700원',
 '3,900원',
 '9,900원',
 '3,500원',
 '9,000원',
 '4,000원',
 '4,000원',
 '7,500원',
 '16,900원',
 '16,900원',
 '2,500원']

In [23]:
print("메뉴 개수 :", len(titles_list))
print("가격 개수 :", len(prices_list))

메뉴 개수 : 88
가격 개수 : 88

### 리스트의 요소들을 1:1로 묶어서 딕셔너리로 만들기

In [24]:
# zip : 길이가 동일한 두 개의 순서가 있는 집합을 1:1로 대응시켜 튜플로 묶어주는 함수
 # zip함수로 묶여진 데이터는 바로 표시되진 않아서 변수로 출력시켜도 확인이 불가하고 형변환을 하거나 반복문으로 출력가능
temp = zip(titles_list, prices_list)
temp

In [25]:
type(temp)

zip

In [26]:
for i in temp :
    print(i)

('매화 연어', '12,500원')
('불짬뽕 만두', '2,500원')
('열무 두부강된장 비빔밥', '5,500원')
('열무 감초고추장 비빔밥', '5,000원')
('오향 청양 소보로덮밥', '5,500원')
('소이 청양 소보로덮밥', '5,500원')
('스페셜 한우함박스테이크 도시락', '14,000원')
('스페셜 해바라기 도시락', '13,000원')
('스페셜 숯불직화 진달래 도시락', '12,000원')
('스페셜 송정식 떡갈비 도시락', '11,000원')
('매화 고등어', '11,500원')
('해바라기', '10,300원')
('진달래', '8,800원')
('카츠카츠 고기고기', '8,000원')
('돈까스도련님 고기고기', '7,300원')
('돈치 고기고기', '6,800원')
('새치 고기고기', '7,800원')
('동백', '6,700원')
('돈치스팸', '5,500원')
('칠리 찹쌀탕수육도련님', '5,000원')
('돈까스도련님', '5,200원')
('제육 돈까스도련님', '5,200원')
('한우 함박스테이크& 청양 토네이도 소세지', '9,000원')
('한우 함박스테이크&토네이도 소세지', '9,000원')
('송정식 떡갈비', '7,200원')
('치킨제육', '5,500원')
('더블 돈까스도련님', '10,500원')
('더블 칠리 찹쌀탕수육도련님', '8,500원')
('메가치킨마요', '6,600원')
('왕치킨마요', '5,600원')
('빅치킨마요', '4,600원')
('치킨마요', '3,900원')
('스팸마요', '4,400원')
('참치마요', '3,800원')
('김치볶음밥&돼지불백', '7,900원')
('스팸 김치볶음밥', '5,200원')
('김치볶음밥', '4,400원')
('부대찌개', '6,500원')
('묵은지 김치찌개', '6,000원')
('돼지불백 덮밥', '5,900원')
('제많덮(제육 많이 덮밥)', '6,500원')
('빅 제많덮(빅 제육 많이 덮밥)', '7,500원')
('숯불직화구이 덮밥', '6,500원')
('김치 제육 덮밥', '5,200원')
('왕카레돈까스덮밥', '6,700원')
('오리지널 치즈 닭갈비덮밥', '6,500원')
('김치 참치 덮밥', '4,900원')
('핫 치즈 닭갈비덮밥', '6,500원')
('돈까스 카레', '5,100원')
('돈까스 덮밥', '4,700원')
('소불고기 감초고추장 비빔밥', '6,000원')
('시골제육 두부강된장 비빔밥', '6,500원')
('참치야채 감초고추장 비빔밥', '4,000원')
('빅치킨마요 부대찌개 정식', '8,800원')
('치킨마요 부대찌개 정식', '8,100원')
('단품 부대찌개', '5,200원')
('단품 묵은지 김치찌개', '4,700원')
('단품 카레', '2,900원')
('반찬 돈까스도련님', '4,200원')
('반찬 치킨', '4,000원')
('반찬 제육볶음', '3,900원')
('반찬 돈까스', '2,900원')
('반찬 토네이도 소세지', '3,200원')
('반찬 고기고기', '3,900원')
('반찬 고등어 데리야끼', '3,900원')
('미니반찬 김치', '500원')
('미니반찬 무말랭이 무침', '600원')
('12곡밥', '2,100원')
('발아현미밥', '1,900원')
('한솥밥', '1,200원')
('해시 포테이토 스틱', '2,000원')
('치즈버터 해시 포테이토 스틱', '2,200원')
('허니버터 해시 포테이토 스틱', '2,200원')
('뉴 감자고로케', '2,700원')
('미니 찹쌀핫도그', '2,800원')
('미니 찹쌀탕수육', '2,300원')
('케이준후라이', '1,900원')
('김피탕', '6,700원')
('크림 닭강정(소)', '3,900원')
('크림 닭강정(중)', '9,900원')
('한솥 닭강정(소)', '3,500원')
('한솥 닭강정(중)', '9,000원')
('후라이드 순살(소)_양념치킨소스', '4,000원')
('후라이드 순살(소)_케이준소스', '4,000원')
('후라이드 순살(중)', '7,500원')
('치킹 반반순살(양념, 후라이드)', '16,900원')
('치킹 반반순살(후라이드)', '16,900원')
('제주녹차 미니꿀호떡', '2,500원')

In [27]:
# 메뉴와 가격을 1:1 대응시킨 zip형태를 딕셔너리로 형변환
titles_prices_dic = dict(zip(titles_list, prices_list))
titles_prices_dic

{'매화 연어': '12,500원',
 '불짬뽕 만두': '2,500원',
 '열무 두부강된장 비빔밥': '5,500원',
 '열무 감초고추장 비빔밥': '5,000원',
 '오향 청양 소보로덮밥': '5,500원',
 '소이 청양 소보로덮밥': '5,500원',
 '스페셜 한우함박스테이크 도시락': '14,000원',
 '스페셜 해바라기 도시락': '13,000원',
 '스페셜 숯불직화 진달래 도시락': '12,000원',
 '스페셜 송정식 떡갈비 도시락': '11,000원',
 '매화 고등어': '11,500원',
 '해바라기': '10,300원',
 '진달래': '8,800원',
 '카츠카츠 고기고기': '8,000원',
 '돈까스도련님 고기고기': '7,300원',
 '돈치 고기고기': '6,800원',
 '새치 고기고기': '7,800원',
 '동백': '6,700원',
 '돈치스팸': '5,500원',
 '칠리 찹쌀탕수육도련님': '5,000원',
 '돈까스도련님': '5,200원',
 '제육 돈까스도련님': '5,200원',
 '한우 함박스테이크& 청양 토네이도 소세지': '9,000원',
 '한우 함박스테이크&토네이도 소세지': '9,000원',
 '송정식 떡갈비': '7,200원',
 '치킨제육': '5,500원',
 '더블 돈까스도련님': '10,500원',
 '더블 칠리 찹쌀탕수육도련님': '8,500원',
 '메가치킨마요': '6,600원',
 '왕치킨마요': '5,600원',
 '빅치킨마요': '4,600원',
 '치킨마요': '3,900원',
 '스팸마요': '4,400원',
 '참치마요': '3,800원',
 '김치볶음밥&돼지불백': '7,900원',
 '스팸 김치볶음밥': '5,200원',
 '김치볶음밥': '4,400원',
 '부대찌개': '6,500원',
 '묵은지 김치찌개': '6,000원',
 '돼지불백 덮밥': '5,900원',
 '제많덮(제육 많이 덮밥)': '6,500원',
 '빅 제많덮(빅 제육 많이 덮밥)': '7,500원',
 '숯불직화구이 덮밥': '6,500원',
 '김치 제육 덮밥': '5,200원',
 '왕카레돈까스덮밥': '6,700원',
 '오리지널 치즈 닭갈비덮밥': '6,500원',
 '김치 참치 덮밥': '4,900원',
 '핫 치즈 닭갈비덮밥': '6,500원',
 '돈까스 카레': '5,100원',
 '돈까스 덮밥': '4,700원',
 '소불고기 감초고추장 비빔밥': '6,000원',
 '시골제육 두부강된장 비빔밥': '6,500원',
 '참치야채 감초고추장 비빔밥': '4,000원',
 '빅치킨마요 부대찌개 정식': '8,800원',
 '치킨마요 부대찌개 정식': '8,100원',
 '단품 부대찌개': '5,200원',
 '단품 묵은지 김치찌개': '4,700원',
 '단품 카레': '2,900원',
 '반찬 돈까스도련님': '4,200원',
 '반찬 치킨': '4,000원',
 '반찬 제육볶음': '3,900원',
 '반찬 돈까스': '2,900원',
 '반찬 토네이도 소세지': '3,200원',
 '반찬 고기고기': '3,900원',
 '반찬 고등어 데리야끼': '3,900원',
 '미니반찬 김치': '500원',
 '미니반찬 무말랭이 무침': '600원',
 '12곡밥': '2,100원',
 '발아현미밥': '1,900원',
 '한솥밥': '1,200원',
 '해시 포테이토 스틱': '2,000원',
 '치즈버터 해시 포테이토 스틱': '2,200원',
 '허니버터 해시 포테이토 스틱': '2,200원',
 '뉴 감자고로케': '2,700원',
 '미니 찹쌀핫도그': '2,800원',
 '미니 찹쌀탕수육': '2,300원',
 '케이준후라이': '1,900원',
 '김피탕': '6,700원',
 '크림 닭강정(소)': '3,900원',
 '크림 닭강정(중)': '9,900원',
 '한솥 닭강정(소)': '3,500원',
 '한솥 닭강정(중)': '9,000원',
 '후라이드 순살(소)_양념치킨소스': '4,000원',
 '후라이드 순살(소)_케이준소스': '4,000원',
 '후라이드 순살(중)': '7,500원',
 '치킹 반반순살(양념, 후라이드)': '16,900원',
 '치킹 반반순살(후라이드)': '16,900원',
 '제주녹차 미니꿀호떡': '2,500원'}

## 이제껏 작성했던 코드를 한 셀에 담아 DF생성까지 한번에 실행하기
- 웹 크롤러 실행파일을 개발한다면 코드가 한 셀에 시작부터 끝까지 모두 들어가 있어야 함

In [28]:
# 크롬 드라이버 열어서 한솥 페이지 접근, 창 최대화
driver = wb.Chrome()
driver.get("https://www.hsd.co.kr/menu/menu_list")
driver.maximize_window()
time.sleep(2)

# try - except문으로 더보기 버튼 전부 누르기
try :
    while True :
        btn = driver.find_element(By.CSS_SELECTOR, "a.c_05")
        btn.click()
        time.sleep(2)
except :
    print("더보기 버튼이 더이상 없네요 ㅠ_ㅠ 그래도 코드는 에러없이 이어서 동작합니다!")

# 메뉴와 가격 정보에 접근
titles = driver.find_elements(By.CSS_SELECTOR, "h4.h.fz_03")
prices = driver.find_elements(By.CSS_SELECTOR, "div.item-price > strong")

# 메뉴와 가격 텍스트만 리스트에 넣기
titles_list, prices_list = [], []

for i in tqdm(range(len(titles))) :
    titles_list.append(titles[i].text)
    prices_list.append(prices[i].text + "원")

# DF로 만들기
hansot_dic = {"메뉴명": titles_list, "가격": prices_list}
hansot_df = pd.DataFrame(hansot_dic, index=range(1, len(titles_list)+1))
hansot_df.index.name = "No."
hansot_df

더보기 버튼이 더이상 없네요 ㅠ_ㅠ 그래도 코드는 에러없이 이어서 동작합니다!

100%|██████████████████████████████████████████████████████████████████████████████████| 88/88 [00:03<00:00, 27.81it/s]

                   메뉴명       가격
No.
1                매화 연어  12,500원
2               불짬뽕 만두   2,500원
3         열무 두부강된장 비빔밥   5,500원
4         열무 감초고추장 비빔밥   5,000원
5          오향 청양 소보로덮밥   5,500원
..                 ...      ...
84    후라이드 순살(소)_케이준소스   4,000원
85          후라이드 순살(중)   7,500원
86   치킹 반반순살(양념, 후라이드)  16,900원
87       치킹 반반순살(후라이드)  16,900원
88          제주녹차 미니꿀호떡   2,500원

[88 rows x 2 columns]

In [29]:
# DF 전체 행 보기
pd.set_option("display.max_rows", None)   # None은 무한으로 출력하겠다는 뜻(출력할 행의 개수 입력 가능)
hansot_df

                        메뉴명       가격
No.
1                     매화 연어  12,500원
2                    불짬뽕 만두   2,500원
3              열무 두부강된장 비빔밥   5,500원
4              열무 감초고추장 비빔밥   5,000원
5               오향 청양 소보로덮밥   5,500원
6               소이 청양 소보로덮밥   5,500원
7          스페셜 한우함박스테이크 도시락  14,000원
8              스페셜 해바라기 도시락  13,000원
9          스페셜 숯불직화 진달래 도시락  12,000원
10          스페셜 송정식 떡갈비 도시락  11,000원
11                   매화 고등어  11,500원
12                     해바라기  10,300원
13                      진달래   8,800원
14                카츠카츠 고기고기   8,000원
15              돈까스도련님 고기고기   7,300원
16                  돈치 고기고기   6,800원
17                  새치 고기고기   7,800원
18                       동백   6,700원
19                     돈치스팸   5,500원
20              칠리 찹쌀탕수육도련님   5,000원
21                   돈까스도련님   5,200원
22                제육 돈까스도련님   5,200원
23   한우 함박스테이크& 청양 토네이도 소세지   9,000원
24       한우 함박스테이크&토네이도 소세지   9,000원
25                  송정식 떡갈비   7,200원
26                     치킨제육   5,500원
27                더블 돈까스도련님  10,500원
28           더블 칠리 찹쌀탕수육도련님   8,500원
29                   메가치킨마요   6,600원
30                    왕치킨마요   5,600원
31                    빅치킨마요   4,600원
32                     치킨마요   3,900원
33                     스팸마요   4,400원
34                     참치마요   3,800원
35               김치볶음밥&돼지불백   7,900원
36                 스팸 김치볶음밥   5,200원
37                    김치볶음밥   4,400원
38                     부대찌개   6,500원
39                 묵은지 김치찌개   6,000원
40                  돼지불백 덮밥   5,900원
41            제많덮(제육 많이 덮밥)   6,500원
42        빅 제많덮(빅 제육 많이 덮밥)   7,500원
43                숯불직화구이 덮밥   6,500원
44                 김치 제육 덮밥   5,200원
45                 왕카레돈까스덮밥   6,700원
46            오리지널 치즈 닭갈비덮밥   6,500원
47                 김치 참치 덮밥   4,900원
48               핫 치즈 닭갈비덮밥   6,500원
49                   돈까스 카레   5,100원
50                   돈까스 덮밥   4,700원
51           소불고기 감초고추장 비빔밥   6,000원
52           시골제육 두부강된장 비빔밥   6,500원
53           참치야채 감초고추장 비빔밥   4,000원
54            빅치킨마요 부대찌개 정식   8,800원
55             치킨마요 부대찌개 정식   8,100원
56                  단품 부대찌개   5,200원
57              단품 묵은지 김치찌개   4,700원
58                    단품 카레   2,900원
59                반찬 돈까스도련님   4,200원
60                    반찬 치킨   4,000원
61                  반찬 제육볶음   3,900원
62                   반찬 돈까스   2,900원
63              반찬 토네이도 소세지   3,200원
64                  반찬 고기고기   3,900원
65              반찬 고등어 데리야끼   3,900원
66                  미니반찬 김치     500원
67             미니반찬 무말랭이 무침     600원
68                     12곡밥   2,100원
69                    발아현미밥   1,900원
70                      한솥밥   1,200원
71               해시 포테이토 스틱   2,000원
72          치즈버터 해시 포테이토 스틱   2,200원
73          허니버터 해시 포테이토 스틱   2,200원
74                  뉴 감자고로케   2,700원
75                 미니 찹쌀핫도그   2,800원
76                 미니 찹쌀탕수육   2,300원
77                   케이준후라이   1,900원
78                      김피탕   6,700원
79                크림 닭강정(소)   3,900원
80                크림 닭강정(중)   9,900원
81                한솥 닭강정(소)   3,500원
82                한솥 닭강정(중)   9,000원
83        후라이드 순살(소)_양념치킨소스   4,000원
84         후라이드 순살(소)_케이준소스   4,000원
85               후라이드 순살(중)   7,500원
86        치킹 반반순살(양념, 후라이드)  16,900원
87            치킹 반반순살(후라이드)  16,900원
88               제주녹차 미니꿀호떡   2,500원

In [30]:
# DF에서 중복되는 행 삭제하기
hansot_df.drop_duplicates()

                        메뉴명       가격
No.
1                     매화 연어  12,500원
2                    불짬뽕 만두   2,500원
3              열무 두부강된장 비빔밥   5,500원
4              열무 감초고추장 비빔밥   5,000원
5               오향 청양 소보로덮밥   5,500원
6               소이 청양 소보로덮밥   5,500원
7          스페셜 한우함박스테이크 도시락  14,000원
8              스페셜 해바라기 도시락  13,000원
9          스페셜 숯불직화 진달래 도시락  12,000원
10          스페셜 송정식 떡갈비 도시락  11,000원
11                   매화 고등어  11,500원
12                     해바라기  10,300원
13                      진달래   8,800원
14                카츠카츠 고기고기   8,000원
15              돈까스도련님 고기고기   7,300원
16                  돈치 고기고기   6,800원
17                  새치 고기고기   7,800원
18                       동백   6,700원
19                     돈치스팸   5,500원
20              칠리 찹쌀탕수육도련님   5,000원
21                   돈까스도련님   5,200원
22                제육 돈까스도련님   5,200원
23   한우 함박스테이크& 청양 토네이도 소세지   9,000원
24       한우 함박스테이크&토네이도 소세지   9,000원
25                  송정식 떡갈비   7,200원
26                     치킨제육   5,500원
27                더블 돈까스도련님  10,500원
28           더블 칠리 찹쌀탕수육도련님   8,500원
29                   메가치킨마요   6,600원
30                    왕치킨마요   5,600원
31                    빅치킨마요   4,600원
32                     치킨마요   3,900원
33                     스팸마요   4,400원
34                     참치마요   3,800원
35               김치볶음밥&돼지불백   7,900원
36                 스팸 김치볶음밥   5,200원
37                    김치볶음밥   4,400원
38                     부대찌개   6,500원
39                 묵은지 김치찌개   6,000원
40                  돼지불백 덮밥   5,900원
41            제많덮(제육 많이 덮밥)   6,500원
42        빅 제많덮(빅 제육 많이 덮밥)   7,500원
43                숯불직화구이 덮밥   6,500원
44                 김치 제육 덮밥   5,200원
45                 왕카레돈까스덮밥   6,700원
46            오리지널 치즈 닭갈비덮밥   6,500원
47                 김치 참치 덮밥   4,900원
48               핫 치즈 닭갈비덮밥   6,500원
49                   돈까스 카레   5,100원
50                   돈까스 덮밥   4,700원
51           소불고기 감초고추장 비빔밥   6,000원
52           시골제육 두부강된장 비빔밥   6,500원
53           참치야채 감초고추장 비빔밥   4,000원
54            빅치킨마요 부대찌개 정식   8,800원
55             치킨마요 부대찌개 정식   8,100원
56                  단품 부대찌개   5,200원
57              단품 묵은지 김치찌개   4,700원
58                    단품 카레   2,900원
59                반찬 돈까스도련님   4,200원
60                    반찬 치킨   4,000원
61                  반찬 제육볶음   3,900원
62                   반찬 돈까스   2,900원
63              반찬 토네이도 소세지   3,200원
64                  반찬 고기고기   3,900원
65              반찬 고등어 데리야끼   3,900원
66                  미니반찬 김치     500원
67             미니반찬 무말랭이 무침     600원
68                     12곡밥   2,100원
69                    발아현미밥   1,900원
70                      한솥밥   1,200원
71               해시 포테이토 스틱   2,000원
72          치즈버터 해시 포테이토 스틱   2,200원
73          허니버터 해시 포테이토 스틱   2,200원
74                  뉴 감자고로케   2,700원
75                 미니 찹쌀핫도그   2,800원
76                 미니 찹쌀탕수육   2,300원
77                   케이준후라이   1,900원
78                      김피탕   6,700원
79                크림 닭강정(소)   3,900원
80                크림 닭강정(중)   9,900원
81                한솥 닭강정(소)   3,500원
82                한솥 닭강정(중)   9,000원
83        후라이드 순살(소)_양념치킨소스   4,000원
84         후라이드 순살(소)_케이준소스   4,000원
85               후라이드 순살(중)   7,500원
86        치킹 반반순살(양념, 후라이드)  16,900원
87            치킹 반반순살(후라이드)  16,900원
88               제주녹차 미니꿀호떡   2,500원

# 뉴발란스 랭킹 신발 정보 수집하기
- 실제로 사용자가 온라인 쇼핑을 할 때, 브라우저를 어떻게 조작하는지 생각해보고 코드로 구현해보자!

In [31]:
driver = wb.Chrome()
driver.maximize_window()
time.sleep(1)
driver.get("https://www.nbkorea.com/product/featuredList.action?cateGrpCode=250100&cIdx=1385")

### 물품의 이미지가 있는 부분을 클릭해서 물품 상세 정보 페이지로 이동

In [32]:
imgs = driver.find_elements(By.CSS_SELECTOR, "img.img_goods")
len(imgs)

117

In [33]:
imgs[0].text
# 이미지라서 컨텐츠(텍스트)는 따로 없음

''

In [34]:
# 첫번째 상품 클릭
imgs[0].click()

In [35]:
driver.back()

In [36]:
# 두번째 상품 클릭
imgs[1].click()

# <StaleElementReferenceException에러 발생 이유>
# back을 통해서 다시 기존 페이지로 돌아오면 이전에 갖고 있던 imgs의 정보가 더이상 유효하지 않아서 발생되는 에러
# (뒤로 돌아간다는 것 자체가 또 한번의 통신을 하게 되는 것이므로 가장 최근에 통신한 정보를 다시 받아서 사용해야 함)

StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=148.0.7778.217); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7f78e7de5+14895]
	chromedriver!GetHandleVerifier [0x7ff7f78e7e50+14900]
	chromedriver!(No symbol) [0x7ff7f764d5ad]
	chromedriver!(No symbol) [0x7ff7f76653ad]
	chromedriver!(No symbol) [0x7ff7f7663ab0]
	chromedriver!(No symbol) [0x7ff7f765617b]
	chromedriver!(No symbol) [0x7ff7f7653f7e]
	chromedriver!(No symbol) [0x7ff7f76585e5]
	chromedriver!(No symbol) [0x7ff7f76586af]
	chromedriver!(No symbol) [0x7ff7f76a9ae0]
	chromedriver!(No symbol) [0x7ff7f769bc4f]
	chromedriver!(No symbol) [0x7ff7f76d005a]
	chromedriver!(No symbol) [0x7ff7f769b566]
	chromedriver!(No symbol) [0x7ff7f76f486f]
	chromedriver!(No symbol) [0x7ff7f7699df8]
	chromedriver!(No symbol) [0x7ff7f769ace3]
	chromedriver!GetHandleVerifier [0x7ff7f7bfcc49+3296f9]
	chromedriver!GetHandleVerifier [0x7ff7f7bf7375+323e25]
	chromedriver!GetHandleVerifier [0x7ff7f7c1bc82+348732]
	chromedriver!GetHandleVerifier [0x7ff7f7906045+32af5]
	chromedriver!GetHandleVerifier [0x7ff7f790ecec+3b79c]
	chromedriver!GetHandleVerifier [0x7ff7f78f1bc4+1e674]
	chromedriver!GetHandleVerifier [0x7ff7f78f1d54+1e804]
	chromedriver!GetHandleVerifier [0x7ff7f78d60e7+2b97]
	KERNEL32!BaseThreadInitThunk [0x7ffc9bdee957+17]
	ntdll!RtlUserThreadStart [0x7ffc9c52427c+2c]

In [37]:
imgs = driver.find_elements(By.CSS_SELECTOR, "img.img_goods")
imgs[1].click()

In [38]:
driver.back()

In [39]:
imgs = driver.find_elements(By.CSS_SELECTOR, "img.img_goods")
imgs[2].click()

# 2번 인덱스로 접근하니 다시 첫번째 상품에 들어가짐

In [40]:
driver.back()

In [41]:
imgs = driver.find_elements(By.CSS_SELECTOR, "img.img_goods")
imgs[3].click()

In [42]:
driver.back()

In [43]:
imgs = driver.find_elements(By.CSS_SELECTOR, "div.pro_thumbNail img.img_goods")
len(imgs)

28

In [44]:
imgs[1].click()

In [45]:
driver.back()

In [46]:
imgs = driver.find_elements(By.CSS_SELECTOR, "div.pro_thumbNail img.img_goods")
imgs[2].click()

### 상품 세부 정보 수집
- 상품명, 평점, 구매 가능 사이즈, 발볼 넓이, 리뷰 개수

#### 1) 상품명

In [47]:
title = driver.find_element(By.CSS_SELECTOR, "h2.title")
title.text

'MR530SG'

#### 2) 평점

In [48]:
mean_rating = driver.find_element(By.CSS_SELECTOR, "div.crema_product_reviews_score__container")
mean_rating.text

# 별모양과 평점이 같이 선택되지만 텍스트는 평점 밖에 없으므로 부모 태그와 클래스만으로 점수를 뽑아낼 수 있음

'4.9'

#### 3) 구매 가능 사이즈

In [50]:
size = driver.find_elements(By.CSS_SELECTOR, "ul.items")
len(size)

5

In [51]:
size[0].text

''

In [52]:
for i in size : 
    print(i.text)

220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
300
D(보통)

In [53]:
size = driver.find_elements(By.CSS_SELECTOR, "#optSizeSection > ul.items")
len(size)

1

In [54]:
size[0].text
# 나오긴하지만 전체 사이즈가 한 문자열에 들어가 있음

'220\n225\n230\n235\n240\n245\n250\n255\n260\n265\n270\n275\n280\n285\n290\n300'

In [55]:
size = driver.find_elements(By.CSS_SELECTOR, "#optSizeSection > ul.items > li")
len(size)

16

In [56]:
for i in size : 
    print(i.text)

220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
300

#### input 태그
- 사용자 입력을 받기 위한 인터페이스를 제공하는 특수 태그
- 시작태그만 있고 끝태그는 없음
- 다양한 속성들을 갖고 있음
  - type : 입력형식 지정
  - value : 서버로 전송할 실제 데이터 값
  - disabled : 비활성 상태(입력 불가)

In [57]:
# 활성화와 비활성화 사이즈를 구분하기 위해 input태그 까지 접근
size = driver.find_elements(By.CSS_SELECTOR, "#optSizeSection > ul.items > li > input")
len(size)

16

#### get_attribute 함수로 속성에 접근하기
- 특정 요소 내 속성을 검색하는 함수
- 속성값이 있으면 값이 나오고 없으면 None이나 true로 반환

In [58]:
size[0].get_attribute("value")

'220'

In [59]:
# 활성화 된 220사이즈는 아무것도 나오지 않음
size[0].get_attribute("disabled")

In [60]:
print(size[0].get_attribute("disabled"))

None

In [61]:
# 비활성화 되어 있는 300사이즈는 true가 출
size[-1].get_attribute("disabled")

'true'

#### CSS_SELECTOR로 특정 태그의 속성에 접근하기
- 태그명[속성="~~"]

In [62]:
temp = driver.find_element(By.CSS_SELECTOR, 'label[for="size_220"]')
temp.text

'220'

In [63]:
temp = driver.find_element(By.CSS_SELECTOR, 'label[title="220"]')
temp.text

'220'

In [64]:
# 구매가능 사이즈와 아닌 사이즈 추출
enabled_size, disabled_size = [], []

for i in size :
    input_id = i.get_attribute("id")

    # label 태그의 for 속성에 접근
    label = driver.find_element(By.CSS_SELECTOR, f'label[for="{input_id}"]')
    label_text = label.text.strip()   # 사이즈에 대한 텍스트만 추출

    # disabled가 없다면 None이므로 아래 조건문에서 False가 됨
    is_disabled = i.get_attribute("disabled")

    if is_disabled :
        disabled_size.append(label_text)
    else :
        enabled_size.append(label_text)

print("구매가능 사이즈 :", enabled_size)
print("구매불가 사이즈 :", disabled_size)

구매가능 사이즈 : ['220', '225', '230', '235', '240', '245', '250', '255', '260', '265', '270', '275', '280']
구매불가 사이즈 : ['285', '290', '300']

#### 4) 발볼 넓이

In [66]:
#optWidthSection > ul > li > label
foot_width = driver.find_element(By.CSS_SELECTOR, "#optWidthSection > ul.items > li > label")
foot_width.text

'D(보통)'

#### 5) 리뷰 개수

In [67]:
cnt_reviews = driver.find_element(By.CSS_SELECTOR, "a.crema-product-reviews-count.crema-applied")
cnt_reviews.text

'(1,004)'

In [68]:
cnt_reviews.text[1:-1] + "개"

'1,004개'

In [ ]:
driver.back()

### 상위 4개 품목들의 정보 수집

In [73]:
for i in tqdm(range(4)) :
    imgs = driver.find_elements(By.CSS_SELECTOR, "div.pro_thumbNail img.img_goods")
    imgs[i].click()
    time.sleep(3)

    title = driver.find_element(By.CSS_SELECTOR, "h2.title")
    mean_rating = driver.find_element(By.CSS_SELECTOR, "div.crema_product_reviews_score__container")
    size = driver.find_elements(By.CSS_SELECTOR, "#optSizeSection > ul.items > li > input")
    
    enabled_size, disabled_size = [], []
    
    for j in size :
        input_id = j.get_attribute("id")
    
        # label 태그의 for 속성에 접근
        label = driver.find_element(By.CSS_SELECTOR, f'label[for="{input_id}"]')
        label_text = label.text.strip()   # 사이즈에 대한 텍스트만 추출
    
        # disabled가 없다면 None이므로 아래 조건문에서 False가 됨
        is_disabled = j.get_attribute("disabled")
    
        if is_disabled :
            disabled_size.append(label_text)
        else :
            enabled_size.append(label_text)
    
    foot_width = driver.find_element(By.CSS_SELECTOR, "#optWidthSection > ul.items > li > label")
    cnt_reviews = driver.find_element(By.CSS_SELECTOR, "a.crema-product-reviews-count.crema-applied")

    print(title.text + " - " + mean_rating.text + " - " + foot_width.text + " - " + cnt_reviews.text[1:-1]+"개")
    print("구매가능 사이즈 :", enabled_size)

    driver.back()
    time.sleep(3)

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

MR530SG - 4.9 - D(보통) - 1,007개
구매가능 사이즈 : ['220', '225', '230', '235', '240', '245', '250', '255', '260', '265', '270', '275', '280']

 25%|█████████████████████                                                               | 1/4 [00:13<00:41, 13.76s/it]

MR530KA (STEEL GREY) - 4.9 - D(보통) - 1,742개
구매가능 사이즈 : ['220', '225', '230', '235', '240', '245', '250', '255', '260', '265', '270', '275', '280', '285', '290']

 50%|██████████████████████████████████████████                                          | 2/4 [00:23<00:22, 11.43s/it]

U740BM2 (BLACK SILVER) - 4.9 - D(보통) - 3,228개
구매가능 사이즈 : ['220', '225', '230', '235', '240', '245', '250', '255', '260', '265', '270', '275', '280', '285', '290', '295']

 75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:33<00:10, 10.57s/it]

U509BG (GREY MATTER BLACK) - 5.0 - D(보통) - 213개
구매가능 사이즈 : ['220', '225', '230', '235', '240', '245', '250', '255', '260', '265', '270', '275', '280', '290']

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:42<00:00, 10.66s/it]

### 한 셀에 모든 코드 넣어서 동작시켜보세요~!
- 상위 8개 품목에 대해서 순위를 매겨 DF로 만들어보세요

In [74]:
# 크롬 열고 최대화 및 뉴발란스 사이트 이동
driver = wb.Chrome()
driver.maximize_window()
time.sleep(2)
driver.get('https://www.nbkorea.com/product/featuredList.action?cateGrpCode=250100&cIdx=1385')
time.sleep(2)
# 상품의 각 정보들을 담아줄 빈 리스트 생성(5개)
title_list, mean_rating_list, enabled_size_list, foot_width_list, cnt_reviews_list = [], [], [], [], []

# try-except문으로 8개의 상품의 세부정보에 접근
try :
    for i in tqdm(range(8)) :
        imgs = driver.find_elements(By.CSS_SELECTOR, "div.pro_thumbNail img.img_goods")
        imgs[i].click()
        time.sleep(3)
    
        title = driver.find_element(By.CSS_SELECTOR, "h2.title")
        title_list.append(title.text)
        
        mean_rating = driver.find_element(By.CSS_SELECTOR, "div.crema_product_reviews_score__container")
        mean_rating_list.append(mean_rating.text)
        
        size = driver.find_elements(By.CSS_SELECTOR, "#optSizeSection > ul.items > li > input")  
        enabled_size, disabled_size = [], []
        for j in size :
            input_id = j.get_attribute("id")
        
            # label 태그의 for 속성에 접근
            label = driver.find_element(By.CSS_SELECTOR, f'label[for="{input_id}"]')
            label_text = label.text.strip()   # 사이즈에 대한 텍스트만 추출
        
            # disabled가 없다면 None이므로 아래 조건문에서 False가 됨
            is_disabled = j.get_attribute("disabled")
        
            if is_disabled :
                disabled_size.append(label_text)
            else :
                enabled_size.append(label_text)
        enabled_size_list.append(enabled_size)
        
        foot_width = driver.find_element(By.CSS_SELECTOR, "#optWidthSection > ul.items > li > label")
        foot_width_list.append(foot_width.text)
        
        cnt_reviews = driver.find_element(By.CSS_SELECTOR, "a.crema-product-reviews-count.crema-applied")
        cnt_reviews_list.append(cnt_reviews.text[1:-1]+"개")

        driver.back()
        time.sleep(3)
        
except Exception as e :   # 에러 발생시 에러 출력
    print("에러명 :", e)

# 수집된 데이터 개수 확인(print문으로)
print("수집된 데이터 개수 확인 :")
print(len(title_list), len(mean_rating_list), len(cnt_reviews_list), len(enabled_size_list), len(cnt_reviews_list))

# DF 출력 코드
newbal_dic = {"상품명":title_list, "평점":mean_rating_list, "리뷰개수":cnt_reviews_list, 
              "구매가능 사이즈":enabled_size_list, "발볼":foot_width_list}
newbal_df = pd.DataFrame(newbal_dic, index=range(1, len(title_list)+1))
newbal_df.index.name = "순위"
newbal_df

100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:36<00:00, 12.06s/it]

수집된 데이터 개수 확인 :
8 8 8 8 8

,상품명,평점,리뷰개수,구매가능 사이즈,발볼
순위,,,,,
1,MR530SG,4.9,"1,008개","[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)
2,MR530KA (STEEL GREY),4.9,"1,743개","[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)
3,U740BM2 (BLACK SILVER),4.9,"3,228개","[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)
4,U509BG (GREY MATTER BLACK),5.0,213개,"[220, 225, 230, 235, 240, 250, 255, 260, 265, ...",D(보통)
5,W480SK5 (4E),4.9,"1,819개","[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",4E
6,U7403FT,5.0,119개,"[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)
7,U740WM2 (WHITE SILVER METALLIC),4.9,"4,951개","[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)
8,U74096I,5.0,119개,"[220, 225, 230, 235, 240, 245, 250, 255, 260, ...",D(보통)

In [75]:
pd.set_option("display.max_colwidth", None)  # 컬럼 너비를 최대치로 늘리기
newbal_df

,상품명,평점,리뷰개수,구매가능 사이즈,발볼
순위,,,,,
1,MR530SG,4.9,"1,008개","[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280]",D(보통)
2,MR530KA (STEEL GREY),4.9,"1,743개","[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290]",D(보통)
3,U740BM2 (BLACK SILVER),4.9,"3,228개","[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295]",D(보통)
4,U509BG (GREY MATTER BLACK),5.0,213개,"[220, 225, 230, 235, 240, 250, 255, 260, 265, 270, 275, 280]",D(보통)
5,W480SK5 (4E),4.9,"1,819개","[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290]",4E
6,U7403FT,5.0,119개,"[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290]",D(보통)
7,U740WM2 (WHITE SILVER METALLIC),4.9,"4,951개","[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280]",D(보통)
8,U74096I,5.0,119개,"[220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290]",D(보통)