### [실습] 사람인 신입 구인광고 데이터 수집
- 신입 채용하는 Top10 기업의 데이터를 수집해보자~!
- 공고명, 회사명, 지역, 경력, 학력 정보를 추출

In [1]:
import requests as req
U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"}
from bs4 import BeautifulSoup as bs

In [2]:
res_saramin = req.get("https://www.saramin.co.kr/zf_user/jobs/hot100", headers = U_A)
res_saramin

In [3]:
soup = bs(res_saramin.text, "lxml")
soup

<!DOCTYPE html>
<html lang="ko">
<head>
<title>전체 신입 채용정보 | 인기공고 HOT100 - 사람인</title> <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="ko-KR" http-equiv="Content-Language"/>
<meta content="86455485e27cab6986d130e4c3b90c5b516820d1" name="naver-site-verification"/>
<meta content="가장 인기있는 전체 신입 채용공고 확인하고 취업하세요! - 인기공고 HOT 100 사람인" name="Description"/>
<meta content="사람인" name="writer"/>
<meta content="전체 신입 인기공고 HOT100, 직업, 직무, 경영, 사무, 영업, IT, 디자인, 서비스, 생산, 제조, 건설, 유통, 미디어, 교육, 전문직, 근무지역, 서울, 경기, 인천, 부산, 학력, 고졸, 초대졸, 대졸, 기업유형, 대기업, 공사·공기업, 외국계기업, 스타트업, 중견기업, 중소기업, 이직, 신입, 경력, 공채, 사람인, 취업, 채용, 공채" name="keywords"/>
<meta content="nosublinks" name="naver"/> <meta content="전체 신입 채용정보 | 인기공고 HOT100 - 사람인" property="og:title"/>
<meta content="사람인" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="http://www.saraminimage.co.kr/logo/saraminsnslogo.png" property="og:image"/>
<meta content="200" property="og:image:width"/>
<meta content="200" property="og:image:height"/>
<meta content="가장 인기있는 전체 신입 채용공고 확인하고 취업하세요! - 인기공고 HOT 100 사람인" property="og:description"/>
<meta content="https://www.saramin.co.kr/zf_user/jobs/hot100" property="og:url"/>
<meta content="ko_KR" property="og:locale"/>
<meta content="1593727887570039" property="fb:app_id"/> <link href="android-app://kr.co.saramin.brandapp/https/m.saramin.co.kr/jobs/hot100" rel="alternate"/>
<link href="/sri_css/layout.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.saramin.co.kr/zf_user/jobs/hot100" rel="canonical"/>
<link href="ios-app://739013038/https/m.saramin.co.kr/jobs/hot100" rel="alternate"/>
<link href="https://m.saramin.co.kr/jobs/hot100" media="only screen and (max-width: 640px)" rel="alternate" title="mobile optimized version" type="text/html"/>
<link href="/sri_css/pattern.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/header_default.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/gnb_default_override.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/common_ui_keeping.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/components.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/jobs-hot100.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/jobs-recruit.css?v=20260604103334" media="screen, print" rel="stylesheet" type="text/css"/>
<link href="/sri_css/powerlink.css?v=20260604103334" media="all" rel="stylesheet" type="text/css"/>
<link href="/favicon.ico?ver=3" rel="favicon"/>
<link href="/favicon.ico?ver=3" rel="icon" type="image/x-icon"/>
<link href="/favicon.ico?ver=3" rel="shortcut icon" type="image/x-icon"/> <script src="//www.saraminimage.co.kr/js/libs/jquery-1.11.1.min.js" type="text/javascript"></script>
<script type="text/javascript">var $j = jQuery.noConflict();</script>
<script src="/js/libs/saramin/common.js?v=20260604103334" type="text/javascript"></script>
<!--[if lt IE 9]> <script type="text/javascript" src="//www.saramin.co.kr/js/html5shiv.min.js"></script><![endif]-->
<script src="//www.saraminimage.co.kr/js/libs/jquery.tinyscrollbar.min.js" type="text/javascript"></script>
<script src="/js/ui-component.js?v=20260604103334" type="text/javascript"></script>
<script src="/js/layout/default-layout.js?v=20260604103334" type="text/javascript"></script>
<script src="/js/company-info/sri-certification/lib/polyfill.js?v=20260604103334" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/adimg3.search/adpost/js/adpost_show_ads_v2.min.js" type="text/javascript"></script>
<script src="/js/powerlink_ui.js?v=20260604103334" type="text/javascript"></script> <script type="text/javascript">
    var nestads = window.nestads || { cmd: [] };

    document.addEventListener('DOMContentLoaded', function () {
        var useSSL = 'https:' === document.location.protocol;
        var $script = document.createElement('script');
        $script.src = (useSSL ? 'https:' : 'http:') + '//static.nestads.com/sdk/js/v2.5.4/nestads-sdk.js';
        document.body.appendChild($script);
    });
</script>
<script type="text/javascript">
    (function() {
        nestads.cmd.push(() => {
            const scriptList = ([{"inventory_code":"recruit-view_728x90","location_id":"9af1ea08-8d9f-44bd-a927-429801a8eab3","width":"728","height":"90"},{"inventory_code":"area-list_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"etc_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"CS_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"profession-list_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"logout_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"memcom_1260x60","location_id":"202cd25c-486d-43ce-bc0e-35e124291660","width":"1200","height":"57"},{"inventory_code":"member_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"talent_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"successHelper_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"companyinfo_240x90","location_id":"b374fa93-e44b-422e-bac1-f2da87ee3260","width":"240","height":"90"},{"inventory_code":"hiring_applicatns_258x136","location_id":"043b3575-153a-474a-aa2e-6a639a7d4ac1","width":"258","height":"136"},{"inventory_code":"hiring_home_main_big_894x64","location_id":"513ae9ea-18fa-4d77-8395-edcb6c337ff4","width":"894","height":"64"},{"inventory_code":"hiring_home_main_wing_160x160","location_id":"01094d82-845e-45c0-ac78-aeb2614d259a","width":"160","height":"160"},{"inventory_code":"Main-Big_543x113","location_id":"div-gpt-ad-1425521803564-0","width":"543","height":"113"},{"inventory_code":"big_1260x60","location_id":"a0bd30f0-2df2-4a6e-b802-afa8f746b539","width":"1260","height":"60"},{"inventory_code":"Main-image_230x142","location_id":"div-gpt-ad-1426837722822-0","width":"230","height":"142"},{"inventory_code":"box_300x216","location_id":"5fc011a1-5f2a-4190-8dcd-8d01d8a61382","width":"300","height":"216"},{"inventory_code":"recruit-view_250x250","location_id":"c9b4e321-23a9-4a0d-a6a8-72341ae1594f","width":"250","height":"250"},{"inventory_code":"area-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"1000-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337\t","width":"120","height":"600"},{"inventory_code":"rapid-view_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337\t","width":"120","height":"600"},{"inventory_code":"etc_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"CS_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"category-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"profession-list_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"logout_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"memcom_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"member_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"recruit-view_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"talent_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"etc_office_worker_in_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"area-list_120x240","location_id":"div-gpt-ad-1511846653839-0","width":"120","height":"240"},{"inventory_code":"1000-list_120x240","location_id":"div-gpt-ad-1511847708022-0","width":"120","height":"240"},{"inventory_code":"etc_120x240","location_id":"div-gpt-ad-1511846339912-0","width":"120","height":"240"},{"inventory_code":"CS_120x240","location_id":"div-gpt-ad-1511845587070-0","width":"120","height":"240"},{"inventory_code":"category-list_120x240","location_id":"div-gpt-ad-1511845706684-0","width":"120","height":"240"},{"inventory_code":"profession-list_120x240","location_id":"div-gpt-ad-1511846020570-0","width":"120","height":"240"},{"inventory_code":"memcom_120x240","location_id":"div-gpt-ad-1550543155169-0","width":"120","height":"240"},{"inventory_code":"member_120x240","location_id":"div-gpt-ad-1553056482914-0","width":"120","height":"240"},{"inventory_code":"recruit-view_120x240","location_id":"div-gpt-ad-1511933728215-0","width":"120","height":"240"},{"inventory_code":"talent_120x240","location_id":"div-gpt-ad-1553056822382-0","width":"120","height":"240"},{"inventory_code":"memcom_264x264","location_id":"647bcb1c-4a55-46b3-9ea5-6d44e9e451ce","width":"264","height":"264"},{"inventory_code":"memcom_300x250","location_id":"b3151939-935a-4ae0-b218-ead990612ae2","width":"300","height":"250"},{"inventory_code":"my_right_wing_5","location_id":"eab4064a-9bec-4d9a-9f3a-9248bfe87e28","width":"267","height":"314"}]) || [];
            const resumeInfo = [];
            let targetingParams = null;
            let customTargeting = null;
            if (Object.keys(resumeInfo).length > 0) {
                targetingParams = {
                    "region": !!resumeInfo.region ? [resumeInfo.region.toString()] : [],
                    "career": !!resumeInfo.career ? [resumeInfo.career.toString()] : [],
                    "career_period": !!resumeInfo.career_period || parseInt(resumeInfo.career_period) === 0 ? [resumeInfo.career_period] : [],
                    "job": !!resumeInfo.job ? [resumeInfo.job.toString()] : [],
                }
                if (resumeInfo.custom_age) {
                    customTargeting = {"custom_age": resumeInfo.custom_age};
                }
            }

            nestads.nestAdSlotList = {};
            scriptList.forEach((row) => {
                const slot = nestads.defineSlot(row.location_id, [parseInt(row.width), parseInt(row.height)], row.location_id);
                let config = {
                    banner: {
                        backgroundType: "CUSTOM",
                        backgroundColor: "#ffffff",
                        backgroundTransparency: 0.1,
                    }
                };
                if (row.inventory_code === 'box_300x216') {
                    config.premiumBannerVideo = {
                        expandedBannerSize: [1280, 512],
                        expandedPosition: "RIGHT_TOP",
                        previewVideoPlayCondition: "AUTO_START",
                        autoScroll: false,
                        backgroundType: "CUSTOM",
                        backgroundColor: "#ffffff",
                        backgroundTransparency: 0.1,
                        radius: 16
                    };
                    config.banner.radius = 16
                }
                slot.setConfig(config);
                slot.addService(window.nestads.pubAds());

                // [WMG-41252] Nestads 타겟팅 파라미터 추가 // 모든 인벤토리 코드에 적용 WMG-41563
                if (targetingParams) {
                    slot.setTargeting("gender", resumeInfo.gender || 'UNKNOWN');
                    slot.setTargeting("audienceParameters", targetingParams);
                }
                if (customTargeting) {
                    slot.setTargeting("customTargeting", customTargeting);
                }

                nestads.nestAdSlotList[row.location_id] = slot;
            });

            nestads.enableServices();

            nestads.updateAdSlot = (id) => {
                if (!!!id || !!!nestads.nestAdSlotList[id]) {
                    return;
                }
                const currentSlot = nestads.nestAdSlotList[id];
                const newSlot = nestads.defineSlot(currentSlot.divId, currentSlot.size, currentSlot.placementCode);
                newSlot.addService(nestads.pubAds());
                nestads.nestAdSlotList[id] = newSlot;
                nestads.enableServices();
            };

            window.nestads.pubAds().addEventListener("slotRenderEnded", (event) => {
                if (!!event.slot) {
                    const domId = event.slot.getSlotElementId();
                    if (!!document.getElementById(domId + '-wrapper')) {
                        document.getElementById(domId + '-wrapper').querySelector('.nest-standby-banner').style.display = 'none';
                        document.getElementById(domId + '-inner').style.display = '';
                    }
                }
            });
        });
    })();
</script>
<script>
    (function(a_,i_,r_,_b,_r,_i,_d,_g,_e){if(!a_[_b]){var n=function(){var c=i_.createElement(r_);c.onerror=function(){h.queue.filter(function(a){return 0<=_d.indexOf(a[0])}).forEach(function(a){a=a[1];a=a[a.length-1];"function"===typeof a&&a("error occur when load airbridge")})};c.async=1;c.src=_r;"complete"===i_.readyState?i_.head.appendChild(c):a_.addEventListener("load",function k(){a_.removeEventListener("load",k);i_.head.appendChild(c)})},h={queue:[],get isSDKEnabled(){return!1}};_i.concat(_d).forEach(function(c){var a=c.split("."),k=a.pop();a.reduce(function(p,q){return p[q]=p[q]||{}},h)[k]=function(){h.queue.push([c,arguments])}});a_[_b]=h;"undefined"!==typeof i_.documentMode&&(_r=_r.replace(/^https:/,""));0<_g?(_b=new (a_.XDomainRequest||a_.XMLHttpRequest),_i=function(){},_b.open("GET",_r),_b.timeout=_g,_b.onload=function(){n()},_b.onerror=_i,_b.onprogress=_i,_b.ontimeout=_i,_b.send()):n()}})(window,document,"script","airbridge","https://static.airbridge.io/sdk/latest/airbridge.min.js","init startTracking stopTracking openBanner setBanner setDownload setDownloads openDeeplink setDeeplinks sendWeb setUserAgent setMobileAppData setUserID clearUserID setUserEmail clearUserEmail setUserPhone clearUserPhone setUserAttribute removeUserAttribute clearUserAttributes setUserAlias removeUserAlias clearUserAlias clearUser setUserId setUserAttributes addUserAlias setDeviceAlias removeDeviceAlias clearDeviceAlias setDeviceIFV setDeviceIFA setDeviceGAID events.send events.signIn events.signUp events.signOut events.purchased events.addedToCart events.productDetailsViewEvent events.homeViewEvent events.productListViewEvent events.searchResultViewEvent".split(" "),["events.wait","fetchResource","createTouchpoint","createTrackingLink"],0);
    var airbridgeWebKey = 'ca79046f9e144d959f976fe69cdcb672';
    var appName = 'saramin';
    airbridge.init({
        app: appName,
        webToken: airbridgeWebKey,
        useProtectedAttributionWindow : true,
        utmParsing: true,
        cookieWindow: 1,
        forceFirstPartyCookieID: true
    });
    </script>
<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12546634-1', 'saramin.co.kr');
  ga('require', 'GTM-KN35GK2');
  ga('require','displayfeatures');
  ga('require', 'linkid');
  ga('send', 'pageview');

</script></head>
<body>
<!-- skip navi -->
<div id="skipnavigation">
<a href="#sri_section">본문 바로가기</a>
</div>
<!--// skip navi -->
<header class="" id="sri_header">
<div class="wrap_header">
<a aria-label="사람인" class="bi" data-nav-track="ga_lead|section-gnb|global_menu|ci" href="/">
<span class="frame">
</span>
</a>
<div class="search">
<button class="btn_search" data-nav-track="ga_lead|section-gnb|global_menu|search" type="button">
<svg aria-hidden="true" class="icon" focusable="false"><use xlink:href="#svg_gnb_search"></use></svg>
<span class="keyword static">
                    커리어의 시작, 사람인                </span>
<span class="keyword fixed">
                    커리어의 시작, 사람인                </span>
</button>
<!-- AI버튼 -->
<button class="btn_ai_search" href="#" onclick="location.href='/zf_user/ai-agent/career'">
<svg class="icon">
<use href="#cm-sparkle-fill"></use>
</svg>
<span class="gradient_text">AI 검색</span>
</button>
<!-- //AI버튼 -->
</div>
<div class="utility">
<div class="sign">
<a class="btn_sign signin" data-nav-track="ga_lead|section-gnb|layer_sign|signin" href="/zf_user/auth?url=%2Fzf_user%2Fjobs%2Fhot100">로그인</a>
<hr/>
<a class="btn_sign signup" data-nav-track="ga_lead|section-gnb|layer_sign|join" href="/zf_user/member/registration/join">회원가입</a>
</div>
<div class="wrap_service">
<button class="btn_service" type="button">
        기업서비스
        <svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_profile_bracket"></use></svg>
</button>
<div class="layer_member">
<ul class="services">
<li class="half_col">
<a data-nav-track="ga_lead|section-gnb|layer_comp_service|signin_comp" href="/zf_user/auth?ut=c">로그인</a>
<a data-nav-track="ga_lead|section-gnb|layer_comp_service|company_join" href="/zf_user/member/registration/join?ut=c">회원가입</a>
</li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|musthome" href="https://hiring.saramin.co.kr/home">기업홈</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|recruit-add" href="https://hiring.saramin.co.kr/recruit/add">공고 등록</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|recruit-manage" href="https://hiring.saramin.co.kr/applicant-manage">후보자 관리</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|talent_matching" href="/zf_user/memcom/talent-pool/main/search">인재풀</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|smart_recruiter" href="https://hiring.saramin.co.kr/recruit/smart">공고 요청(후불형)</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|verification" href="/zf_user/memcom/preview/custom-guide">인적성 · 평가도구</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|products" href="https://billing.saramin.co.kr/products?t_ref=main&amp;t_ref_content=member_gnb">채용상품</a></li>
<li><a data-nav-track="ga_lead|home_menu|business|" href="https://business.saramin.co.kr?utm_source=saramin&amp;utm_medium=referral&amp;utm_campaign=organic&amp;utm_content=c_drop_menu">사람인 비즈니스</a></li>
</ul>
</div>
</div>
</div>
<div class="navigation">
<button aria-expanded="false" aria-haspopup="true" class="btn_menu" data-nav-track="ga_lead|section-gnb|total_menu|open" type="button">
<svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_total_off"></use></svg>
<svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_total_on"></use></svg>
<span class="blind">전체메뉴</span>
</button>
<div class="wrap_gnb">
<div class="major recruit selected">
<a aria-current="page" class="depth1" data-nav-track="ga_lead|section-gnb|recruit|recruit" href="/zf_user/jobs/list/domestic">
<span class="txt">채용정보</span>
</a>
<ul class="depth2">
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|area" href="/zf_user/jobs/list/domestic">
<span class="txt">지역별</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|job" href="/zf_user/jobs/list/job-category">
<span class="txt">직업별</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|area_subway" href="/zf_user/jobs/list/subway">

### Top 10 기업 리스트

In [4]:
# Top10 기업
blank = soup.select("div.col.company_nm > a.str_tit")
blank

[<a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=TFkvTjUrQlBaaHNQNTJKU3FIeVdHZz09" target="_blank">
                             (주)엘티엔터테인먼트                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=YTNCWG1veC9XY3AzaFNIKyt5RlE2dz09" target="_blank">
                             (주)한화                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=STZvalU1L3ltME9udGFzL281T0hwQT09" target="_blank">
                             에스케이하이닉스(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ZHdGYm5lTmJEWmVjWkRTcVZISEhYQT09" target="_blank">
                             미스토코리아(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ekxLdTRReE9FMzNhWC82SWk4MmlFUT09" target="_blank">
                             하이트진로음료(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=Y25kTWdyM1JQMDFieWl0M0xrSUNnZz09" target="_blank">
                             (주)이마트                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=czY5UGhqODhESXZCTHhMREFnV3VWdz09" target="_blank">
                             (주)엘지씨엔에스                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=YUxndlQ2Z1psUEJQYTVjS3ZXd1ppQT09" target="_blank">
                             ㈜동화엔텍                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=eEUyVVowUCs4SE93bTBXOUpFYjFpdz09" target="_blank">
                             (주)윈스테크넷                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ZnZRYzVqTmxJMndBU3ZkUFFIK2tCZz09" target="_blank">
                             한국투자신탁운용(주)                        </a>]

In [5]:
# Top 10 기업 데이터
for i in blank:
    print(i.text)

                            (주)엘티엔터테인먼트

                            (주)한화

                            에스케이하이닉스(주)

                            미스토코리아(주)

                            하이트진로음료(주)

                            (주)이마트

                            (주)엘지씨엔에스

                            ㈜동화엔텍

                            (주)윈스테크넷

                            한국투자신탁운용(주)

In [80]:
len(blank)

10

### 1) 공고명

In [6]:
# 공고명
title = soup.select("a.str_tit > span")
title

[<span>르한스 레스토랑 BOH 파트 채용 공고</span>,
 <span>제주 드림타워 복합리조트 [카지노&amp;호텔] 대규모 신입 공채</span>,
 <span>2026년 상반기 신입사원 모집</span>,
 <span>2026년 청년 Hy-Five 인턴 채용 15기</span>,
 <span>미스토코리아(FILA) 2026 대졸 신입사원 공개채용</span>,
 <span>[하이트진로음료] 생산관리 (자재관리) 신입채용</span>,
 <span>이마트 점포 신선직무 신입사원 채용</span>,
 <span>[신입] 2026년 상반기 신입사원 수시채용(AX/DX Engineer)</span>,
 <span>㈜동화엔텍 2026년 하반기 공개채용</span>,
 <span>클라우드 시큐리티 스쿨 교육생 모집 (부산)</span>,
 <span>2026년 채용연계형 인턴 공개채용</span>]

In [7]:
for i in title[1:]:
    print(i.text)

제주 드림타워 복합리조트 [카지노&호텔] 대규모 신입 공채
2026년 상반기 신입사원 모집
2026년 청년 Hy-Five 인턴 채용 15기
미스토코리아(FILA) 2026 대졸 신입사원 공개채용
[하이트진로음료] 생산관리 (자재관리) 신입채용
이마트 점포 신선직무 신입사원 채용
[신입] 2026년 상반기 신입사원 수시채용(AX/DX Engineer)
㈜동화엔텍 2026년 하반기 공개채용
클라우드 시큐리티 스쿨 교육생 모집 (부산)
2026년 채용연계형 인턴 공개채용

### 2) 회사명

In [8]:
comp = soup.select("div.col.company_nm > a.str_tit")
comp

[<a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=TFkvTjUrQlBaaHNQNTJKU3FIeVdHZz09" target="_blank">
                             (주)엘티엔터테인먼트                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=YTNCWG1veC9XY3AzaFNIKyt5RlE2dz09" target="_blank">
                             (주)한화                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=STZvalU1L3ltME9udGFzL281T0hwQT09" target="_blank">
                             에스케이하이닉스(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ZHdGYm5lTmJEWmVjWkRTcVZISEhYQT09" target="_blank">
                             미스토코리아(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ekxLdTRReE9FMzNhWC82SWk4MmlFUT09" target="_blank">
                             하이트진로음료(주)                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=Y25kTWdyM1JQMDFieWl0M0xrSUNnZz09" target="_blank">
                             (주)이마트                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=czY5UGhqODhESXZCTHhMREFnV3VWdz09" target="_blank">
                             (주)엘지씨엔에스                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=YUxndlQ2Z1psUEJQYTVjS3ZXd1ppQT09" target="_blank">
                             ㈜동화엔텍                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=eEUyVVowUCs4SE93bTBXOUpFYjFpdz09" target="_blank">
                             (주)윈스테크넷                        </a>,
 <a class="str_tit" href="/zf_user/company-info/view-inner-recruit?csn=ZnZRYzVqTmxJMndBU3ZkUFFIK2tCZz09" target="_blank">
                             한국투자신탁운용(주)                        </a>]

In [9]:
for i in comp:
    print(i.text)

                            (주)엘티엔터테인먼트

                            (주)한화

                            에스케이하이닉스(주)

                            미스토코리아(주)

                            하이트진로음료(주)

                            (주)이마트

                            (주)엘지씨엔에스

                            ㈜동화엔텍

                            (주)윈스테크넷

                            한국투자신탁운용(주)

### 3) 지역

In [10]:
loc = soup.select("li > p.work_place")
loc

[<p class="work_place">서울 성북구</p>,
 <p class="work_place">제주 제주시 외</p>,
 <p class="work_place">서울 중구 외</p>,
 <p class="work_place">경기 이천시</p>,
 <p class="work_place">서울 성북구 외</p>,
 <p class="work_place">충북 청주시 외</p>,
 <p class="work_place">서울 성동구 외</p>,
 <p class="work_place">서울 강서구 외</p>,
 <p class="work_place">부산 강서구</p>,
 <p class="work_place">부산 해운대구 외</p>,
 <p class="work_place">서울 영등포구</p>]

In [11]:
for i in loc[1:]:
    print(i.text)

제주 제주시 외
서울 중구 외
경기 이천시
서울 성북구 외
충북 청주시 외
서울 성동구 외
서울 강서구 외
부산 강서구
부산 해운대구 외
서울 영등포구

###  4) 경력

In [12]:
exp = soup.select("li > p.career")
exp

[<p class="career">신입 · 경력 · 정규직</p>,
 <p class="career">신입 · 정규직 외</p>,
 <p class="career">신입 · 정규직</p>,
 <p class="career">경력무관 · 정규직 외</p>,
 <p class="career">신입 · 인턴직</p>,
 <p class="career">신입 · 정규직</p>,
 <p class="career">신입 · 정규직</p>,
 <p class="career">신입 · 정규직</p>,
 <p class="career">경력무관 · 정규직 외</p>,
 <p class="career">경력무관 · 교육생</p>,
 <p class="career">신입 · 인턴직</p>]

In [13]:
for i in exp[1:]:
    print(i.text)

신입 · 정규직 외
신입 · 정규직
경력무관 · 정규직 외
신입 · 인턴직
신입 · 정규직
신입 · 정규직
신입 · 정규직
경력무관 · 정규직 외
경력무관 · 교육생
신입 · 인턴직

### 5) 학력

In [14]:
edu = soup.select("li > p.education")
edu

[<p class="education">학력무관</p>,
 <p class="education">학력무관</p>,
 <p class="education">대학교(4년)↑</p>,
 <p class="education">학력무관</p>,
 <p class="education">대학교(4년)↑</p>,
 <p class="education">대학교(4년)↑</p>,
 <p class="education">대학(2,3년)↑</p>,
 <p class="education">대학교(4년)↑</p>,
 <p class="education">대학교(4년)↑</p>,
 <p class="education">대학(2,3년)↑</p>,
 <p class="education">대학교(4년)↑</p>]

In [15]:
for i in edu[1:]:
    print(i.text)

학력무관
대학교(4년)↑
학력무관
대학교(4년)↑
대학교(4년)↑
대학(2,3년)↑
대학교(4년)↑
대학교(4년)↑
대학(2,3년)↑
대학교(4년)↑

### DF 만들기

In [133]:
len(comp)

10

In [18]:
import pandas as pd

In [16]:
title_list = []
comp_list = []
loc_list = []
exp_list = []
edu_list = []

for i in range(len(comp)): #  comp만 10개여서 comp개수 기준으로 반복문돌림, 애초에 range(10)으로 하면 됨
    comp_list.append(comp[i].text.strip())
    # 0번 인덱스는 필요없으니까 +1부터 시작함
    title_list.append(title[i+1].text.strip())
    loc_list.append(loc[i+1].text.strip())
    exp_list.append(exp[i+1].text.strip())
    edu_list.append(edu[i+1].text.strip())

In [19]:
job_df = pd.DataFrame({"공고명":comp_list,
                      "회사명":title_list,
                      "지역":loc_list,
                      "경력":exp_list,
                      "학력":edu_list},
                     index = range(1,11))
job_df.index.name = "순위" # 인덱스 이름 설정
job_df

,공고명,회사명,지역,경력,학력
순위,,,,,
1,(주)엘티엔터테인먼트,제주 드림타워 복합리조트 [카지노&호텔] 대규모 신입 공채,제주 제주시 외,신입 · 정규직 외,학력무관
2,(주)한화,2026년 상반기 신입사원 모집,서울 중구 외,신입 · 정규직,대학교(4년)↑
3,에스케이하이닉스(주),2026년 청년 Hy-Five 인턴 채용 15기,경기 이천시,경력무관 · 정규직 외,학력무관
4,미스토코리아(주),미스토코리아(FILA) 2026 대졸 신입사원 공개채용,서울 성북구 외,신입 · 인턴직,대학교(4년)↑
5,하이트진로음료(주),[하이트진로음료] 생산관리 (자재관리) 신입채용,충북 청주시 외,신입 · 정규직,대학교(4년)↑
6,(주)이마트,이마트 점포 신선직무 신입사원 채용,서울 성동구 외,신입 · 정규직,"대학(2,3년)↑"
7,(주)엘지씨엔에스,[신입] 2026년 상반기 신입사원 수시채용(AX/DX Engineer),서울 강서구 외,신입 · 정규직,대학교(4년)↑
8,㈜동화엔텍,㈜동화엔텍 2026년 하반기 공개채용,부산 강서구,경력무관 · 정규직 외,대학교(4년)↑
9,(주)윈스테크넷,클라우드 시큐리티 스쿨 교육생 모집 (부산),부산 해운대구 외,경력무관 · 교육생,"대학(2,3년)↑"
10,한국투자신탁운용(주),2026년 채용연계형 인턴 공개채용,서울 영등포구,신입 · 인턴직,대학교(4년)↑

### 네이버페이증권 데이터 크롤링
- 시장지표 탭에서 세계 각국의 통화명과 매매기준율을 크롤링하기

In [20]:
res = req.get("https://finance.naver.com/marketindex/", headers = U_A)
res

In [21]:
soup = bs(res.text, "lxml")
soup

<html><head><script language="javascript" src="/template/head_js.naver?referer=info.finance.naver.com&amp;menu=marketindex&amp;submenu=market"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/js/jindo.1.5.3.element-text-patch.js" type="text/javascript"></script>
</head><body><div id="container" style="padding-bottom:0px;">
<div class="market_include">
<div class="market_data">
<div class="market1">
<div class="title">
<h2 class="h_market1"><span>환전 고시 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="exchangeList">
<li class="on">
<a class="head usd" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdt', '', '', event);">
<h3 class="h_lst"><span class="blind">미국 USD</span></h3>
<div class="head_info point_up">
<span class="value">1,535.00</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">1.00</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05 09:15</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">33</span>회</span>
</div>
</li>
<li class="">
<a class="head jpy" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyt', '', '', event);">
<h3 class="h_lst"><span class="blind">일본 JPY(100엔)</span></h3>
<div class="head_info point_up">
<span class="value">959.46</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">0.68</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05 09:15</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">33</span>회</span>
</div>
</li>
<li class="">
<a class="head eur" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurt', '', '', event);">
<h3 class="h_lst"><span class="blind">유럽연합 EUR</span></h3>
<div class="head_info point_dn">
<span class="value">1,782.44</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.22</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05 09:15</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">33</span>회</span>
</div>
</li>
<li class="">
<a class="head cny" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyt', '', '', event);">
<h3 class="h_lst"><span class="blind">중국 CNY</span></h3>
<div class="head_info point_up">
<span class="value">226.47</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">0.09</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05 09:15</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">33</span>회</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market2">
<div class="title">
<h2 class="h_market2"><span>국제 시장 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="worldExchangeList">
<li class="on">
<a class="head jpy_usd" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyut', '', '', event);">
<h3 class="h_lst"><span class="blind">달러/일본 엔</span></h3>
<div class="head_info point_up">
<span class="value">159.9800</span>
<span class="txt_jpy"><span class="blind">엔</span></span>
<span class="change">0.0400</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyuc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_eur" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdt', '', '', event);">
<h3 class="h_lst"><span class="blind">유로/달러</span></h3>
<div class="head_info point_up">
<span class="value">1.1631</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0020</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_gbp" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdt', '', '', event);">
<h3 class="h_lst"><span class="blind">영국 파운드/달러</span></h3>
<div class="head_info point_up">
<span class="value">1.3444</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0009</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_idx" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indt', '', '', event);">
<h3 class="h_lst"><span class="blind">달러인덱스</span></h3>
<div class="head_info point_dn">
<span class="value">99.3800</span>
<span class="change"> 0.1200</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">ICE 기준</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market3">
<div class="title">
<h2 class="h_market3"><span>유가·금시세</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="oilGoldList">
<li class="on">
<a class="head wti" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtit', '', '', event);">
<h3 class="h_lst"><span class="blind">WTI</span></h3>
<div class="head_info point_dn">
<span class="value">93.04</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 2.98</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtic', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">NYMEX(뉴욕상업거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gasoline" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilt', '', '', event);">
<h3 class="h_lst"><span class="blind">휘발유</span></h3>
<div class="head_info point_up">
<span class="value">2010.25</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">0.06</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05</span>
<span class="source">한국석유공사 Opinet 기준</span>
</div>
</li>
<li class="">
<a class="head gold_inter" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국제 금</span></h3>
<div class="head_info point_up">
<span class="value">4505.0</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">38.10</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.04</span>
<span class="source">COMEX(뉴욕상품거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gold_domestic" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국내 금</span></h3>
<div class="head_info point_dn">
<span class="value">219739.68</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1,127.44</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.06.05 09:14</span>
<span class="source">신한은행 기준</span>
							(<span class="num">24</span>회차)
					</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
</div>
</div>
<div class="marketindex_content _replaceNewsLink" id="content">
<div class="section_news">
<h3 class="h_market"><span>환율 주요뉴스</span></h3>
<div class="list_area">
<ul>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005772169" onclick="clickcr(this, 'mhn.list', '277_0005772169', '0', event);">원·달러 환율 0.7원 내린 1529.0원</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.05 09:01</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0016120878" onclick="clickcr(this, 'mhn.list', '001_0016120878', '1', event);">구윤철 "금융외환시장 변동성 확대·민생물가</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.05 08:18</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=011&amp;article_id=0004627884" onclick="clickcr(this, 'mhn.list', '011_0004627884', '2', event);">브라질산 계란 수입·돼지·닭고기 할당관세.</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.05 06:31</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005772035" onclick="clickcr(this, 'mhn.list', '277_0005772035', '3', event);">외국인 7조원 순매도…원·달러 환율 야간거</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 18:34</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0016120618" onclick="clickcr(this, 'mhn.list', '001_0016120618', '4', event);">환율, 야간거래서 1,540원 넘어…금융위</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 18:22</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0016120593" onclick="clickcr(this, 'mhn.list', '001_0016120593', '5', event);">외인 7조 순매도에 환율 1,540원 넘어</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 17:56</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=011&amp;article_id=0004627764" onclick="clickcr(this, 'mhn.list', '011_0004627764', '6', event);">美 금리인상 우려에 외국인 ‘7조 매도 폭</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 17:34</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005772021" onclick="clickcr(this, 'mhn.list', '277_0005772021', '7', event);">부총리 구두개입에도…원·달러 환율, 152</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 17:25</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005772017" onclick="clickcr(this, 'mhn.list', '277_0005772017', '8', event);">[속보]원·달러 환율, 야간거래서 1540</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 17:16</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=015&amp;article_id=0005295056" onclick="clickcr(this, 'mhn.list', '015_0005295056', '9', event);">[속보] 환율, 야간거래서 1540원 넘어</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>06.04 17:12</span>
</li>
</ul>
</div>
<a class="btn_more" href="/news/news_list.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429" onclick="clickcr(this, 'mhn.more', '', '', event);"><img alt="더보기" height="18" src="https://ssl.pstatic.net/static/nfinance/btn_more.gif" width="34"/></a>
</div>
<div class="tab_default1" id="tab_section">
<ul>
<li class="on"><a href="./?tabSel=exchange#tab_section" onclick="clickcr(this, 'mtb.exnoti', '', '', event);"><span class="tab1">환전고시 환율</span></a></li>
<li class=""><a href="./?tabSel=worldExchange#tab_section" onclick="clickcr(this, 'mtb.interex', '', '', event);"><span class="tab2">국제시장 환율</span></a></li>
<li class=""><a href="./?tabSel=gold#tab_section" onclick="clickcr(this, 'mtb.oilgold', '', '', event);"><span class="tab3">유가 금시세</span></a></li>
<li class=""><a href="./?tabSel=materials#tab_section" onclick="clickcr(this, 'mtb.material', '', '', event);"><span class="tab4">원자재</span></a></li>
</ul>
<h2 class="blind">환전고시 환율</h2>
</div>
<div class="section_calculator">
<h3 class="h_calculator"><span>환율계산기 (매매기준율 기준)</span></h3>
<div class="calculator">
<div class="inner">
<div class="input">
<div class="selectbox-noscript" id="sInput">
<select class="selectbox-source" id="select_from">
<option label="1" value="1">대한민국 원 KRW</option>
<option class="selectbox-default" label="1" selected="selected" value="1535.0"> 미국 달러 USD</option>
<option label="1" value="1535.0"> 미국 달러 USD</option>
<option label="1" value="1782.44"> 유럽연합 유로 EUR</option>
<option label="100" value="9.5946"> 일본 엔 JPY</option>
<option label="1" value="226.47"> 중국 위안 CNY</option>
<option label="1" value="195.93"> 홍콩 달러 HKD</option>
<option label="1" value="48.72"> 대만 달러 TWD</option>
<option label="1" value="2059.89"> 영국 파운드 GBP</option>
<option label="1" value="3986.91"> 오만 리알 OMR</option>
<option label="1" value="1103.8"> 캐나다 달러 CAD</option>
<option label="1" value="1944.88"> 스위스 프랑 CHF</option>
<option label="1" value="163.55"> 스웨덴 크로나 SEK</option>
<option label="1" value="1093.61"> 호주 달러 AUD</option>
<option label="1" value="900.43"> 뉴질랜드 달러 NZD</option>
<option label="1" value="73.67"> 체코 코루나 CZK</option>
<option label="1" value="1.71"> 칠레 페소 CLP</option>
<option label="1" value="33.32"> 튀르키예 뉴리라 TRY</option>
<option label="1" value="0.43"> 몽골 투그릭 MNT</option>
<option label="1" value="529.07"> 이스라엘 세켈 ILS</option>
<option label="1" value="238.47"> 덴마크 크로네 DKK</option>
<option label="1" value="164.26"> 노르웨이 크로네 NOK</option>
<option label="1" value="408.85"> 사우디아라비아 리얄 SAR</option>
<option label="1" value="4968.6"> 쿠웨이트 디나르 KWD</option>
<option label="1" value="4070.75"> 바레인 디나르 BHD</option>
<option label="1" value="417.9"> 아랍에미리트 디르함 AED</option>
<option label="1" value="2165.02"> 요르단 디나르 JOD</option>
<option label="1" value="29.62"> 이집트 파운드 EGP</option>
<option label="1" value="46.93"> 태국 바트 THB</option>
<option label="1" value="1194.74"> 싱가포르 달러 SGD</option>
<option label="1" value="382.03"> 말레이시아 링깃 MYR</option>
<option label="100" value="0.0852"> 인도네시아 루피아 IDR</option>
<option label="1" value="421.38"> 카타르 리얄 QAR</option>
<option label="1" value="3.16"> 카자흐스탄 텡게 KZT</option>
<option label="1" value="1194.74"> 브루나이 달러 BND</option>
<option label="1" value="16.02"> 인도 루피 INR</option>
<option label="1" value="5.51"> 파키스탄 루피 PKR</option>
<option label="1" value="12.51"> 방글라데시 타카 BDT</option>
<option label="1" value="24.96"> 필리핀 페소 PHP</option>
<option label="1" value="88.8"> 멕시코 페소 MXN</option>
<option label="1" value="303.09"> 브라질 레알 BRL</option>
<option label="100" value="0.0584"> 베트남 동 VND</option>
<option label="1" value="93.93"> 남아프리카 공화국 랜드 ZAR</option>
<option label="1" value="20.91"> 러시아 루블 RUB</option>
<option label="1" value="5.03"> 헝가리 포린트 HUF</option>
<option label="1" value="420.58"> 폴란드 즈워티 PLN</option>
<option label="1" value="4.55"> 스리랑카 루피 LKR</option>
<option label="1" value="11.51"> 알제리 알제리 디나르 DZD</option>
<option label="1" value="11.87"> 케냐 실링 KES</option>
<option label="1" value="0.43"> 콜롬비아 페소 COP</option>
<option label="1" value="0.59"> 탄자니아 실링 TZS</option>
<option label="1" value="10.02"> 네팔 루피 NPR</option>
<option label="1" value="339.05"> 루마니아 레우 RON</option>
<option label="1" value="240.8"> 리비아 리비아 디나르 LYD</option>
<option label="1" value="190.14"> 마카오 파타카 MOP</option>
<option label="1" value="0.73"> 미얀마 짯 MMK</option>
<option label="1" value="9.66"> 에티오피아 비르 ETB</option>
<option label="1" value="0.13"> 우즈베키스탄 숨 UZS</option>
<option label="1" value="0.38"> 캄보디아 리엘 KHR</option>
<option label="1" value="696.05"> 피지 피지 달러 FJD</option>
</select>
<div class="selectbox-box" onclick="clickcr(this, 'exl*c.clist1', '', '', event);">
<div class="selectbox-label"></div>
</div>
<div class="selectbox-layer ly_calculator">
<div class="selectbox-list"></div>
</div>
</div>
<div class="input_area" id="input_from">
<input id="input_from_money" maxlength="10" onclick="clickcr(this, 'exl*c.unit1', '', '', event);" onfocus="changeActiveInput('from', 'to'); return false;" onkeyup="calcExchange('from', 'to', 'on', event);" type="text" value="1"/>
<img alt="" height="13" id="img_from_monetary" src="https://ssl.pstatic.net/static/nfinance/img_money_USD.gif" width="26"/>

In [22]:
cur = soup.select("td.tit > a")
cur

[]

In [23]:
base_rate = soup.select("td.sale")
base_rate

[]

###  iframe태그
- 다른 서버의 웹 페이지 데이터나 리소스를 현재 서버읭 웹 페이지에 포함 시켜서 보여주는 HTML 태그
- 웹 페이지 내에 독립적인 작은 창으로 다른 서버의 데이터를 가져와 삽입하여 보여줄때 사용함
- 웹 페이지에 보여줄 데이터가 많고 실시간으로 변한다면 한번에 접급할떄 그만큼 소모되는 자원이 많아 속도가 느려질 수 있는데, 이를 방지하기 위해 데이터를 일부만 보여줄 수 있고 따로 관리가 가능한 iframe을 사용함(상품 판매 사이트에서 리뷰데이터와 같이 따로 관리해야하는 데이터의 양이 많은 경우 사용)
- iframe 태그를 활용하여 데이터를 출력시켜주고 있다면 기존처럼 접근이 불가하고, 해당 데이터가 있는 원천 서버의 주소로 접근해야함

In [24]:
# iframe 태그가 있는 원처 서버주소로 새롭게 요청
# document 쪽에 있는 URL의 주소 복사!
res_iframe = req.get("https://finance.naver.com/marketindex/exchangeList.naver", headers = U_A)
res_iframe

In [25]:
soup_iframe = bs(res_iframe.text, "lxml")
soup_iframe

<html lang="ko">
<head>
<title>Npay 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/css/finance.css" rel="stylesheet" type="text/css"/>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/js/ntm.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260520175448/js/nLog.js" type="text/javascript"></script>
</head>
<body>
<div class="tbl_area">
<table border="1" class="tbl_exchange" summary="환전 고시 환율 리스트">
<caption>환전 고시 환율</caption>
<colgroup>
<col width="162"/>
<col width="92"/>
<col width="92"/>
<col width="92"/>
<col width="93"/>
<col width="92"/>
<col width="90"/>
</colgroup>
<thead>
<tr>
<th class="th_ex1" rowspan="2">
<a href="#" onclick="javascript:changeOrder('exchange'); return false;"><span>통화명</span></a></th>
<th class="th_ex2" rowspan="2"><span>매매기준율</span></th>
<th class="th_ex3" colspan="2"><span>현찰</span></th>
<th class="th_ex4" colspan="2"><span>송금</span></th>
<th class="th_ex6" rowspan="2"><span>미화환산율</span></th>
</tr>
<tr>
<th class="th_ex7"><span>사실 때 </span></th>
<th class="th_ex8"><span>파실 때 </span></th>
<th class="th_ex9"><span>보내실 때 </span></th>
<th class="th_ex10"><span>받으실 때</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,535.00</td>
<td>


						1,561.86

				</td>
<td>


						1,508.14

				</td>
<td>


						1,550.00

				</td>
<td>


						1,520.00

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,782.44</td>
<td>


						1,817.91

				</td>
<td>


						1,746.97

				</td>
<td>


						1,800.26

				</td>
<td>


						1,764.62

				</td>
<td>1.161</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">959.46</td>
<td>


						976.25

				</td>
<td>


						942.67

				</td>
<td>


						968.86

				</td>
<td>


						950.06

				</td>
<td>0.625</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">226.47</td>
<td>


						237.79

				</td>
<td>


						215.15

				</td>
<td>


						228.73

				</td>
<td>


						224.21

				</td>
<td>0.148</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">195.93</td>
<td>


						199.78

				</td>
<td>


						192.08

				</td>
<td>


						197.88

				</td>
<td>


						193.98

				</td>
<td>0.128</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">48.72</td>
<td>


						55.10

				</td>
<td>


						43.85

				</td>
<td>


						49.25

				</td>
<td>


						48.19

				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">2,059.89</td>
<td>


						2,100.46

				</td>
<td>


						2,019.32

				</td>
<td>


						2,080.48

				</td>
<td>


						2,039.30

				</td>
<td>1.342</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,986.91</td>
<td>


						4,265.99

				</td>
<td>


						3,707.83

				</td>
<td>


						4,034.75

				</td>
<td>


						3,939.07

				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">1,103.80</td>
<td>


						1,125.54

				</td>
<td>


						1,082.06

				</td>
<td>


						1,114.83

				</td>
<td>


						1,092.77

				</td>
<td>0.719</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,944.88</td>
<td>


						1,983.19

				</td>
<td>


						1,906.57

				</td>
<td>


						1,964.32

				</td>
<td>


						1,925.44

				</td>
<td>1.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">163.55</td>
<td>


						168.94

				</td>
<td>


						154.23

				</td>
<td>


						165.18

				</td>
<td>


						161.92

				</td>
<td>0.107</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">1,093.61</td>
<td>


						1,115.15

				</td>
<td>


						1,072.07

				</td>
<td>


						1,104.54

				</td>
<td>


						1,082.68

				</td>
<td>0.712</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">900.43</td>
<td>


						918.16

				</td>
<td>


						882.70

				</td>
<td>


						909.43

				</td>
<td>


						891.43

				</td>
<td>0.587</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">73.67</td>
<td>


						79.93

				</td>
<td>


						67.04

				</td>
<td>


						74.48

				</td>
<td>


						72.86

				</td>
<td>0.048</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.71</td>
<td>


						1.88

				</td>
<td>


						1.54

				</td>
<td>


						1.73

				</td>
<td>


						1.69

				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">33.32</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						33.68

				</td>
<td>


						32.96

				</td>
<td>0.022</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.43</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						0.43

				</td>
<td>


						0.43

				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">529.07</td>
<td>


						581.97

				</td>
<td>


						486.75

				</td>
<td>


						535.41

				</td>
<td>


						522.73

				</td>
<td>0.345</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">238.47</td>
<td>


						246.33

				</td>
<td>


						224.88

				</td>
<td>


						240.85

				</td>
<td>


						236.09

				</td>
<td>0.155</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">164.26</td>
<td>


						169.68

				</td>
<td>


						154.90

				</td>
<td>


						165.90

				</td>
<td>


						162.62

				</td>
<td>0.107</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">408.85</td>
<td>


						434.60

				</td>
<td>


						380.64

				</td>
<td>


						412.93

				</td>
<td>


						404.77

				</td>
<td>0.266</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,968.60</td>
<td>


						5,291.55

				</td>
<td>


						4,571.12

				</td>
<td>


						5,018.28

				</td>
<td>


						4,918.92

				</td>
<td>3.237</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">4,070.75</td>
<td>


						4,331.27

				</td>
<td>


						3,745.09

				</td>
<td>


						4,111.45

				</td>
<td>


						4,030.05

				</td>
<td>2.652</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">417.90</td>
<td>


						440.88

				</td>
<td>


						389.07

				</td>
<td>


						422.07

				</td>
<td>


						413.73

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">2,165.02</td>
<td>


						2,357.70

				</td>
<td>


						1,991.82

				</td>
<td>


						2,191.00

				</td>
<td>


						2,139.04

				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">29.62</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						29.97

				</td>
<td>


						29.27

				</td>
<td>0.019</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">46.93</td>
<td>


						49.27

				</td>
<td>


						44.12

				</td>
<td>


						47.39

				</td>
<td>


						46.47

				</td>
<td>0.031</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">1,194.74</td>
<td>


						1,218.51

				</td>
<td>


						1,170.97

				</td>
<td>


						1,206.68

				</td>
<td>


						1,182.80

				</td>
<td>0.778</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">382.03</td>
<td>


						410.30

				</td>
<td>


						353.76

				</td>
<td>


						385.85

				</td>
<td>


						378.21

				</td>
<td>0.249</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.52</td>
<td>


						9.37

				</td>
<td>


						7.67

				</td>
<td>


						8.60

				</td>
<td>


						8.44

				</td>
<td>0.006</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">421.38</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						426.43

				</td>
<td>


						416.33

				</td>
<td>0.275</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">3.16</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						3.19

				</td>
<td>


						3.13

				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">1,194.74</td>
<td>


						1,242.52

				</td>
<td>


						1,123.06

				</td>
<td>


						1,209.07

				</td>
<td>


						1,180.41

				</td>
<td>0.778</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">16.02</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						16.20

				</td>
<td>


						15.84

				</td>
<td>0.010</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">5.51</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						5.57

				</td>
<td>


						5.45

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">12.51</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						12.66

				</td>
<td>


						12.36

				</td>
<td>0.008</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">24.96</td>
<td>


						27.45

				</td>
<td>


						22.92

				</td>
<td>


						25.20

				</td>
<td>


						24.72

				</td>
<td>0.016</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">88.80</td>
<td>


						98.12

				</td>
<td>


						79.48

				</td>
<td>


						89.68

				</td>
<td>


						87.92

				</td>
<td>0.058</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">303.09</td>
<td>


						334.00

				</td>
<td>


						272.79

				</td>
<td>


						306.72

				</td>
<td>


						299.46

				</td>
<td>0.198</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.84</td>
<td>


						6.52

				</td>
<td>


						5.16

				</td>
<td>


						5.89

				</td>
<td>


						5.79

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">93.93</td>
<td>


						101.44

				</td>
<td>


						86.42

				</td>
<td>


						95.05

				</td>
<td>


						92.81

				</td>
<td>0.061</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">20.91</td>
<td>


						22.89

				</td>
<td>


						17.26

				</td>
<td>


						21.64

				</td>
<td>


						20.18

				</td>
<td>0.014</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">5.03</td>
<td>


						5.49

				</td>
<td>


						4.63

				</td>
<td>


						5.08

				</td>
<td>


						4.98

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">420.58</td>
<td>


						454.22

				</td>
<td>


						386.94

				</td>
<td>


						425.20

				</td>
<td>


						415.96

				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.55</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						4.60

				</td>
<td>


						4.50

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">11.51</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						11.64

				</td>
<td>


						11.38

				</td>
<td>0.008</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">11.87</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						12.01

				</td>
<td>


						11.73

				</td>
<td>0.008</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.43</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						0.43

				</td>
<td>


						0.43

				</td>

In [26]:
cur_iframe = soup_iframe.select("td.tit > a")
cur_iframe[0].text

'\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t미국 USD\n\t\t\t\t\n\t\t\t\t'

In [27]:
len(cur_iframe)

58

In [33]:
br_iframe = soup_iframe.select("td.sale")
br_iframe[0].text

'1,535.00'

In [32]:
len(br_iframe)

58

In [31]:
# list로 만들어서 깔끔한 값 출력하기
cur_list, br_list = [], [] # 같이 묶어서 할 때 []도 2개 만들어야함

for i in range(58):
    cur_list.append(cur_iframe[i].text.strip())
    br_list.append(br_iframe[i].text.strip())

In [34]:
pay_df = pd.DataFrame({'통화명':cur_list,
                        '매매기준율':br_list},
                     index = range(1,59))
pay_df.index.name = "NO"
pay_df

              통화명     매매기준율
NO
1          미국 USD  1,535.00
2        유럽연합 EUR  1,782.44
3   일본 JPY (100엔)    959.46
4          중국 CNY    226.47
5          홍콩 HKD    195.93
6          대만 TWD     48.72
7          영국 GBP  2,059.89
8          오만 OMR  3,986.91
9         캐나다 CAD  1,103.80
10        스위스 CHF  1,944.88
11        스웨덴 SEK    163.55
12         호주 AUD  1,093.61
13       뉴질랜드 NZD    900.43
14         체코 CZK     73.67
15         칠레 CLP      1.71
16       튀르키예 TRY     33.32
17         몽골 MNT      0.43
18       이스라엘 ILS    529.07
19        덴마크 DKK    238.47
20       노르웨이 NOK    164.26
21    사우디아라비아 SAR    408.85
22       쿠웨이트 KWD  4,968.60
23        바레인 BHD  4,070.75
24     아랍에미리트 AED    417.90
25        요르단 JOD  2,165.02
26        이집트 EGP     29.62
27         태국 THB     46.93
28       싱가포르 SGD  1,194.74
29      말레이시아 MYR    382.03
30  인도네시아 IDR 100      8.52
31        카타르 QAR    421.38
32      카자흐스탄 KZT      3.16
33       브루나이 BND  1,194.74
34         인도 INR     16.02
35       파키스탄 PKR      5.51
36      방글라데시 BDT     12.51
37        필리핀 PHP     24.96
38        멕시코 MXN     88.80
39        브라질 BRL    303.09
40    베트남 VND 100      5.84
41  남아프리카 공화국 ZAR     93.93
42        러시아 RUB     20.91
43        헝가리 HUF      5.03
44        폴란드 PLN    420.58
45       스리랑카 LKR      4.55
46        알제리 DZD     11.51
47         케냐 KES     11.87
48       콜롬비아 COP      0.43
49       탄자니아 TZS      0.59
50         네팔 NPR     10.02
51       루마니아 RON    339.05
52        리비아 LYD    240.80
53        마카오 MOP    190.14
54        미얀마 MMK      0.73
55      에티오피아 ETB      9.66
56     우즈베키스탄 UZS      0.13
57       캄보디아 KHR      0.38
58         피지 FJD    696.05

### [실습] 만개의 레시피 데이터 크롤링
- 1page에서 레시피명, 작성자, 조회수 크롤링 하기!

In [40]:
res_re = req.get("https://www.10000recipe.com/recipe/list.html", headers = U_A)
res_re

In [37]:
soup = bs(res_re.text, "lxml")
soup

<!DOCTYPE html>
<!--[if (IE 6)|(IE 7)|(IE 8)|(IE 9)]>
<html lang="ko" xmlns="http://www.w3.org/1999/xhtml" class="old_ie">
<![endif]-->
<html class="" lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="no-cache" http-equiv="Pragma"/>
<meta content="-1" http-equiv="Expires"/>
<link href="/manifest.json" rel="manifest"/>
<meta content="1567451316868458" property="fb:pages"/>
<meta content="국내 No.1 요리앱, 10만개 이상의 레시피, 편리한 검색, 맛보장 레시피, TV쿡방 레시피, 온라인 최저가 쇼핑, 요리 공모전" name="description"/>
<meta content="" name="keywords"/>
<meta content="3eLg1zfxeZ_oO6oOOsvIxbtcW-FtDsViPVm7-CYOl8w" name="google-site-verification"/>
<meta content="1f5cc8d2183836842bd3db03bc960620" name="p:domain_verify"/>
<meta content="" name="user_id"/>
<title>요리를 즐겁게~ 만개의레시피</title>
<meta content="요리를 즐겁게~ 만개의레시피" property="kakao:title"/>
<meta content="" property="kakao:description"/>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PDPW2LX');</script>
<link href="https://recipe1.ezmember.co.kr/static/css/bootstrap_20211222.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/font_20230910.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/ez_recipe_20250928.css" rel="stylesheet" type="text/css"/>
<link href="https://www.10000recipe.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon.png" rel="apple-touch-icon"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/icon-hires.png" rel="icon" sizes="192x192"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/icon-normal.png" rel="icon" sizes="128x128"/>
<script charset="utf-8" src="https://recipe1.ezmember.co.kr/static/js/jquery-1.11.2.min.js" type="text/javascript"></script>
<script src="//static.criteo.net/js/ld/publishertag.js" type="text/javascript"></script>
<script type="text/javascript">
// Common Javascript
var _WWW_URL_ = 'https://www.10000recipe.com';
var _IMG_URL_ = 'https://recipe1.ezmember.co.kr';
var _FILE_URL_ = 'https://recipe1.ezmember.co.kr/cache';
var _CURRENT_PAGE_ = 'https://www.10000recipe.com/recipe/list.html';
var _USER_ID_ = '';
</script>
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script>
  window.googletag = window.googletag || {cmd: []};
  googletag.cmd.push(function() {
    googletag.defineSlot('/21842705582/10k_w_recipe_top', [[970, 90], [728, 90]], 'div-gpt-ad-1576827715543-0').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.pubads().collapseEmptyDivs();
    googletag.enableServices();
  });
</script>
<script async="" src="//lib.wtg-ads.com/publisher/10000recipe.com/wtg_skyscraper.js" type="text/javascript"></script>
<script async="" src="//lib.wtg-ads.com/publisher/10000recipe.com/sb_ad.js" type="text/javascript"></script>
<script type="text/javascript">
function showInfoSourcing() {
    EAD.showDialog({'title':'상품 연결 안내','url':'/recipe/info_sourcing.html','width':1020,'modal':true});
}
</script>
<!-- LOGGER(TM) TRACKING SCRIPT V.40 FOR logger.co.kr / 39580 : COMBINE TYPE / DO NOT ALTER THIS SCRIPT. -->
<script type="text/javascript">var _TRK_LID="39580";var _L_TD="ssl.logger.co.kr";var _TRK_CDMN="";</script>
<script type="text/javascript">var _CDN_DOMAIN = location.protocol == "https:" ? "https://fs.bizspring.net" : "http://fs.bizspring.net";
        (function(b,s){var f=b.getElementsByTagName(s)[0],j=b.createElement(s);j.async=true;j.src='//fs.bizspring.net/fs4/bstrk.1.js';f.parentNode.insertBefore(j,f);})(document,'script');</script>
<noscript><img alt="Logger Script" height="1" src="http://ssl.logger.co.kr/tracker.tsp?u=39580&amp;js=N" width="1"/></noscript>
<!-- END OF LOGGER TRACKING SCRIPT -->
<!-- remove adblocks -->
<script async="" nonce="_fDQcfoeJAYbeAl_CXAg1A" src="https://fundingchoicesmessages.google.com/i/pub-1557771002660658?ers=1"></script><script nonce="_fDQcfoeJAYbeAl_CXAg1A">(function() {function signalGooglefcPresent() {if (!window.frames['googlefcPresent']) {if (document.body) {const iframe = document.createElement('iframe'); iframe.style = 'width: 0; height: 0; border: none; z-index: -1000; left: -1000px; top: -1000px;'; iframe.style.display = 'none'; iframe.name = 'googlefcPresent'; document.body.appendChild(iframe);} else {setTimeout(signalGooglefcPresent, 0);}}}signalGooglefcPresent();})();</script>
</head>
<body>
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-PDPW2LX" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "vk6clm10se");
</script>
<script charset="utf-8" src="https://recipe1.ezmember.co.kr/static/js/jquery-ui-1.11.4.js" type="text/javascript"></script><link href="https://recipe1.ezmember.co.kr/static/css/jquery-ui-1.11.4_201507011.css" rel="stylesheet" type="text/css"/><script>
$(document).ready(function() {
    doRTKeyword();

    $("#srhRecipeText").keypress(function(event) {
        if (event.which == 13) {
            event.preventDefault();
            $("#frmTopRecipeSearch").submit();
        }
    }).autocomplete({
        delay: 200,
        source: "https://www.10000recipe.com/recipe/ajax.html?q_mode=autoComplete",
        focus: function(event, ui) {
            return false;
        },
        select: function(event, ui) {
            this.value = ui.item.label;
            return false;
        }
    }).focus();

    $('.ui-autocomplete').css('z-index','10000');
});



var curRtword = 2;
function doRTKeyword()
{
    var backRtword = (curRtword == 1) ? 2 : 1;
    $("#RtwordDiv_"+curRtword).hide();
    $("#RtwordDiv_"+backRtword).show();
    curRtword = backRtword;
}
</script>
<a class="rmenu_top" href="#" id="btnGogoTop" style="display:none"><span class="glyphicon glyphicon-menu-up"></span></a>
<div class="gnb" style="position: relative">
<div class="gnb_top_wrap">
<div class="gnb_top">
<h1><a href="https://www.10000recipe.com/index.html"><img alt="로고" src="https://recipe1.ezmember.co.kr/img/logo4.png"/></a></h1>
<div class="gnb_search">
<form action="https://www.10000recipe.com/recipe/list.html" id="frmTopRecipeSearch" method="get">
<div class="input-group">
<input class="form-control" id="srhRecipeText" name="q" placeholder="" style="ime-mode:active;" type="text" value=""/>
<span class="input-group-btn">
<button class="btn btn-default" onclick="$('#frmTopRecipeSearch').submit();" type="button"><span class="glyphicon glyphicon-search"></span></button>
</span>
</div>
</form>
<div class="gnb_search_word" style="display: none">
<ul id="RtwordDiv_1" style="display:none;"><li><a href="https://www.10000recipe.com/recipe/list.html?q=오이 무침">오이 무침</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부 찌개">두부 찌개</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부 조림">두부 조림</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=제육 볶음">제육 볶음</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=김치 찌개">김치 찌개</a></li></ul><ul id="RtwordDiv_2" style="display:none;"><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부">두부</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=콩 나물 국">콩 나물 국</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=미역 국">미역 국</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=된장 찌개">된장 찌개</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=감자">감자</a></li></ul> <div class="gnb_search_btn">
<a href="javascript:void(0);" onclick="doRTKeyword()"><img alt="이전" src="https://recipe1.ezmember.co.kr/img/btn_arrow2_l.gif"/></a>
<a href="javascript:void(0);" onclick="doRTKeyword()"><img alt="다음" src="https://recipe1.ezmember.co.kr/img/btn_arrow2_r.gif"/></a>
</div>
</div>
</div>
<ul class="gnb_right">
<li style="position: relative;">
<div style="position: absolute; width:100px; top: 47px; left: 0; margin-left: -25px;display:none;">
<span style="margin: 0; padding: 0; font-size: 0; display: block; text-align: center;"><img src="https://recipe1.ezmember.co.kr/img/icon_arrow10.png" width="8"/></span>
<span style="border-radius: 2px; background: #ffd200; color: #000; display: block; font-size: 11px; padding:2px 5px; text-align: center;">회원가입 +3,000</span>
</div>
<a href="https://www.10000recipe.com/user/login.html?q_path=https%3A%2F%2Fwww.10000recipe.com%2Frecipe%2Flist.html"><img alt="로그인" src="https://recipe1.ezmember.co.kr/img/ico_user.png"/></a>
</li>
<li>
<a data-original-title="레시피등록" data-target="#divModalWriteForm" data-toggle="modal" href="https://www.10000recipe.com/user/login.html?q_path=https%3A%2F%2Fwww.10000recipe.com%2Frecipe%2Flist.html" title="레시피등록"><img src="https://recipe1.ezmember.co.kr/img/tmn_write.png"/></a>
</li>
<!--li style="margin-left:50px;">
                        <a href="https://market.android.com/details?id=com.ezhld.recipe" target="_blank" data-toggle="tooltip" title="" data-original-title="앱다운로드-안드로이드"><img src="https://recipe1.ezmember.co.kr/img/tmn_app_a.png"></a>
                    </li>
                    <li>
                        <a href="https://itunes.apple.com/kr/app/yoribaeggwa-mangaeyi-resipi/id494190282?mt=8" target="_blank" data-toggle="tooltip" title="" data-original-title="앱다운로드-애플"><img src="https://recipe1.ezmember.co.kr/img/tmn_app_i.png"></a>
                    </li-->
</ul>
</div>
</div>
<div class="gnb_nav">
<ul class="gnb_nav_ea10">
<li><a href="https://www.10000recipe.com/index.html">추천</a></li>
<li><a class="active" href="https://www.10000recipe.com/recipe/list.html">분류</a></li>
<li><a href="https://www.10000recipe.com/ranking/home_new.html">랭킹</a></li>
<li><a href="https://www.10000recipe.com/issue/list.html?types=magazine">매거진</a></li>
<li>
<div class="dropdown">
<a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdownMenu1_topMenu">더보기<span aria-hidden="true" class="glyphicon glyphicon-menu-down"></span></a>
<ul aria-labelledby="dropdownMenu1" class="dropdown-menu" role="menu" style="z-index:100000;">
<li role="presentation"><a href="https://www.10000recipe.com/event/list.html" role="menuitem" tabindex="-1">이벤트</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/brand/home.html" role="menuitem" tabindex="-1">브랜드</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/chef/chef_list.html" role="menuitem" tabindex="-1">쉐프</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/chef/celeb_list.html" role="menuitem" tabindex="-1">만개 인플루언서</a></li>
</ul>
</div>
</li>
</ul>
</div>
</div>
<script>
var fromOther = 'n';
$(document).ready(function() {
    $(".ellipsis_title").ellipsis({row: 1});
    $(".ellipsis_title2").ellipsis({row: 2});

    $(window).scroll(function() {
        if ($(window).scrollTop() > $(window).height()*1.5) {
            $("#btnGogoTop").slideDown(300);
        } else {
            $("#btnGogoTop").slideUp(300);
        }
    });
    $('[data-toggle="tooltip"]').tooltip();
});

$(function() {
    $('#memLayerBtn').click(function (e) {
        // Used to stop the event bubbling..
        e.stopPropagation();
        if ($('.mem_layer').is(':visible')) {
            $('.mem_layer').hide();
        } else {
            $('.mem_layer').show();
        }
    });

    $(document).click(function () {
        $('.document_common_layer').hide();
    });

    $("#btnBlogContentsList").click(function() {
        $("#btnBlogContentsList").html('<span class="fa fa-spinner fa-spin" style="width:'+$("#btnBlogContentsList").width()+'px"></span>');
        el = $(this);
        var params = 'q_mode=get_blog_contents_list&q_portal='+$("[name=q_portal]:checked").val()+'&q_blogid='+$("#q_blogid").val();
        $.get("https://www.10000recipe.com/common/ajx_common.html?"+params, function(html) {
            $("#btnBlogContentsList").html('조회');
            $("#divBlogContentsList").html(html);
        });
    });
    $('#divModalBlogForm').on('show.bs.modal',function() {
        $.ajax({
            type: "POST",
            url: "https://www.10000recipe.com/common/ajx_common.html",
            data: "q_mode=get_blog_info",
            dataType: "json",
            success: function(json) {
                if (json['portal']) {
                    $("[id^=q_portal_]").filter('[value='+json['portal']+']').trigger('click');
                }
                if (json['blog_id']) {
                    $("#q_blogid").val(json['blog_id']);
                    $("#q_blog_select_type_id").trigger('click');
                }
            },
            error: function () {

            }
        });
    });
    doChangePortal('Naver');
});
var _blogIsSubmit = false;
function doChangePortal(portal) {
    var header = '';
    var tail = '';
    $("#top_blog_select_id").hide();
    $("#top_blog_select_url").hide();
    if (portal == 'Naver') {
        header = 'https://blog.naver.com/';
        tail = '';
        $("#top_blog_select_id").show();
    } else if (portal == 'Tistory') {
        header = 'https://';
        tail = '.tistory.com';
        $("#top_blog_select_id").show();
    } else if (portal == 'Direct') {
        $("#top_blog_select_url").show();
    }
    $("#txtBlogHeader").text(header);
    $("#txtBlogTail").text(tail);
    $("#q_portal_"+portal).prop("checked",true);
}

function doBlogSelect() {
    var selType = $("input[name='q_portal']:checked").val();
    if (selType == 'Direct') {
        var q_link = $("#q_blogurl").val();
        if ($.trim(q_link) == '') {
            alert('URL을 입력해 주세요.');
            $("#q_blogurl").focus();
            return;
        } else {
            setBlogContents(q_link);
        }
     } else {
        getBlogContentsList();
     }
}
function getBlogContentsList(page,added_params) {
    if (page == 0) return;
    if (!page) {
        page = 1;
    }
    if ($("#q_blogid").val() == '') {
        alert("블로그 주소를 입력해 주세요.");
        return;
    }
    //var blog_url = $("#txtBlogHeader").text() + $("#q_blogid").val() + $("#txtBlogTail");

    if (_blogIsSubmit) {
        alert("처리중 입니다. 잠시만 기다리세요.");
        return;
    }

    $("#q_page").val(page);
    _blogIsSubmit = true;
    var params = 'q_mode=get_blog_contents_list&q_portal='+$("[name=q_portal]:checked").val()+'&q_blogid='+$("#q_blogid").val()+'&q_scal='+$("#q_scal").val()+'&q_page='+page;
    if (added_params) {
        if (added_params.substring(0,1) != '&') params += '&';
        params += added_params;
    }

    $.ajax({
        type: "POST",
        cache: false,
        url: "https://www.10000recipe.com/common/ajx_common.html",
        data: params,
        success: function(html) {
            $("#divBlogContentsList").html(html);
            $("[id^=spanBlogContentsTitle_]").ellipsis();
            $('#divModalBlogContentsList').modal('show');
            _blogIsSubmit = false;
            return html;
        },
        error: function () {
            alert('예기치 못한 오류로 인해 실패했습니다.');
            _blogIsSubmit = false;
        }
    });
}
function setBlogContents(q_link) {
    if (typeof q_link == 'undefined' || q_link == '') {
        q_link = $("#listBlog [id^=q_link_]:checked").val();

        if (!q_link) {
            alert('블로그 컨텐츠를 선택하세요.');
            return;
        }
    }
    $("#btnSetBlogContents").html('<span class="fa fa-spinner fa-spin" style="width:' + $("#btnSetBlogContents").width() + 'px"></span>');
    if(fromOther == 'n') document.location.href = 'https://www.10000recipe.com/inbox/insert.html?ref_blog_url=' + encodeURIComponent(q_link);
    else if(fromOther == 'review') document.location.href = 'https://www.10000recipe.com/event/ins_review.html?seq=&review_seq=&ref_blog_url=' + encodeURIComponent(q_link);
}

function doSelWrite(tabs)
{
    $("[id^='writeSelectStep']").hide();
    $("#writeSelectStep"+tabs).show();
    $("[id^='selTabs']").removeClass('active');
    $("#selTabs"+tabs).addClass('active');
}

function doInstaSelect()
{
    if (!$("#q_insta_url").val())
    {
        $("#warnInstaMsg").html('ⓘ URL을 등록해 주세요.');
        return ;
    }
    $("#ailoading").show();
    $.ajax({
        type: "GET",
        cache: false,
        url: "https://www.10000recipe.com/common/ajx_common.html",
        data: "q_mode=get_insta_input_ai&insta_url="+$("#q_insta_url").val(),
        success: function(html) {
            var msg = '';
            if(html == 'NOT_EXIST') msg = 'ⓘ URL을 등록해 주세요.';
            else if(html == 'INVALID_URL') msg = 'ⓘ 사용할 수 없는 URL 입니다.';
            else if(html == 'DUPLICATE') msg = 'ⓘ 이미 등록된 인스타그램 URL 입니다.';
            else if(html == 'NOT_CONT') msg = 'ⓘ 내용을 분석할 수 없습니다. 다른 URL을 사용해주세요.';
            else if(html == 'FAILED' || html == '') msg = 'ⓘ 분석에 실패했습니다. 직접 등록하기를 추천드려요.';
            else if(html != '')
            {
                $("#ret_ai_desc").val(html);
                $("#goInputForm").submit();
            }
            $("#ailoading").hide();
            $("#warnInstaMsg").html(msg);
        },
        error: function () {
            alert('예기치 못한 오류로 인해 실패했습니다.');
            _blogIsSubmit = false;
        }
    });
}
</script>
<form action="https://www.10000recipe.com/inbox/insert.html" id="goInputForm" method="post" name="goInF">
<input id="ret_ai_desc" name="ai_desc" type="hidden" value=""/>
</form>
<div aria-hidden="true" aria-labelledby="myModalLabelss" class="modal fade" id="divModalWriteForm" role="dialog" style="z-index:100001" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content modal_new" style="width:760px">
<div class="loader_box" id="ailoading" style="display:none;">
<span class="dots-loader">Loading…</span>
<p>AI가 내용을 분석하고 있어요.<br/>잠시만 기다려주세요.</p>
</div>
<div class="modal_new_tit">
<div class="modal_new_t_l">레시피 등록</div>
<div class="modal_new_t_r"><a aria-label="Close" class="x-icon" data-dismiss="modal" href="#"></a></div>
</div>
<div class="modal_new_cont">
<div class="modal_new_c_t">레시피 등록방법을 선택해주세요.</div>
<div class="modal_new_c regi2_btn st_lg">
<a href="https://www.10000recipe.com/inbox/insert.html"><span class="regi2_btn_w">직접등록</span></a>
<a href="javascript:void(0)" id="selTabs2" onclick="doSelWrite('2')"><span class="regi2_btn_b">블로그 레시피 가져오기</span></a>
<a href="javascript:void(0)" id="selTabs3" onclick="doSelWrite('3')"><span class="regi2_btn_v">영상 레시피 가져오기</span></a>
</div>
<div id="writeSelectStep2" style="display:none;">
<div class="modal_new_c_t">레시피를 가져올 방식을 선택해 주세요.</div>
<div class="modal_new_c">
<div class="regi2_radio pad_b_20">
<span onclick="doChangePortal('Naver')"><input id="q_portal_Naver" name="q_portal" type="radio" value="Naver"/><label>네이버</label></span>

### 1) 레시피명

In [41]:
re_title = soup.select(" div.common_sp_caption_tit.line2")
re_title

[<div class="common_sp_caption_tit line2">굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피</div>,
 <div class="common_sp_caption_tit line2">들기름 두부구이 두부부침 양념장 레시피 두부반찬</div>,
 <div class="common_sp_caption_tit line2">간장버터 새송이구이</div>,
 <div class="common_sp_caption_tit line2">시금치무침 (시금치데치는 방법 시금치나물요리 나물반찬 반찬레시피)</div>,
 <div class="common_sp_caption_tit line2">칼칼한 오징어무국 맛있게 끓이는 법</div>,
 <div class="common_sp_caption_tit line2">양배추 오믈렛/다이어트 식단</div>,
 <div class="common_sp_caption_tit line2">오이고추된장무침 (사계절 먹기좋은 밑반찬 고추무침 5분 레시피)</div>,
 <div class="common_sp_caption_tit line2">아이반찬 양파소세지볶음 레시피 양파요리 초스피드반찬</div>,
 <div class="common_sp_caption_tit line2">어묵볶음 만들기 안 불고 쫄깃하게 만드는 법</div>,
 <div class="common_sp_caption_tit line2">봄 입맛 살리는 오이 달래 무침 황금 레시피</div>,
 <div class="common_sp_caption_tit line2">도시락 반찬으로 최고! 스팸감자조림♡</div>,
 <div class="common_sp_caption_tit line2">새송이버섯버터굴소스볶음 간단반찬</div>,
 <div class="common_sp_caption_tit line2">매콤하게 구워 더 맛있는 새송이버섯 매콤구이 레시피 (1봉지로 만드는 초간단 반찬)</div>,
 <div class="common_sp_caption_tit line2">[두부계란덮밥] 두부를 이용한 건강한 다이어트 밥상</div>,
 <div class="common_sp_caption_tit line2">청포묵 무침 만드는 법</div>,
 <div class="common_sp_caption_tit line2">매운빨간콩나물무침 레시피 매일반찬</div>,
 <div class="common_sp_caption_tit line2">청경채 된장 무침으로</div>,
 <div class="common_sp_caption_tit line2">여름반찬 아삭오이고추 만능된장무침 레시피</div>,
 <div class="common_sp_caption_tit line2">파프리카 겉절이 레시피 식감 살아 있는 파프리카 김치 만들기 반찬 요리</div>,
 <div class="common_sp_caption_tit line2">#최애반찬#소세지강정</div>,
 <div class="common_sp_caption_tit line2">감자볶음 레시피 감자채볶음 햄감자볶음 황금레시피</div>,
 <div class="common_sp_caption_tit line2">도토리묵김무침 레시피 아이반찬</div>,
 <div class="common_sp_caption_tit line2">즉석,오이 부추 무침(백종원양념)</div>,
 <div class="common_sp_caption_tit line2">고소한 맛이 좋은 밑반찬, 애호박버섯볶음 만들기(새우젓없이 만들기)</div>,
 <div class="common_sp_caption_tit line2">저렴하게 반찬 뚝딱!! 감자조림 만들기</div>,
 <div class="common_sp_caption_tit line2">♥[신혼밥상] 10분 뚝딱 양배추참치덮밥</div>,
 <div class="common_sp_caption_tit line2">베이컨감자채볶음</div>,
 <div class="common_sp_caption_tit line2">단무지무침 레시피 밑반찬 만들기 치자 단무지무침</div>,
 <div class="common_sp_caption_tit line2">숙주나물 무침 만들기 아삭한 숙주나물 무침 양념 레시피 깔끔한 밑반찬 요리</div>,
 <div class="common_sp_caption_tit line2">라이스페이퍼 양배추만두</div>,
 <div class="common_sp_caption_tit line2">내 인생 레시피,친정 엄마표 “파채무침”</div>,
 <div class="common_sp_caption_tit line2"> "시금치나물"</div>,
 <div class="common_sp_caption_tit line2">시금치 계란 볶음 레시피 다이어트 반찬</div>,
 <div class="common_sp_caption_tit line2">단짠단짠 고기없이깊은맛! 메추리알장조림만드는법표고버섯장조림</div>,
 <div class="common_sp_caption_tit line2">[밑반찬] 10분 밑반찬 딱딱하지않고 부드러운 오징어채</div>,
 <div class="common_sp_caption_tit line2">실패없는 무생채 레시피</div>,
 <div class="common_sp_caption_tit line2">버섯으로 관자 느낌 내는 방법! 새송이버섯간장버터구이 만들기</div>,
 <div class="common_sp_caption_tit line2">굴소스 느타리버섯볶음 만드는 법 버섯볶음 레시피</div>,
 <div class="common_sp_caption_tit line2">단짠단짠 마성의 베이컨덮밥♡</div>,
 <div class="common_sp_caption_tit line2">토마토간장샐러드 진짜 별거없는데 미치도록 맛있어요 7분 완성 초간단 샐러드</div>]

### 2) 작성자

In [42]:
re_author = soup.select("div.common_sp_caption_rv_name > a")
re_author

[<a href="/profile/recipe.html?uid=55349530"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2025/10/25/d036f260b0087a7dc4fff29e26ac10a21.png"/>Y큰손</a>,
 <a href="/profile/recipe.html?uid=77721145"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/10/14/5ed3ab6a5f58ba5a2081185096829aa81.jpg"/>써지니</a>,
 <a href="/profile/recipe.html?uid=37582108"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2024/01/23/0da383ffdbe1e1c6f0419303e997d4e81.jpg"/>요리하는허니레빗</a>,
 <a href="/profile/recipe.html?uid=45835234"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2020/10/15/679d706ae8cec3828198c200b6ed85311.jpg"/>ariel1007</a>,
 <a href="/profile/recipe.html?uid=57397925"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2026/02/01/5bed347730ccafbda452e7a89eb6dac11.png"/>급식실박실장</a>,
 <a href="/profile/recipe.html?uid=dal031"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2023/03/04/4db307c661cc92cf77a30bf530d2a0a81.f4d975082303ba44f752108dd76d5a6c"/>잔근육</a>,
 <a href="/profile/recipe.html?uid=45835234"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2020/10/15/679d706ae8cec3828198c200b6ed85311.jpg"/>ariel1007</a>,
 <a href="/profile/recipe.html?uid=17672780"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/11/02/ebabeecd253fe65af137c57a075d8c0c1.jpg"/>라피네</a>,
 <a href="/profile/recipe.html?uid=79262418"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2026/03/27/ef25aa60b58a8c02eaff94ebf10204ce1.jpg"/>눈히</a>,
 <a href="/profile/recipe.html?uid=46773240"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2026/04/01/fbd4d763efdbdcfa4c8c3733d2c76ce31.jpg"/>호수맘</a>,
 <a href="/profile/recipe.html?uid=47181483"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2019/09/17/b488938a21561b705f5c7b3d0cc9dd641.5248f77ae96fcdeeef6d3e7c54c2fcc7"/>냠냠간단요리</a>,
 <a href="/profile/recipe.html?uid=17672780"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/11/02/ebabeecd253fe65af137c57a075d8c0c1.jpg"/>라피네</a>,
 <a href="/profile/recipe.html?uid=jylhee070467"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2015/07/14/d5df3425ae205d7c98d45a531ea9e2e91.jpg"/>밥심은국력</a>,
 <a href="/profile/recipe.html?uid=27221056"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2025/11/27/0f644ba759fa983cb0b709cc510f436a1.71e57f6a7c2242d6af54d15f45f59f77"/>쑤블리</a>,
 <a href="/profile/recipe.html?uid=16713232"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2023/08/04/14e5112b18cc05d622094d2d21b6d60b1.f60bc376173010d6e30cb73d0c923c9a"/>뚜루</a>,
 <a href="/profile/recipe.html?uid=17672780"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/11/02/ebabeecd253fe65af137c57a075d8c0c1.jpg"/>라피네</a>,
 <a href="/profile/recipe.html?uid=cheonsa12"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/08/28/cf446fbf7ba33ff0db98930392d513561.jpg"/>요리재능발견</a>,
 <a href="/profile/recipe.html?uid=32061214"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/09/16/5fe2af6da937d52fee8e3e97188d196a1.jpg"/>햇살머금은집</a>,
 <a href="/profile/recipe.html?uid=21143379"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2025/03/18/3268140b162b572b591f0994706410b01.jpg"/>요리백과사전</a>,
 <a href="/profile/recipe.html?uid=hyosup1983"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2019/06/20/bcec53bab4eb42c9489afd12d640dce31.png"/>심킹카</a>,
 <a href="/profile/recipe.html?uid=16713232"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2023/08/04/14e5112b18cc05d622094d2d21b6d60b1.f60bc376173010d6e30cb73d0c923c9a"/>뚜루</a>,
 <a href="/profile/recipe.html?uid=17672780"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/11/02/ebabeecd253fe65af137c57a075d8c0c1.jpg"/>라피네</a>,
 <a href="/profile/recipe.html?uid=98378734"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/01/30/3d8b80be133430125468cc7305e6fc4f1.jpg"/>달콤스윗맘</a>,
 <a href="/profile/recipe.html?uid=kkokkobook"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/03/01/07e84fe546461d1f21990acbcb7237581.jpg"/>꼬꼬부기</a>,
 <a href="/profile/recipe.html?uid=74338465"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2025/01/04/6c2cda7ebd91a86bc741d237a6383b631.jpg"/>한입만아내</a>,
 <a href="/profile/recipe.html?uid=fkaldbs"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2019/09/08/9d0406f5bc09d7ee45d37f99c0132a431.5cae3e8da47cd5caa7ba0bfb2db4c54c"/>행복한윤블리네</a>,
 <a href="/profile/recipe.html?uid=18528617"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2021/11/18/f1bfe3fd47e31bd172c72fc7afa5a9ee1.jpg"/>승일승훈</a>,
 <a href="/profile/recipe.html?uid=77721145"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/10/14/5ed3ab6a5f58ba5a2081185096829aa81.jpg"/>써지니</a>,
 <a href="/profile/recipe.html?uid=74288368"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2024/09/02/875a02bb7767f5e682813e7475ad41891.jpg"/>포남댁</a>,
 <a href="/profile/recipe.html?uid=gdubu33"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2016/01/29/900013400086b533aef0411aeb3ee7d71.png"/>만개의레시피</a>,
 <a href="/profile/recipe.html?uid=98378734"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/01/30/3d8b80be133430125468cc7305e6fc4f1.jpg"/>달콤스윗맘</a>,
 <a href="/profile/recipe.html?uid=62299079"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/05/02/00a012f5232ddb601ee1db15740f84f41.a3f7fa1be5f30485ad762da29c935372"/>밥차리라</a>,
 <a href="/profile/recipe.html?uid=aeaelove"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2023/03/13/6dfb00ab7f9ccebfe7d99d839b0f61491.d456ad63a7a5b1d868c685390d3c2aa4"/>춤추는루나</a>,
 <a href="/profile/recipe.html?uid=46773240"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2026/04/01/fbd4d763efdbdcfa4c8c3733d2c76ce31.jpg"/>호수맘</a>,
 <a href="/profile/recipe.html?uid=53351442"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/12/12/19eaa381c02a75893ad23d88fcf0e1541.e1544dd748e6261fee374867e359ac39"/>븟린이</a>,
 <a href="/profile/recipe.html?uid=81424037"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2026/01/22/504eec93a1dd1a31b41dd613de6582511.png"/>윤자딸</a>,
 <a href="/profile/recipe.html?uid=48794657"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2019/12/30/0c96d23a0f039a99325d354605d60f691.jpg"/>루던</a>,
 <a href="/profile/recipe.html?uid=77721145"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2022/10/14/5ed3ab6a5f58ba5a2081185096829aa81.jpg"/>써지니</a>,
 <a href="/profile/recipe.html?uid=47181483"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2019/09/17/b488938a21561b705f5c7b3d0cc9dd641.5248f77ae96fcdeeef6d3e7c54c2fcc7"/>냠냠간단요리</a>,
 <a href="/profile/recipe.html?uid=80802273"><img src="https://recipe1.ezmember.co.kr/cache/rpf/2023/11/02/3c59439108b7310153bca4a5f170fb0d1.jpg"/>아임레시피</a>]

### 3) 조회수

In [43]:
re_views = soup.select("div.common_sp_caption_rv > span.common_sp_caption_buyer")
re_views

[<span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 964</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.6만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1,893</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 4,060</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 3.1만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 3.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1,087</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 475</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 11.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 5.5만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1,245</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 4,202</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 3,734</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 3.7만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.3만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 809</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 16.8만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 520</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 3.1만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.8만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 5.6만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 7,775</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 6,278</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2,286</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1,485</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 9,357</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 4.2만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2,573</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2.2만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 767</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2.9만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 913</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 42.4만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 1.3만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 2.8만</span>,
 <span class="common_sp_caption_buyer" style="vertical-align: middle;">조회수 9,757</span>]

In [44]:
re_views[0].text[4:]

'1만'

In [45]:
len(re_views)

40

In [46]:
title_list, author_list, views_list = [],[],[]

for i in range(40):
    title_list.append(re_title[i].text.strip())
    author_list.append(re_author[i].text.strip())
    views_list.append(re_views[i].text.strip()[4:]) # '조회수' 문자열 제거하고 수치만 남기지

In [47]:
re_df = pd.DataFrame({"레시피명":title_list,
                     "작성자":author_list,
                     "조회수":views_list},
                    index = range(1,41))
re_df.index.name = "No"
re_df

                                              레시피명        작성자    조회수
No
1                      굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피        Y큰손     1만
2                       들기름 두부구이 두부부침 양념장 레시피 두부반찬        써지니    964
3                                       간장버터 새송이구이   요리하는허니레빗   1.4만
4             시금치무침 (시금치데치는 방법 시금치나물요리 나물반찬 반찬레시피)  ariel1007   1.6만
5                              칼칼한 오징어무국 맛있게 끓이는 법     급식실박실장  1,893
6                                  양배추 오믈렛/다이어트 식단        잔근육  4,060
7              오이고추된장무침 (사계절 먹기좋은 밑반찬 고추무침 5분 레시피)  ariel1007   3.1만
8                     아이반찬 양파소세지볶음 레시피 양파요리 초스피드반찬        라피네   3.4만
9                         어묵볶음 만들기 안 불고 쫄깃하게 만드는 법         눈히  1,087
10                        봄 입맛 살리는 오이 달래 무침 황금 레시피        호수맘    475
11                            도시락 반찬으로 최고! 스팸감자조림♡     냠냠간단요리  11.4만
12                               새송이버섯버터굴소스볶음 간단반찬        라피네   5.5만
13  매콤하게 구워 더 맛있는 새송이버섯 매콤구이 레시피 (1봉지로 만드는 초간단 반찬)      밥심은국력  1,245
14                    [두부계란덮밥] 두부를 이용한 건강한 다이어트 밥상        쑤블리  4,202
15                                    청포묵 무침 만드는 법         뚜루  3,734
16                              매운빨간콩나물무침 레시피 매일반찬        라피네   1.4만
17                                     청경채 된장 무침으로     요리재능발견   3.7만
18                          여름반찬 아삭오이고추 만능된장무침 레시피     햇살머금은집   1.3만
19         파프리카 겉절이 레시피 식감 살아 있는 파프리카 김치 만들기 반찬 요리     요리백과사전    809
20                                     #최애반찬#소세지강정        심킹카  16.8만
21                      감자볶음 레시피 감자채볶음 햄감자볶음 황금레시피         뚜루    520
22                                도토리묵김무침 레시피 아이반찬        라피네   3.1만
23                              즉석,오이 부추 무침(백종원양념)      달콤스윗맘   1.8만
24           고소한 맛이 좋은 밑반찬, 애호박버섯볶음 만들기(새우젓없이 만들기)       꼬꼬부기   5.6만
25                           저렴하게 반찬 뚝딱!! 감자조림 만들기      한입만아내  7,775
26                          ♥[신혼밥상] 10분 뚝딱 양배추참치덮밥    행복한윤블리네  6,278
27                                        베이컨감자채볶음       승일승훈   2.4만
28                      단무지무침 레시피 밑반찬 만들기 치자 단무지무침        써지니  2,286
29       숙주나물 무침 만들기 아삭한 숙주나물 무침 양념 레시피 깔끔한 밑반찬 요리        포남댁  1,485
30                                    라이스페이퍼 양배추만두     만개의레시피  9,357
31                          내 인생 레시피,친정 엄마표 “파채무침”      달콤스윗맘   4.2만
32                                         "시금치나물"       밥차리라  2,573
33                           시금치 계란 볶음 레시피 다이어트 반찬      춤추는루나   2.2만
34                단짠단짠 고기없이깊은맛! 메추리알장조림만드는법표고버섯장조림        호수맘    767
35                  [밑반찬] 10분 밑반찬 딱딱하지않고 부드러운 오징어채        븟린이   2.9만
36                                    실패없는 무생채 레시피        윤자딸    913
37               버섯으로 관자 느낌 내는 방법! 새송이버섯간장버터구이 만들기         루던  42.4만
38                      굴소스 느타리버섯볶음 만드는 법 버섯볶음 레시피        써지니   1.3만
39                                 단짠단짠 마성의 베이컨덮밥♡     냠냠간단요리   2.8만
40       토마토간장샐러드 진짜 별거없는데 미치도록 맛있어요 7분 완성 초간단 샐러드      아임레시피  9,757

### 1~10page의 데이터를 모두 수집해보자
- 먼저 1page와 2,3page의 url을 비교해 규칙을 찾아보기(페이지 No와 관련된 정보가 있을 것)
- 일반적으로 개발자들이 여러 page가 있는 웹 사이트를 만들때 같은 기능은 최대한 유사한 코드를 활용함

In [48]:
# tqdm : 반복문의 진행상황을 로딩바로 확인하게 해주는 함수
from tqdm import tqdm

In [49]:
title_list, author_list, views_list = [],[],[]

# 1~10page까지의 데이터 수집을 위해 반복문 작성
for page in tqdm(range(1,11,1)):
    url = f"https://www.10000recipe.com/recipe/list.html?order=reco&page={page}"
    res = req.get(url, headers = U_A)
    soup = bs(res.text, "lxml")

    re_title = soup.select(" div.common_sp_caption_tit.line2")
    re_author = soup.select("div.common_sp_caption_rv_name > a")
    re_views = soup.select("div.common_sp_caption_rv > span.common_sp_caption_buyer")

    for a in range(40):
        title_list.append(re_title[a].text.strip())
        author_list.append(re_author[a].text.strip())
        views_list.append(re_views[a].text.strip()[4:])


re_df = pd.DataFrame({"레시피명":title_list,
                     "작성자":author_list,
                     "조회수":views_list},
                    index = range(1,len(title_list)+1))
re_df.index.name = "No"
re_df

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:15<00:00,  1.54s/it]

                                         레시피명        작성자    조회수
No
1                 굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피        Y큰손     1만
2                  들기름 두부구이 두부부침 양념장 레시피 두부반찬        써지니    964
3                                  간장버터 새송이구이   요리하는허니레빗   1.4만
4        시금치무침 (시금치데치는 방법 시금치나물요리 나물반찬 반찬레시피)  ariel1007   1.6만
5                         칼칼한 오징어무국 맛있게 끓이는 법     급식실박실장  1,893
..                                        ...        ...    ...
396                   309.꽈리고추멸치조림(2026.5.27)      벚꽃조이나    148
397                                  시금치베이컨볶음      시크제이맘   2.6만
398                       입맛 확 돋우는 미나리비빔밥 레시피    작키오늘뭐먹지    350
399  햄야채 볶음밥 레시피 겨울방학 점심 메뉴 간단 한 그릇 햄 볶음밥 레시피        포남댁    552
400               가츠동 대신 비비고 만두로 계란 만두 덮밥 만들기      요리조리콩  6,153

[400 rows x 3 columns]

### 특정 키워드가 들어간 레시피만 필터링

In [61]:
# 레시피명 컬럼에서 '김치'가 포함된 행만 필터링
# str.contains: DF에서 특정 문자가 포함된 행 찾기
filtered_df = re_df[re_df["레시피명"].str.contains("감자")]

# reset_index: 인덱스 번호 재설정
# drop=True: 기존 인덱스 컬럼 삭제
filtered_df.reset_index(drop=True, inplace=True)
filtered_df.index = range(1, len(filtered_df)+1) # 필터링 된 DF의 행 개수만큼 인덱스 설정
filtered_df.index.name = "No"
filtered_df

                                              레시피명       작성자    조회수
No
1                             도시락 반찬으로 최고! 스팸감자조림♡    냠냠간단요리  11.4만
2                       감자볶음 레시피 감자채볶음 햄감자볶음 황금레시피        뚜루    520
3                            저렴하게 반찬 뚝딱!! 감자조림 만들기     한입만아내  7,775
4                                         베이컨감자채볶음      승일승훈   2.4만
5                    NO밀가루! 감자치즈호떡 아이들 간식으로 딱 좋아요.    만개의레시피   1.7만
6                                     햄 감자채볶음 만드는법      반이짝이   1.8만
7                                  감자 멸치 조림 황금 레시피       호수맘    298
8                            재료도 방법도 초간단! 떠먹는 치즈감자       제줌마  18.8만
9                           돼지고기감자조림 밥통이 거덜날 수 있어요    즐거운날랄라   5.3만
10                     감자꽈리고추조림 밥통 거덜내는 무시무시한 저녁반찬     아임레시피   1.8만
11              [매콤감자조림] 간단하고 매콤한 감자 요리 레시피 | 신혼밥상       쑤블리  5,523
12                        백종원 감자채 당근볶음 쉬운 7월제철 밑반찬    햇살머금은집  1,199
13                                일본가정식 이모모찌 (감자떡)     일본아줌마   1.4만
14                         쫀득쫀득 일본식 감자떡 '이모모찌' 만들기  녜딘Nyedin  27.9만
15  앞다리살감자조림 수십 번 해먹은 인생 레시피 저렴한 앞다리살로 만든 감자조림 맛보장     아임레시피  8,944
16                                     【스팸감자볶음만들기】      조밍키♥  74.2만
17                                   최애반찬 소시지 감자조림       쿡따라  30.9만
18                             저녁반찬 없을때 후다닥 참치감자조림      춤추는곰  16.9만
19            국민반찬 부서지지 않는 감자채 볶음 만드는 법 10분 완성 레시피      아이해피    843
20          눈사람 함박스테이크 감자샐러드로 홈파티 음식 다진 돼지고기로 간단하게      열려라쿡  6,075
21                 감자 계란국 끓이는 법 계란 감자국 간단한 맑은 국 요리       Y큰손   2.7만
22                        [No.1 감자새우덮밥] 고급스러운 중식덮밥    JUNE86     8만
23                           간단 반찬-아이 반찬으로 좋은 감자볶음       촌아짐  59.5만
24                                        치즈 웨지 감자      쿡라이프  23.2만
25                                        참치 감자 조림      밥차리라  64.8만
26                          비건베이킹인데 너무 맛있는 감자 크래커!    MJ홈베이킹   4.4만

### 함수로 코드 통합
- 매개변수는 검색할 최종 페이지, 필터링 할 검색어(디폴트는 검색어 없도록 설정)

In [59]:
# 매개변수 뒤에 ': int' 와 같은 부분은 입력되는 매개변수의 자료형을 사전에 알려주는 것
# '-> pd.DataFrame' 의 경우 반환(return)되는 자료형을 사전에 알려주는 것
def search_recipe(end_page: int, search: str = "") -> pd.DataFrame :
    title_list, author_list, views_list = [], [], []

    for i in tqdm(range(1, end_page+1, 1)) :
        url = f"https://www.10000recipe.com/recipe/list.html?order=reco&page={i}"
        res = req.get(url, headers=U_A)
        soup = bs(res.text, "lxml")
    
        title = soup.select("div.common_sp_caption_tit.line2")
        author = soup.select("div.common_sp_caption_rv_name")
        views = soup.select("span.common_sp_caption_buyer")
    
        for i in range(len(title)) :
            title_list.append(title[i].text.strip())
            author_list.append(author[i].text.strip())
            views_list.append(views[i].text.strip()[4:])
    
    recipe_dic = {"레시피명": title_list, "작성자": author_list, "조회수": views_list}
    re_df = pd.DataFrame(recipe_dic, index=range(1,len(title_list)+1))

    # 검색어가 존재할 때(검색어를 입력했을 때)
    if search :
        # copy로 기존 DF를 복사해서 활용(원본 DF가 변형되는 것을 방지)
        filtered_df = re_df[re_df["레시피명"].str.contains(f'{search}')].copy()
    # 검색어가 따로 없을 때
    else :
        filtered_df = re_df.copy()

    filtered_df.reset_index(drop=True, inplace=True)
    filtered_df.index = range(1, len(filtered_df)+1)
    filtered_df.index.name= "No"
    return filtered_df

In [60]:
search_recipe(5)

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.01s/it]

                                     레시피명        작성자    조회수
No
1             굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피        Y큰손     1만
2              들기름 두부구이 두부부침 양념장 레시피 두부반찬        써지니    964
3                              간장버터 새송이구이   요리하는허니레빗   1.4만
4    시금치무침 (시금치데치는 방법 시금치나물요리 나물반찬 반찬레시피)  ariel1007   1.6만
5                     칼칼한 오징어무국 맛있게 끓이는 법     급식실박실장  1,893
..                                    ...        ...    ...
196                ♥[신혼밥상] 10분 반찬! 메추리알조림    행복한윤블리네  46.3만
197                                김치 삼겹살       쿠킹조이  7,544
198        영화속요리 10탄 줄리앤줄리아 속 크림소스 치킨스테이크     포레스트키친  14.5만
199              호두마늘볶음 만드는법- 딸에게# /수미네반찬       노란장미     6만
200          에어프라이어 콘치즈 토스트 만들기!중독성 강하네요!       뽀유TV  24.4만

[200 rows x 3 columns]

In [62]:
search_recipe(5,"김치")

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.02s/it]

                                       레시피명     작성자    조회수
No
1   파프리카 겉절이 레시피 식감 살아 있는 파프리카 김치 만들기 반찬 요리  요리백과사전    809
2                            참기름 스팸김치볶음 레시피   평범한흔남   1.2만
3                            든든한 혼밥 돈까스김치나베  순둥이요리사  14.6만
4                                    김치 삼겹살    쿠킹조이  7,544