### 네이버 블로그 제목 및 내용 수집

In [2]:
import requests as req
import pandas as pd
from bs4 import BeautifulSoup as bs

In [3]:
U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"}

In [4]:
keyword = "현대자동차"
url = f"https://search.naver.com/search.naver?ssc=tab.blog.all&sm=tab_jum&query={keyword}"
res = req.get(url, headers = U_A)
res

In [5]:
soup = bs(res.text, "lxml")
soup

<!DOCTYPE html>

## 블로그 목록 정보 수집
- 타이틀, 블로거명, 게시일

In [18]:
title = soup.select("a > span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1.sds-comps-text-weight-sm")
title

[<span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">2026 <mark>현대자동차</mark> 채용 일정, 연봉과 워라밸은 어떨까?</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">2026 <mark>현대</mark>차 채용 공고(+ <mark>현대자동차</mark> 신입 연봉 실수령액)</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> ICCU 3번째 불량 당첨, 대책이 없어요??</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 빌트인캠 동영상 확인하는 방법</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대</mark>차 주식 배당금 받으려면 언제 사야 하는지 핵심 정리</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 차량 프로젝트 관리, 차량 아키텍처 개발, 차량 재료 개발 직무 완벽정리</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대</mark>차 주가 하루만에 13% 폭등 무슨일? 배당금까지</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">세일즈에 대한 생각, 26년 1월 마감, 제네시스 수지, 고객의 힘, 복리의 마법, 감사하기(<mark>현대</mark>차 김정길 카마스터)</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">“<mark>현대</mark>차 실적 분석 2026: 매출 최고인데 주가는 왜 못 오를까?”</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">주유구와 충전구가 동시에? <mark>현대</mark>차 싼타페에 숨겨진 '두 개의 구멍' 정체</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대 자동차</mark> 그랜드 스타렉스 차박 캠핑카 중고 발견</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">유재석 캠프 <mark>자동차</mark>로 뜬 <mark>현대</mark> 넥쏘 실구매가 및 제원</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">같은 <mark>현대자동차</mark> 블루핸즈인데 평산점에선 괜찮다더니, 정관점 가서 바로 발견된 문제</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">[<mark>현대</mark>차 옵션 가이드] 무조건 넣으세요! 본전 뽑는 '혜자 옵션' TOP5   ( 성남 분당 판교 <mark>현대자동차</mark> 고등대리점 강정식 )</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">"매출은 역대 최대인데, 왜 주가는 흔들리나?" 2026 <mark>현대</mark>차 매출 실적발표 배당금 주가전망 목표가 역습</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대</mark>차 주가 충격 전망 나왔다.. 아틀라스 실체 이렇다는데</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대 자동차</mark> 아이오닉 9 국산 대형 전기차 SUV 6인승 실내와 장단점</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">[<mark>자동차</mark>리뷰] 경차 끝판왕 등장? 2026 <mark>현대자동차</mark> 캐스퍼 완벽 분석</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 주가 분석 및 전망 (소프트웨어, AI로보틱스, AAM)</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 면접 후기 토론 PT 면접 정리</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">"더 싼 <mark>현대</mark>차주식!" 2026 <mark>현대</mark>차우 배당금 배당일 주가전망 목표주가 주가 경보</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 박민우 사장 프로필</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대</mark>차 주가 조정은 매수기회일까? 새만금 9조 투자 및 목표가 전망 (아틀라스 로봇)</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">테슬라와는 다르다! <mark>현대</mark>차 배터리 구독 서비스가 가져올 역대급 변화</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 합격 전략, 지금 준비해야 할 취업준비 자격증은?</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 주가 60만원 깨졌는데, 저가 매수 기회인가?</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">울산북구 수영장 추천｜<mark>현대자동차</mark>문화회관 수영강습 시간표·수강신청 총정리!</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm">'100만 원 간다' <mark>현대</mark>차 주식의 미래 이 분야가 결정한다고 하는데</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대자동차</mark> 전자식 변속 칼럼 장단점 !!</span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-headline1 sds-comps-text-weight-sm"><mark>현대</mark>차2우B를 계속 물타고 있습니다</span>]

In [40]:
title[0].text

'2026 현대자동차 채용 일정, 연봉과 워라밸은 어떨까?'

In [24]:
name = soup.select("div.sds-comps-horizontal-layout.sds-comps-inline-layout.sds-comps-profile-info-title > span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1")
name

[<span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/bangkuseok" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">방구석 어학연수</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/ink2777" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">잇찌</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/bacma" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">백마탄환자</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/mimoa0127" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">나는 차였다(I was car)</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/hbsing501" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">어디서든 빛나는</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/upupo7795" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">파이브커리어컨설팅그룹</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/kh3492" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">길씨</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/smujk" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">현대차 김정길 카마스터 입니다.</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/woofam" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">우팸</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/26sf4mu9tfg" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">자동차를 사랑하는 뉴스</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/bikenmusic" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">쌍둥아빠</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/london005" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">공장이야기</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/loanspecialist" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">레이픽 | 맛집·여행·생활리뷰</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/x0183169694" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">고등대리점 강정식 010.9733.9990</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/nogari77" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">줍줍누나</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/dively_money" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">디블리</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/bikenmusic" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">쌍둥아빠</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/1min1sec_enjoy" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">1min1sec_enjoy</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/stt622" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">여리의 경제소식통</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/jgt337" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">취업달인</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/nogari77" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">줍줍누나</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/gwjun" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">사람과 정책</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/nunoslash77" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">이안</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/dyong4614" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">냥냥이의 엔진</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/rlawkdrn85" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">쿄쿄</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://in.naver.com/imgreat" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">아이엠그레이트</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/akghdrn777" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">풍덩이</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/0713mingyu" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">뉴뉴파파의 경제이야기</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/heosm27" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">현대자동차 송탄제일대리점</span></a></span>,
 <span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1 sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-title-text"><a class="fender-ui_228e3bd1 fender-ui_475445f0" data-heatmap-target="articleSourceJSX_title" href="https://blog.naver.com/jbro0225" nocr="1" target="_blank"><span class="sds-comps-text sds-comps-text-ellipsis sds-comps-text-ellipsis-1">배당으로 은퇴를 준비합니다.</span></a></span>]

In [43]:
#name[0].text
for i in name:
    print(i.text)

방구석 어학연수
잇찌
백마탄환자
나는 차였다(I was car)
어디서든 빛나는
파이브커리어컨설팅그룹
길씨
현대차 김정길 카마스터 입니다.
우팸
자동차를 사랑하는 뉴스
쌍둥아빠
공장이야기
레이픽 | 맛집·여행·생활리뷰
고등대리점 강정식 010.9733.9990
줍줍누나
디블리
쌍둥아빠
1min1sec_enjoy
여리의 경제소식통
취업달인
줍줍누나
사람과 정책
이안
냥냥이의 엔진
쿄쿄
아이엠그레이트
풍덩이
뉴뉴파파의 경제이야기
현대자동차 송탄제일대리점
배당으로 은퇴를 준비합니다.

In [33]:
date = soup.select("div.sds-comps-horizontal-layout.sds-comps-inline-layout.sds-comps-profile-info-subtexts > span.sds-comps-text.sds-comps-text-type-body2.sds-comps-text-weight-sm.sds-comps-profile-info-subtext")
date

[<span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.02.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.03.21.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2025.12.11.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.01.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.03.26.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.03.13.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.08.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.02.01.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.05.02.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.04.23.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2025.12.23.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">4주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">3주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.04.01.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.06.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.03.31.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">4주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">4주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">3주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.15.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.03.05.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.05.03.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.02.14.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">3주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.01.07.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">2026.04.28.</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">4주 전</span>,
 <span class="sds-comps-text sds-comps-text-type-body2 sds-comps-text-weight-sm sds-comps-profile-info-subtext">4주 전</span>]

In [42]:
date[0].text

'2026.01.02.'

In [34]:
len(date)

30

In [38]:
title_list, name_list, date_list = [],[],[]

for i in range(len(title)):
    title_list.append(title[i].text.strip())
    name_list.append(name[i].text.strip())
    date_list.append(date[i].text.strip())

In [39]:
blog_df = pd.DataFrame({"타이틀": title_list,
                       "블로거명":name_list,
                       "게시일":date_list},
                      index = range(1,31))

blog_df.index.name = "No"
blog_df

,타이틀,블로거명,게시일
No,,,
1,"2026 현대자동차 채용 일정, 연봉과 워라밸은 어떨까?",방구석 어학연수,2026.01.02.
2,2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액),잇찌,2026.03.21.
3,"현대자동차 ICCU 3번째 불량 당첨, 대책이 없어요??",백마탄환자,2025.12.11.
4,현대자동차 빌트인캠 동영상 확인하는 방법,나는 차였다(I was car),2026.01.01.
5,현대차 주식 배당금 받으려면 언제 사야 하는지 핵심 정리,어디서든 빛나는,2026.03.26.
6,"현대자동차 차량 프로젝트 관리, 차량 아키텍처 개발, 차량 재료 개발 직무 완벽정리",파이브커리어컨설팅그룹,2026.03.13.
7,현대차 주가 하루만에 13% 폭등 무슨일? 배당금까지,길씨,2026.01.08.
8,"세일즈에 대한 생각, 26년 1월 마감, 제네시스 수지, 고객의 힘, 복리의 마법,...",현대차 김정길 카마스터 입니다.,2026.02.01.
9,“현대차 실적 분석 2026: 매출 최고인데 주가는 왜 못 오를까?”,우팸,2026.05.02.
10,주유구와 충전구가 동시에? 현대차 싼타페에 숨겨진 '두 개의 구멍' 정체,자동차를 사랑하는 뉴스,2026.04.23.
11,현대 자동차 그랜드 스타렉스 차박 캠핑카 중고 발견,쌍둥아빠,2025.12.23.
12,유재석 캠프 자동차로 뜬 현대 넥쏘 실구매가 및 제원,공장이야기,2주 전
13,"같은 현대자동차 블루핸즈인데 평산점에선 괜찮다더니, 정관점 가서 바로 발견된 문제",레이픽 | 맛집·여행·생활리뷰,4주 전
14,[현대차 옵션 가이드] 무조건 넣으세요! 본전 뽑는 '혜자 옵션' TOP5 ( ...,고등대리점 강정식 010.9733.9990,2주 전
15,"""매출은 역대 최대인데, 왜 주가는 흔들리나?"" 2026 현대차 매출 실적발표 배당...",줍줍누나,3주 전
16,현대차 주가 충격 전망 나왔다.. 아틀라스 실체 이렇다는데,디블리,2026.04.01.
17,현대 자동차 아이오닉 9 국산 대형 전기차 SUV 6인승 실내와 장단점,쌍둥아빠,2026.01.06.
18,[자동차리뷰] 경차 끝판왕 등장? 2026 현대자동차 캐스퍼 완벽 분석,1min1sec_enjoy,2026.03.31.
19,"현대자동차 주가 분석 및 전망 (소프트웨어, AI로보틱스, AAM)",여리의 경제소식통,4주 전
20,현대자동차 면접 후기 토론 PT 면접 정리,취업달인,4주 전
21,"""더 싼 현대차주식!"" 2026 현대차우 배당금 배당일 주가전망 목표주가 주가 경보",줍줍누나,3주 전
22,현대자동차 박민우 사장 프로필,사람과 정책,2026.01.15.
23,현대차 주가 조정은 매수기회일까? 새만금 9조 투자 및 목표가 전망 (아틀라스 로봇),이안,2026.03.05.
24,테슬라와는 다르다! 현대차 배터리 구독 서비스가 가져올 역대급 변화,냥냥이의 엔진,2026.05.03.
25,"현대자동차 합격 전략, 지금 준비해야 할 취업준비 자격증은?",쿄쿄,2026.02.14.
26,"현대자동차 주가 60만원 깨졌는데, 저가 매수 기회인가?",아이엠그레이트,3주 전
27,울산북구 수영장 추천｜현대자동차문화회관 수영강습 시간표·수강신청 총정리!,풍덩이,2026.01.07.
28,'100만 원 간다' 현대차 주식의 미래 이 분야가 결정한다고 하는데,뉴뉴파파의 경제이야기,2026.04.28.
29,현대자동차 전자식 변속 칼럼 장단점 !!,현대자동차 송탄제일대리점,4주 전
30,현대차2우B를 계속 물타고 있습니다,배당으로 은퇴를 준비합니다.,4주 전

### 함수를 활용한 코드 통합
- 매개변수는 검색 키워드가 들어가도록 하고 return은 DF으로 반환 받도록 설정

In [62]:
def blog_def(keyword: str) -> pd.DataFrame:
    title_list, name_list, date_list = [],[],[]

    url = f"https://search.naver.com/search.naver?ssc=tab.blog.all&sm=tab_jum&query={keyword}"
    U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"}
    res = req.get(url, headers = U_A)
    soup = bs(res.text, "lxml")

    title = soup.select("a > span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1.sds-comps-text-weight-sm")
    name = soup.select("div.sds-comps-horizontal-layout.sds-comps-inline-layout.sds-comps-profile-info-title > span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1")
    date = soup.select("div.sds-comps-horizontal-layout.sds-comps-inline-layout.sds-comps-profile-info-subtexts > span.sds-comps-text.sds-comps-text-type-body2.sds-comps-text-weight-sm.sds-comps-profile-info-subtext")

    for i in range(len(title)):
        title_list.append(title[i].text.strip())
        name_list.append(name[i].text.strip())
        date_list.append(date[i].text.strip())

            
    blog_df = pd.DataFrame({"타이틀": title_list,
                       "블로거명":name_list,
                       "게시일":date_list},
                      index = range(1,31))
    blog_df.index.name = "No"
        
    return blog_df

In [63]:
blog_def("삼성전자")

,타이틀,블로거명,게시일
No,,,
1,삼성전자 배당금 5월29일 통장 꽂히는 진짜 액수,주식하는남자쿠니네,3주 전
2,"성과급만 6,000만 원 추가? 삼성전자 노조 요구안 실현 시 벌어지는 일(정당한 ...",수락,4주 전
3,삼성전자 특별배당금 받았는데... 추가 매수는 못 하겠어요,"낭만생활백서(주부 재테크,육아)",2026.04.17.
4,"""특별배당까지 터졌다!"" 2026 삼성전자 배당금 지급일 기준일 특별배당금 1만원전...",줍줍누나,3주 전
5,"삼성전자 상승할 때마다 뛰는 삼성생명, 이유 있었다",우팸,3주 전
6,"삼성전자 주가, 코스피 지수 5% 폭락하고 있지만 마음이 편하고 계좌는 수익나는 이유",자꾸남,2026.03.03.
7,"삼성전자 SK하이닉스 레버리지 ETF, 매수 전 교육부터 막히는 이유",청년개미,2주 전
8,“삼성전자 노조 결국 폭발했다…현재 협상 상황”,“차와 함께하는 모든 순간”,4주 전
9,삼성전자 성과급 6억 폭탄에 잠 못 드는 반도체 업계 현황,주식하는남자쿠니네,3주 전
10,삼성전자 SK하이닉스 주가 성과금 실제 받은 후기,버린돌 인생 공략집,2026.04.08.
11,"삼성전자 주가 311% 수익률이여 안녕, 가슴 아픈 삼성전자 매도 후기",느려도괜찮아,3주 전
12,삼성전자 최승호 노조위원장 프로필 나이 결혼 가족 자녀 아내 학력 고향 부서 직급,STORY,3주 전
13,"삼성전자 제치고 ""1000% 폭등"" 한 역대급 'AI 대장주'의 정체",에이투지,2주 전
14,삼성전자 총파업 초읽기. 노조 이송이 부위원장 “회사를 없애버리자” 발언까지 터지며...,스페셜타임스,3주 전
15,긴급조정권 뜻 | 삼성전자 파업 해결할 수 있을까?,대구 공장 임대·매매,3주 전
16,"""애플·TSMC와 비교하면"" 삼성전자 실제 위치는 의외로 이렇습니다",효선생 “경제노트”,2026.04.08.
17,삼성전자 이송이 부위원장 프로필 나이 학력 광주공고 관심 폭발,세상 모든 핫이슈,3주 전
18,연봉 1억인데 성과급 6억 vs 600만원… 삼성전자 2개 부문 8개 사업부의 냉혹...,슘페터,2주 전
19,삼성전자 파업 총정리 (현재 상황 + 노조 요구 + 피해 규모까지 한 번에 정리),쏘나타,2026.04.24.
20,"""삼성전자는 없애버러야"" 이송이 부위원장, 프로필 나이 고향 학력, 노동조합",낭만뉴스,3주 전
21,"삼성전자 주식 10만주 있는데 ""아무 힘이 없다""는 대주주의 한숨",날아라 일룡아,2주 전
22,삼성전자 주가 충격 전망 나왔다... 40만 전자 간다더니,TAX 기사,2026.04.09.
23,1억 넣고 잊었더니 집 샀다 소유가 밝힌 삼성전자·SK하이닉스 10년의 결과,맘강윰,6일 전
24,"""다 오른 줄 알았죠?"" 삼성전자 SK하이닉스 주가 아직도 저평가라는데",언젠간 부자,2주 전
25,삼성전자 반도체 복호두 사건 그리고 심각한 내부 상황,"나티, 세상이 궁금해",3주 전
26,10퍼센트 확률인데 진짜 삼전 주주 됐음 키움증권 삼성전자 주주 이벤트 당첨 후기 ...,라니라이프,4주 전
27,"[필독] 삼성전자 총파업 D-6, 최승호 위원장 프로필과 반도체 셧다운 위기의 진실",경제거북이,3주 전
28,삼성전자·SK하이닉스 레버리지 ETF란 무엇인가? 출시일·장점·리스크 총정리,후미후미,2주 전
29,"삼성전자 성과급 인당 4억 가능할까, SK하이닉스와 비교해봤습니다",Back 2 MD,2026.04.08.
30,삼성전자 서비스센터 전화번호 및 예약 방법 정리,N잡러 갱동의 사업 발자국,2026.02.19.

## 블로그 내부 본문 데이터 수집

In [64]:
url = "https://blog.naver.com/PostView.naver?blogId=ink2777&logNo=224224554325&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fsearch.naver.com%2Fsearch.naver%3Fssc%3Dtab.blog.all%26sm%3Dtab_jum%26query%3D%25ED%2598%2584%25EB%258C%2580%25EC%259E%2590%25EB%258F%2599%25EC%25B0%25A8&trackingCode=tab_blg&directAccess=false"
res_blog = req.get(url, headers = U_A)
res_blog

In [65]:
soup = bs(res_blog.text, "lxml")
soup

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ko">
<head>
<meta content="no-cache" http-equiv="Pragma"/>
<meta content="-1" http-equiv="Expires"/>
<meta content="always" name="referrer"/>
<!--[if ie]>
<style type="text/css">
html {overflow: scroll; overflow-x: auto;}
</style>
<![endif]-->
<link charset="UTF-8" href="https://ssl.pstatic.net/t.static.blog/mylog/versioning/LayoutTopCommon-291396673_https.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/music/player-d3fc09e_https.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static/blog/icon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<meta content="2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액)" property="og:title"/>
<meta content="https://blogthumb.pstatic.net/MjAyNjAzMjFfMjkg/MDAxNzc0MDY1ODc1OTgz.EoL8BPlxtSrx06EsAYjCD5WuUc6-j0hWBCP5VOV_CsQg.KXmWHM_fGoGBwJi07nh4Gp94FmtqJNG5wPnSKuChLnIg.PNG/%C0%CC%B9%CC%C1%F6_21.png?type=w2" property="og:image"/>
<meta content="2026 현대차 채용 공고 (+ 현대자동차 신입 연봉 실수령액) 안녕하세요. 취업 정보 알려드리는 잇찌입니다...." property="og:description"/>
<meta content="https://blog.naver.com/ink2777/224224554325" property="og:url"/>
<meta content="blog" property="me:feed:serviceId"/>
<style type="text/css">
/*<![CDATA[*/


body {background-color:rgb(255, 255, 255);background-image:none;}
#head-skin {background-image:none;}


#whole-border {border-width:0px;border-color:rgb(0, 0, 0);border-style:solid;background:transparent;}
#whole-head {height:0;background:transparent;}
#whole-body {padding:0 8px;background:transparent;}
#whole-footer {height:0;background:transparent;}


#wrapper .side-border {border-width:0px;border-style:solid;border-color:rgb(0, 0, 0);border:0;}
#wrapper .side-head {height:8px;background:transparent;}
#wrapper .side-body {padding:0;background:transparent;}
#wrapper .side-footer {height:8px;background:transparent;}


#wrapper .cm-col1 {color:rgb(85, 85, 85);}
#wrapper .cm-arw {background:rgb(85, 85, 85);}
#wrapper div.line {border-top-color:rgb(85, 85, 85);}
#wrapper .cm-border {border-width:0;border-style:solid;border-color:rgb(0, 0, 0);}
#wrapper .cm-head {height:30px;background:url(https://ssl.pstatic.net/static/blog/skin/90/cm-head.png);}
#wrapper .cm-body {background:transparent;}
#wrapper .cm-footer {height:0;background:transparent;}
#wrapper .cm-icol {color:rgb(246, 123, 0);}
#wrapper h3 {margin-left:14px;bottom:7px;}
#wrapper .cmore {bottom:7px;}
#blog-category .listimage {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_arw.gif);}
#wrapper .buddyup {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_up.gif);}
#wrapper .buddydw {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_down.gif);}
#blog-category .f_icoclosed {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_closed_l.gif) !important;}
#blog-category .f_icoopen {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_open_l.gif) !important;}
#blog-category ul li.depth2 {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_depth2_l.gif) !important;}

* html #wrapper .cm-head { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/90/cm-head.png,sizingMethod=crop); }

#blog-gnb .link {color:rgb(153, 153, 153);}
#blog-gnb .gnb_name {color:rgb(153, 153, 153);}
#blog-gnb .bar {background:rgb(153, 153, 153);}
#blog-gnb .btn_blog_login {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png) no-repeat 0 0;}
#blog-gnb .gnb_icon {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png) no-repeat 0 0 !important;}
#blog-gnb .go-down {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png);}
#blog-gnb .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png) no-repeat 100% 50% !important;}
#blog-gnb .go-up {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png);}
#blog-gnb .gnb_lyr_opened .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png) no-repeat 100% 50% !important;}

* html #blog-gnb .btn_blog_login { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png,sizingMethod=crop); }
* html #blog-gnb .gnb_icon { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png,sizingMethod=crop); }
* html #blog-gnb .go-down { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }
* html #blog-gnb .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }
* html #blog-gnb .go-up { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }
* html #blog-gnb .gnb_lyr_opened .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }

#foldset .go-left {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png)}
#foldset .go-right {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png)}

* html #foldset .go-left { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png,sizingMethod=crop); }
* html #foldset .go-right { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png,sizingMethod=crop); }

#body {width:982px; margin:0 auto; padding:0;}
body, #head-skin, #bottom-skin {background-position:50% 0;}
#wrapper {width:966px; padding-top:8px;}
#content-area {width:966px;}



.itemfont, a.itemfont:link, a.itemfont:visited, a.itemfont:hover, a.itemfont:active {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}
a.itemTagfont:link, a.itemTagfont:visited {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}
a.itemTagfont:hover , a.itemTagfont:active {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial; color:#418F21;}
.itemSubjectfont   {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}
#post-area .post_adpost .itemSubjectfont {font-size:10pt !important;font-family:돋움, 굴림, seoul, verdana, arial;}


#blog-mapviewwidget {}
#blog-rss {height:27px;background-image:url(https://blogimgs.pstatic.net/nblog/skins/rss/0104_image_1.gif);}
#blog-rss .rss1 {width:42px;height:14px;margin:8px 0 0 30px;}
#blog-rss .rss2 {width:42px;height:14px;margin:8px 0 0 72px;}
#blog-rss .rss3 {width:48px;height:14px;margin:8px 0 0 114px;}

#blog-title {height:357px;background:url(https://blogfiles.pstatic.net/MjAyMDEwMDdfMjgx/MDAxNjAyMDAzNjMzNzI3.AwrIovwR86oo04Z_biUergBVkDuegYYp6FWhUdSQac0g.ZGAHAm5fivkrk924tpeXy6_-qvZE8apmMq1E07ZYd3Ag.PNG.ink2777/title?type=w3000);}
#blogTitleText {vertical-align:middle;text-align:center;}
#blogTitleName {display:none;color:rgb(51, 51, 51);font-family:sans-serif;font-size:20px;}

#blog-menu .border {height:70px;border-width:0px;border-color:rgb(0, 0, 0);border-style:dotted;}
#blog-menu table {height:70px;background:url(https://ssl.pstatic.net/static/blog/skin/90/blog-menu.png);}
#blog-menu .on {color:rgb(246, 123, 0);}
#blog-menu .off {color:rgb(51, 51, 51);}
#blog-menu .bar {background:rgb(51, 51, 51);}

* html #blog-menu table { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/90/blog-menu.png,sizingMethod=crop); }
#blog-profile .border {border-width:0px;border-style:solid;border-color:rgb(255, 255, 255);}
#blog-profile .bg-head {height:5px;background:url(https://blogimgs.pstatic.net/nblog/skins/profile/0101_head_1.gif);}
#blog-profile .bg-body {padding:0px;background:url(https://blogimgs.pstatic.net/nblog/skins/profile/0101_body_1.gif);}
#blog-profile .bg-footer {height:5px;background:url(https://blogimgs.pstatic.net/nblog/skins/profile/0101_footer_1.gif);}
#blog-profile .col {color:rgb(51, 51, 51);}
#blog-profile .icon {background-image:url(https://blogimgs.pstatic.net/nblog/skins/profile/0101_icon.gif);}
#blog-profile .image {display:block;}
#blog-profile .image img {width:161px;}
#blog-profile .align {text-align:left;}


#blog-buddyconnect {}


#post-area .post {border-width:0px;border-color:rgb(235, 235, 235);border-style:none;}
#post-area .post-back {background:transparent;}
#post-area .pcol1 {color:rgb(51, 51, 51);font-size:14px;}
#post-area .pcol2 {color:rgb(51, 51, 51);}
#post-area .pcol2b {background:rgb(51, 51, 51);}
#post-area .cline {border-bottom-color:rgb(51, 51, 51);}
#post-area .pcol3 {color:rgb(246, 123, 0);}
#post-area .dline {border-top-width:1px;border-top-color:rgb(51, 51, 51);border-top-style:dotted;}
#post-area .htl {width:15px;height:15px;background:transparent;}
#post-area .htc {height:15px;background:transparent;}
#post-area .htr {width:15px;height:15px;background:transparent;}
#post-area .ftl {width:15px;height:15px;background:transparent;}
#post-area .ftc {height:15px;background:transparent;}
#post-area .ftr {width:15px;height:15px;background:transparent;}
#post-area .bcl {width:15px;background:transparent;}
#post-area .bcc {background:transparent;}
#post-area .bcr {width:15px;background:transparent;}
#post-area .ico1 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_up.gif);}
#post-area .ico2 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_down.gif);}
#post-area .ico3 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico2.gif);}
#post-area .comment {background:rgb(253, 250, 207);}
#post-area .btn {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png);}
#post-area .btn-sympathy {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_sympathy_03.gif);}
#post-area .btn_r {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_reply_default.gif);}

* html #post-area .btn { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png,sizingMethod=crop); }
.post-back {background:transparent;}
.pcol1 {color:rgb(51, 51, 51);font-size:14px;}
.pcol2 {color:rgb(51, 51, 51);}
.pcol2b {background:rgb(51, 51, 51);}
.pcol3 {color:rgb(246, 123, 0);}
.bcc {background:transparent;}
#post-area .sline {border-bottom-color:rgb(51, 51, 51);}




/*]]>*/
</style>
<script src="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/js/global/RemoveSubDomain-12d2f16_https.js" type="text/javascript"></script>
<script>






var mylogURL = 'https://blog.naver.com';
var adminURL = 'https://admin.blog.naver.com';
var noteURL = 'https://note.naver.com';
var itemURL = 'https://item.naver.com';
var cafeURL = 'https://cafe.naver.com';
var profileURL = 'https://blog.naver.com';
var blogURL = 'https://blog.naver.com';
var blogURLHttp = 'https://blog.naver.com';
var prologueURL = 'https://blog.naver.com';
var sectionURL = 'https://section.blog.naver.com';
var memologURL = 'https://blog.naver.com';
var lifeURL = 'https://lifelog.blog.naver.com';
var uploadURL = 'https://upload.blog.naver.com';
var imageURL = 'https://blogimgs.pstatic.net';
var attachURL = 'https://blogfiles.pstatic.net';
var thumbnailURL = 'https://blogthumb.pstatic.net';
var nonCachedThumbnailURL = 'https://blogthumb.pstatic.net';
var filetransURL = 'http://filetrans.blog.naver.com';
var item2_bridgeURL = 'http://bridge.item2.naver.com';
var idURL = 'http://nid.naver.com';
var idURLSecret = 'https://nid.naver.com';
var mapviewURL = 'http://mapview.naver.com';
var exifURL = 'https://exif-blog.ssl.phinf.net';
var viewerImageUrl = imageURL + "/blog20/blog/layout_photo/viewer/";
var domainURL = "";
var greenReviewCampaignURL = 'http://campaign.naver.com';
var writeURL = 'https://blog.naver.com';
var spiURL = 'https://ssl.pstatic.net/spi';
var blogProfileThumbnailUrl='https://blogpfthumb-phinf.pstatic.net';
var naverCommentStaticURL = 'https://ssl.pstatic.net/static.cbox';
var naverCommentApiURL = 'https://apis.naver.com/commentBox/cbox9';
var naverCommentApiProxyURL = 'https://apis.naver.com/commentBox/blogid';
var itemImagesURL = 'https://blogimgs.pstatic.net/item';

var sCssUrlForPhotoLayer = 'https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/storyphoto_original_viewer-adf5d27_https.css';
var commonStatDailyURL = 'https://blog.stat.naver.com';
var baUrl = 'https://scv-blog.io.naver.com/jackpotlog/v1/logs';





var blogId = 'ink2777' || 'ink2777';
var userId = '';
var userNo = '';
var userNaverId = '';
var baUserKey = '__UNKNOWN__';
var userIdNo = "";



var isWritingBlocked = false;
var isWritingBlockedBySpamIP = false;
var isWritingBlockedBySpamIPManually = false;
var isLoggedIn = false;
var isShortestContentAreaWidth = false;

var blogOwner = false;

var blogNo = '59281546';
var nickName = '잇찌';
var isInitializingBlog = false;
var rightClickOpenYn = true;
var isMylogBlocked = false;
var isBlogBlock = false;
var blockOrWriteBlock = false;
var autoSourcingYn = true;


var isMemolog = false;
var isMemologList = false;
var isPrologue = false;


var isBlogMe = false;

var isUsingUrl = false;


var isRequestFromIPad = false;


var isOverIOS5_0Version = false;
var isOverAndroidJellybeanVersion = false;
var isCommingNaverApp = false;
var isUsingNaverKitkatEngine = false;
var isAndroidKitkatVersion = false;

var defaultSmartEditorVersion = 2;

var adContentLocation = "0";
var gAdBucket = "";






var readOnlyStatus = false;
var readOnlyStatusAll = false;
var readOnlyLinkErrorMsg = '죄송합니다. 블로그 서비스 점검 중입니다. \n점검 시간 동안은 기능 이용이 제한됩니다. \n자세한 내용은 블로그 홈 공지사항을 참고해주세요.';
var readOnlyCommentMsg = '12월 17일(월) 오전 0시~8시 서비스 점검으로 댓글 작성이 제한됩니다. \n더욱 안정적인 서비스로 찾아뵙겠습니다. 불편하시더라도 조금만 기다려주세요.';
var sIsTagReadOnly = '';
var sTagSorryText = '죄송합니다. 태그 서비스 점검 중입니다.\n점검 시간 동안은 일부 서비스 이용이 제한됩니다.\n자세한 내용은 공지사항을 참조하세요.';
var blogQuickPostingUseType = "NOT_SET";




var isCommentReadOnly = false;
var sCommentReadOnlyBlockSubmit = '죄송합니다. 블로그 댓글, 답글 서비스 점검 중에는 이용이 제한됩니다.';
var sCommentReadOnlyWriteMsg = '서비스 점검으로 댓글 작성이 제한됩니다.\n더욱 안정적인 서비스로 찾아뵙겠습니다. 불편하시더라도 조금만 기다려주세요.';








var isJeagleDebug = false;





var skinId = "0";
var skinType = "C";

var isEnglish = "false";

var areaCode = "11B10101";
var weatherType = "0";

var currencySign = "ALL";

var listNumVisitor = '5';
var isVisitorOpen = true;
var isCategoryOpen = true;
var writingMaterialListType = '1'
var previewCalType = '';



var oExternalWidget = [{'teminationMessageHtml':'','blockYn':false,'reversedWidgetCode':'E3%pF2%C3%E3%uF2%C3%E3%aF2%C3%B8%08%2E%E3%22%fles_22%D3%tegrat+22%7772kniF2%moc.revan.niF2%F2%A3%ptth22%D3%ferh+22%knalb_22%D3%tegrat+aC3%E3%uC3%E3%F2%+22%302935588645318851_EQ22%D3%dieqs+22%B3%xp371A3%thgiehr+B3%xp071A3%htdiwr+B3%htob+A3%raelc+B3%92%0+C2%0+C2%082%bgr+A3%roloc-redrob+B3%xp371+A3%thgieh+B3%xp071+A3%htdiw22%D3%elyts+22%22%D3%ngila+22%D752%B752%22%D3%eulavnosj+22%gnp.tegdiw22%D3%eltit+22%eurt22%D3%eqgmi+22%37122%D3%thgiehr+22%07122%D3%htdiwr+22%37122%D3%thgieh+22%07122%D3%htdiw+22%otohp22%D3%epytbus_s+22%tnemhcatta22%D3%epyt_s+22%tcejbo_es__22%D3%ssalc+22%gnp.tegdiwF2%7772kni.GNP.gQVnGBreLDfiXDQCSj4TqXKBWg_j0GhXzjGC_1rSiY5R.gokHeb_Pc9MczoC9R1OcBPDFkSKaBk5RIinXtxejUlIU.3gzM4YDN1MTM4gTNxADMF2%5QTMfljM0ADMyAjMF2%ten.citatsp.selifgolbF2%F2%A3%sptth22%D3%crs+22%918239897645318851_tcejbo_es22%D3%di+gmiC3%E3%pC3%','serviceTerminated':false,'seq':4}];


var calType = "";


var curLog = 'https://blog.naver.com';
var playerType = '0';
var playerDesign = '1';


var isCommentOpen = false;
var listNumComment = 5;


var isBuddyOpen = false;



var userSelectMenu = '';


var visitorgpData = '2';
var vigitorSetUrl = '';
var vigitorPropUrl = '/versioning//common/swf/Widget/visitorGP/VisitorGP-50a2c61.xml';
var visitorgp_vars = {
	setUrl    : vigitorSetUrl,
	req_url   : '/NVisitorgp4Ajax.naver?blogId=' + blogId,
	prop_url  : vigitorPropUrl,
	graphType : visitorgpData,
	flashvars : function(){
		return "req_url=" + this.req_url +"&prop_url=" + this.prop_url +"&graphType=" + this.graphType;
	},
	height    : 121
};



var watchData = '';
var watch_design = {
	name    : watchData.split('|')[0],
	font    : watchData.split('|')[1],
	color   : watchData.split('|')[2],
	bgcolor : watchData.split('|')[3]
}
var watch_vars = {
	blogId : blogId,
	skinType : skinType,
	skinId : skinId
}


var serviceId = '';
var naverId = '';
var happyBeanApiURL = '';
var reqparam = '';
var HAPPYBEAN_API_URL = "";
var HAPPYBEAN_FUND_URL = "";
//var HAPPYBEAN_MY_URL   = "";
var HAPPYBEAN_DONATION_URL = "";




var selectCategoryNo = "62";


var aNonWidget = ['rss', 'powered','adpost','buddyconnect','greenreview'];
<!-- var aWidget = ['gnb', 'externalwidget','music'];  -->
var aWidget = [];


aWidget.push('mapview');

aWidget.push('rss');

aWidget.push('visitorgp');

aWidget.push('title');

aWidget.push('menu');

aWidget.push('profile');

aWidget.push('category');

aWidget.push('buddyconnect');

aWidget.push('4');

aWidget.push('search');

aWidget.push('content');

aWidget.push('gnb');

aWidget.push('externalwidget');

var bIsRemocon = false;
var bIsPreview = document.location.href.indexOf("PostPreview.nhn") > -1 || document.location.href.indexOf("MemologMemoPreview.nhn") > -1;

var isTopLayoutEmpty = false;

var openSideType = "1";
var foldSideType = "2";

var g_ContentShareObject = {
	adPostPreview : false,
	adPostPreviewSide : false,
	adPostPreviewContent : false,
	adPostAlign : "",
	adPostCount : ""
};

var blogDomainUrl = "";
var sAjaxFlashUrl = '/versioning//common/lib/ajax.flash/ajax-885363e.swf';
var isHappyBeanLeverage = false;


var doc = document.documentElement;
doc.setAttribute('data-useragent',navigator.userAgent);
var gbIsNotOpenBlogUser = "false" === "true";
var gbIsNPayAccepted = "false";
var gbIsPayAcceptedOrBefore = "false";
</script>
<script charset="utf-8" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/Jindo152-313837964_https.js" type="text/javascript"></script>
<script charset="UTF-8" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/LayoutTopCommon-865522784_https.js" type="text/javascript"></script>
<script charset="utf-8" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/JindoComponent-190469086_https.js" type="text/javascript"></script>
<meta content="index,follow" name="robots"/>
<meta content="no" http-equiv="imagetoolbar"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="article" property="og:type"/>
<meta content="네이버 블로그 | 잇찌와 업글인간" property="og:article:author"/>
<meta content="네이버 블로그 | 잇찌와 업글인간" property="og:site_name"/>
<meta content="잇찌" property="naverblog:nickname"/>
<meta content="https://blogpfthumb-phinf.pstatic.net/MjAyNDEwMzBfMjQ1/MDAxNzMwMjMzMjkyMDI1.azURs1Ki-r9lGYN8YSLMDj4_NukxWKvGCyKjAIvtZC0g.FETf-hDEmn4PFvY0v_KZ1vuJzO4t8INbJK8ve_eJ3uog.JPEG/6b45759cecb348598c0ad72f3fdaf15e.jpeg/6b45759cecb348598c0ad72f3fdaf15e.jpeg" property="naverblog:profile_image"/>
<meta content='"2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액)":https://blog.naver.com/ink2777/224224554325' property="me2:post_body"/>
<meta content="네이버블로그 잇찌와 업글인간" property="me2:post_tag"/>
<meta content="blog" property="me:feed:serviceId"/>
<title>2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액) : 네이버 블로그</title>

In [87]:
# text = soup.select("div.se-module.se-module-text > p.se-text-paragraph.se-text-paragraph-align-")
# text[-2].text

text = soup.select_one("div.se-main-container")

In [89]:
for i in text:
    print(i.text.strip())

2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액)

​​



​​안녕하세요. 취업 정보 알려드리는 잇찌입니다.​현차에서 2026년 3월 20일부터 4월 3일까지 2주간 공식 채용 홈페이지에서 전 부문이 참가하는 대규모 채용을 실시하고 있습니다.​이번 채용은 신입, 경력직으로 규모를 달리하여 모집하고 있으며, 부문은 총 171개로 연구개발, 생산/제조, 사업/기획, 디자인, IT, 경영지원 등이 있겠습니다.​​

현대자동차 신입 채용 공고



​​모집기간: 3월 20일(금) 9시 ~ 4월 3일(금) 17시까지 ​지원대상은?학사, 석사 학위를 기 취득했거나 2026년 8월 이내 졸업 예정인 자 해외여행에 결격 사유가 없으며, 남성의 경우 병역필 또는 면제자 ​모집 부문: 연구개발, 디자인, 생산, 제조, 사업, 기획, 경영지원, IT ​채용 절차 프로세스는?서류전형 - 인적성검사 - 직무면접 - 종합면접 - 채용검진 - 최종합격 및 입사 *공고에 따라서 자격요건 및 프로세스는 상이할 수 있습니다.​​

상세 직무 및 근무지





​​현대차에서는 열정과 성장 잠재력을 가진 미래형 인재를 선발해 모빌리티 혁신을 만들어 가겠다는 목표를 가지고 있는데요.​2025년 채용에 이어서 2026년도 장애인 신입 채용을 동시에 운영해서 균형이 잡힌 현대자동차 만의 채용 기조를 이어가겠다는 방침입니다.주요 근무지는 울산, 아산, 남양, 판교, 의왕, 경기, 마북, 전주 등이 있겠습니다.​​



​​

현대차 신입 연봉 정리(초봉·성과급·실수령액)

현대자동차 취업을 고려하는 분들이라면 가장 궁금한 것 중 하나가 바로 신입 연봉 수준일 텐데요.최신 데이터를 바탕으로 보면, 현대차는 여전히 국내 최상위 수준의 연봉을 유지하고 있습니다.​특히 성과급 비중이 높은 구조라 '실제 받는 돈(영끌)' 기준으로는 체감 연봉이 훨씬 높다는 점이 특징입니다.​​



​​

현대차 신입 연봉 (2025 기준)

기본 계약 연봉

약 5,000만 원 ~ 5,300만 원 수준 대기업 평균과 비교해도 높은 편이지만, 현대차는 여기서 끝이 아닙니다.​​

실제 연봉 (영끌 기준)

약 8,000만 원 ~ 9,400만 원 수준 즉, 성과급 + 상여금 포함 시 1년 차에도 9천 가까이 가능​​



​​

왜 이렇게 많이 받을까?

현대자동차 연봉이 높은 이유는 구조에 있습니다.​1)성과급 비중이 매우 큼 - PI(성과금), PS(이익배분금) 지급- 경영 실적이 좋을수록 크게 상승2025년은 역대급 실적으로 인해 성과급 최대 수준 반영 ​2)다양한 추가 수당- 품질격려금- 명절 상여금- 복지 포인트- 주식 지급(약 30주)단순 월급 외에도 "숨은 돈"이 많음 ​​



​​

직무별 연봉 차이

현대차는 직무별 실수령액 차이도 뚜렷한 편인데요.​사무직 / 연구직기본 연봉 + 성과급 중심 초봉 영끌 약 9천 전후 ​생산직 기본급 + 각종 수당 (야간/특근 등)초봉 약 7,000만 원대생산직도 국내 최상위 수준​​



​​평균 연봉 수준 2025년 평균 연봉 : 약 1억 3,100만 원 전년 대비 5.7% 상승 입사 후 5년 내 1억 돌파 가능성 높음​​핵심 요약하면?계약 연봉: 5,000만 원 초반 신입 실수령(영끌): 8,000만 원 ~ 9,400만 원 평균 연봉: 1억 3천 수준 특징: 성과급 비중 매우 큼​​즉, "현대차는 기본급보다 성과급이 진짜 연봉을 결정합니다."​​현대자동차는 단순히 초봉이 높은 기업이 아니라, 성과에 따라 보상이 크게 달라지는 고성과형 연봉 구조를 가진 회사입니다.​그래서 취업을 준비할 때는 연봉 총액(영끌) 기준으로 보는 게 중요합니다.​앞으로도 실적이 유지된다면, 신입 기준에서도 국내 최상위 연봉 수준은 이어질 전망입니다.연차가 쌓이면 억대 연봉도 충분히 기대할 수 있는 것이죠.​

In [94]:
# 개행 없애기
text.text.replace("\n","") # replace(바꾸고 싶은 것, 변경할 것)

'2026 현대차 채용 공고(+ 현대자동차 신입 연봉 실수령액)\u200b\u200b \u200b\u200b안녕하세요. 취업 정보 알려드리는 잇찌입니다.\u200b현차에서 2026년 3월 20일부터 4월 3일까지 2주간 공식 채용 홈페이지에서 전 부문이 참가하는 대규모 채용을 실시하고 있습니다.\u200b이번 채용은 신입, 경력직으로 규모를 달리하여 모집하고 있으며, 부문은 총 171개로 연구개발, 생산/제조, 사업/기획, 디자인, IT, 경영지원 등이 있겠습니다.\u200b\u200b 현대자동차 신입 채용 공고\u200b\u200b모집기간: 3월 20일(금) 9시 ~ 4월 3일(금) 17시까지 \u200b지원대상은?학사, 석사 학위를 기 취득했거나 2026년 8월 이내 졸업 예정인 자 해외여행에 결격 사유가 없으며, 남성의 경우 병역필 또는 면제자 \u200b모집 부문: 연구개발, 디자인, 생산, 제조, 사업, 기획, 경영지원, IT \u200b채용 절차 프로세스는?서류전형 - 인적성검사 - 직무면접 - 종합면접 - 채용검진 - 최종합격 및 입사 *공고에 따라서 자격요건 및 프로세스는 상이할 수 있습니다.\u200b\u200b 상세 직무 및 근무지\u200b\u200b현대차에서는 열정과 성장 잠재력을 가진 미래형 인재를 선발해 모빌리티 혁신을 만들어 가겠다는 목표를 가지고 있는데요.\u200b2025년 채용에 이어서 2026년도 장애인 신입 채용을 동시에 운영해서 균형이 잡힌 현대자동차 만의 채용 기조를 이어가겠다는 방침입니다.주요 근무지는 울산, 아산, 남양, 판교, 의왕, 경기, 마북, 전주 등이 있겠습니다.\u200b\u200b \u200b\u200b 현대차 신입 연봉 정리(초봉·성과급·실수령액)현대자동차 취업을 고려하는 분들이라면 가장 궁금한 것 중 하나가 바로 신입 연봉 수준일 텐데요.최신 데이터를 바탕으로 보면, 현대차는 여전히 국내 최상위 수준의 연봉을 유지하고 있습니다.\u200b특히 성과급 비중이 높은 구조라 \'실제 받는 돈(영끌)\' 기준으로는 체감 연봉이 훨씬 높다는 점이 특징입니다.\u200b\u200b \u200b\u200b 현대차 신입 연봉 (2025 기준)기본 계약 연봉  약 5,000만 원 ~ 5,300만 원 수준 대기업 평균과 비교해도 높은 편이지만, 현대차는 여기서 끝이 아닙니다.\u200b\u200b 실제 연봉 (영끌 기준) 약 8,000만 원 ~ 9,400만 원 수준 즉, 성과급 + 상여금 포함 시 1년 차에도 9천 가까이 가능\u200b\u200b \u200b\u200b 왜 이렇게 많이 받을까?현대자동차 연봉이 높은 이유는 구조에 있습니다.\u200b1)성과급 비중이 매우 큼 - PI(성과금), PS(이익배분금) 지급- 경영 실적이 좋을수록 크게 상승2025년은 역대급 실적으로 인해 성과급 최대 수준 반영 \u200b2)다양한 추가 수당- 품질격려금- 명절 상여금- 복지 포인트- 주식 지급(약 30주)단순 월급 외에도 "숨은 돈"이 많음 \u200b\u200b  \u200b\u200b 직무별 연봉 차이 현대차는 직무별 실수령액 차이도 뚜렷한 편인데요.\u200b사무직 / 연구직기본 연봉 + 성과급 중심 초봉 영끌 약 9천 전후 \u200b생산직 기본급 + 각종 수당 (야간/특근 등)초봉 약 7,000만 원대생산직도 국내 최상위 수준\u200b\u200b \u200b\u200b평균 연봉 수준 2025년 평균 연봉 : 약 1억 3,100만 원 전년 대비 5.7% 상승 입사 후 5년 내 1억 돌파 가능성 높음\u200b\u200b핵심 요약하면?계약 연봉: 5,000만 원 초반 신입 실수령(영끌): 8,000만 원 ~ 9,400만 원 평균 연봉: 1억 3천 수준 특징: 성과급 비중 매우 큼\u200b\u200b즉, "현대차는 기본급보다 성과급이 진짜 연봉을 결정합니다."\u200b\u200b현대자동차는 단순히 초봉이 높은 기업이 아니라, 성과에 따라 보상이 크게 달라지는 고성과형 연봉 구조를 가진 회사입니다.\u200b그래서 취업을 준비할 때는 연봉 총액(영끌) 기준으로 보는 게 중요합니다.\u200b앞으로도 실적이 유지된다면, 신입 기준에서도 국내 최상위 연봉 수준은 이어질 전망입니다.연차가 쌓이면 억대 연봉도 충분히 기대할 수 있는 것이죠.\u200b '

### Request, Beautiful의 단점
- url요청 후 HTML문서에서 보여지는 로드된 정적인 데이터만 추출이 가능했음
- 사람이라면 가능했을 웹 브라우저 자체의 제어가 불가능(웹 브라우저 켜기, 마우스 클릭, 검색, 수집)

# Selenium: 라이브러리 활용
- BeautifulSoup과 달리 사람이 할 수 있는 웹 브라우저의 모든 기능을 제어할 수 있음
- 사람이 실제로 인터넷을 사용하는 것과 동일한 순서대로 코드를 작성해야함
- selenium은 동적 페이지에서도 동작하기 위해 페이지가 바뀌는 순간 모든 데이터가 초기화 되므로 페이지의 변화를 생각해서 코드를 작성해야 함

In [95]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.44.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2026.2.25 (from selenium)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\jungsoo\anaconda3\lib\site-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\jungsoo\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\jungsoo\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\jungsoo\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\jungsoo\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\jungsoo\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\jungsoo\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\jungsoo\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\jungsoo\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\jungsoo\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.44.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -------------------------------------- - 9.2/9.7 MB 59.3 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 51.5 MB/s  0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, outcome, certifi, trio, trio-websocket, selenium

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.5.0

    Uninstalling urllib3-2.5.0:

      Successfully uninstalled urllib3-2.5.0

   ----- ---------------------------------- 1/7 [urllib3]
   ----- ---------------------------------- 1/7 [urllib3]
  Attempting uninstall: certifi
   ----- ---------------------------------- 1/7 [urllib3]
    Found existing installation: certifi 2025.11.12
   ----- ---------------------------------- 1/7 [urllib3]
    Uninstalling certifi-2025.11.12:
   ----- ---------------------------------- 1/7 [urllib3]
      Successfully uninstalled certifi-2025.11.12
   ----- ---------------------------------- 1/7 [urllib3]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------------- 7/7 [selenium]

Successfully installed certifi-2026.5.20 outcome-1.3.0.post0 selenium-4.44.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.7.0 wsproto-1.3.2

In [137]:
# webdriver: 웹을 컨트롤하는 함수(웹 브라우저 역할)
from selenium import webdriver as wb

### 크롬 브라우저 실행

In [101]:
driver = wb.Chrome()

# 크롬창이 뜨고 'Chrome이 자동화된 테스트 소프트웨어에 의해 제어되고 있습니다.' 이 문구가 항상 보여야함

### 네이버 페이지로 이동

In [144]:
driver.get("https://www.naver.com")

TypeError: WebDriver.get() missing 1 required positional argument: 'url'

### 검색창에 특정 단어 입력
- 컴퓨터에게 검색창을 찾게 명령하기 위해서는 다른 요소들과 마찬가지로 검색창의 태그 및 선택자를 알아야함

In [104]:
# By: selenium에서 선택자를 구분해주는 함수
from selenium.webdriver.common.by import By

In [122]:
# find_element: selenium에서 웹의 특정 요소하나를 찾아주는 함수(여러개를 찾으려면 s를 붙여 사용)
# CSS_SELECTOR: CSS선택지를 찾아주는 인자
search = driver.find_element(By.CSS_SELECTOR,"#query")

In [123]:
# send_keys: 특정 문자를 입력시키는 함수(여러번 실행하면 텍스트만 추가됨)
search.send_keys("트럼프")

### ENTER키 누르기

In [112]:
# Keys: 키보드를 컨트롤하는 함수
from selenium.webdriver.common.keys import Keys

In [124]:
search.send_keys(Keys.ENTER) # ENTER키 누르기

### 뒤로가기

In [125]:
driver.back()
# 뒤로가기 버튼은 HTML영역이 아닌 브라우저에서 제공하는 고유 기능이라 driver 변수에서 요청해야함

### 이번에는 ENTER 대신에 돋보기 검색버튼을 클릭해서 들어가기

In [130]:
search = driver.find_element(By.ID,"query") # 검색창 접근
search.send_keys("오늘의 날씨") # 키보드로 키워드 작성

In [131]:
btn = driver.find_element(By.CSS_SELECTOR, "#search-btn-svg") # 돋보기 버튼에 접근

btn.click() # 선택된 버튼 클릭

In [132]:
driver.back()

### XPATH 절대경로 사용하기
- XPATH는 원하는 요소에 정확히 접근하기 위한 절대경로를 가져오는 기능
- 하나의 요소에 정확하게 접근할 때 사용하면 편리한, 여러개의 요소에 접근해야 하거나 웹 페이지가 자주 바뀌는 유동적인 환경에서는 효율이 떨어짐
- 따라서 변동사항이 저긍ㄴ 개별 요소를 추출할 때 사용하면 매우 편리함(검색버튼, 메뉴버튼, 등 잘 바뀌지 않는 요소)
- 요소에 ID나 Class 값이 붙어있지 않아 구조나 텍스트 만으로 대상을 찾아야할 때 활용하면 좋음

In [133]:
search = driver.find_element(By.ID,"query")
search.send_keys("오늘의 날씨")

btn = driver.find_element(By.XPATH,'//*[@id="search-btn-svg"]') # 절대결로로 접근
btn.click()

### 스크롤 기능 사용하기
- 스크롤을 위해서는 스크롤ㄹ이 가능한 전체 틀인 body 태그 자체를 선택한 뒤 스크롤 기능을 활용하느 것도 방법임

In [134]:
# TAG_NAME 태그명으로 요소에 접근
body = driver.find_element(By.TAG_NAME, "body")

# END: 맨 아래쪽으로 이동(DOWN은 아래 방향 키보드 한번)
body.send_keys(Keys.END)

In [135]:
# quit: 브라우저 창을 닫으며 연결이나 메모리도 모두 종료 시킴
driver.quit()

# close()도 닫는 기능이지만 메모리는 그대로 남아있음

### [실습] 네이버 검색
1. 크롬 브라우저 켜기
2. 네이버 접속
3. CSS_SELECTOR로 검색창 접근, 그리고 원하는 검색어 입력
4. 돋보기 검색 아이콘 클릭
5. 스크롤 끝까지 내리기
6. 뒤로가기 버튼 눌러서 다시 메인으로 이동
7. 크롬창 종료

In [159]:
# 1)
driver = wb.Chrome() # ()꼭 입력하기

In [160]:
# 2)
driver.get("https://www.naver.com")

In [161]:
# 3)
search = driver.find_element(By.ID,"query")   # 변수명2 = 변수명1.find_element(By.ID, "태그")
search.send_keys("Shiro") # 변수2.send_keys("검색할 단어")

#4)
search = driver.find_element(By.CSS_SELECTOR, "#search-btn-svg") # 변수명2 = 변수명1.find_element(By.CSS_SELETOR, "태그")
search.click() # 변수2.click()

In [162]:
# 5)
body = driver.find_element(By.TAG_NAME, "body")
body.send_keys(Keys.END)

In [163]:
# 6)
driver.back()

In [164]:
# 7)
driver.quit()

### [실습] 네이버 검색 심화
1. 크롬 브라우저 켜기
2. 네이버로 접속
3. CSS_SELECTOR로 검색창 접근 - 원하는 검색어 입력(ENTER키로 검색)
4. 검색후 '이미지' 탭 클릭(경로 원하는대로 편하게 잡기)
5. 뒤로가기
6. '블로그' 탭을 클릭해서 들어가기(CSS_SELECTOR로 경로 잡기)
7. 스크롤을 맨 밑으로 한 번 내리기
8. Selenium 코드를 활용해 블로그 제목 크롤링하기(find_elements로 여러개 요소에 접근)
9. 크롤링된 제목을 No를 1번 부터 인덱스로 설정해서 DF로 만들기
10. DF를 csv파일로 저장하기
11. 뒤로가기 버튼을 두 번 실행해서 다시 메인으로 이동
12. 크롬창 종료 - 메모리까지 삭제

In [271]:
# 1)
driver = wb.Chrome()

In [272]:
# 2)
driver.get("https://www.naver.com")

In [273]:
# 3)
search = driver.find_element(By.ID, "query")
search.send_keys("Shiro")

search.send_keys(Keys.ENTER) # ENTER키 누르기

In [274]:
# 4)
search = driver.find_element(By.CSS_SELECTOR, "#lnb > div.lnb_group > div > div.lnb_nav_area._nav_area_root > div > div.api_flicking_wrap._conveyer_root > div:nth-child(3) > a")
search.click()

In [275]:
# 5)
driver.back()

In [276]:
# 6)
search = driver.find_element(By.CSS_SELECTOR, "#lnb > div.lnb_group > div > div.lnb_nav_area._nav_area_root > div > div.api_flicking_wrap._conveyer_root > div:nth-child(2) > a")
search.click()

In [281]:
# 7)
body = driver.find_element(By.TAG_NAME, "body")
body.send_keys(Keys.END)

In [278]:
# 8) ver1 - find_elements 사용해서 제목 긁어오기
titles = driver.find_elements(
    By.CSS_SELECTOR,
    "span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1.sds-comps-text-weight-sm"
)
titles

[<selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18599")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18667")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18733")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18800")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18869")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.18936")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19003")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19069")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19135")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19201")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19265")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19313")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19362")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19409")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19458")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19506")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19554")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19601")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19647")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19694")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19740")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19789")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19837")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19885")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19936")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.19982")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.20030")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.20079")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.20127")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.20175")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22183")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22231")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22277")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22325")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22373")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22421")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22469")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22518")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22567")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22615")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22663")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22712")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22762")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22811")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22859")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22907")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.22955")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23003")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23052")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23100")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23146")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23194")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23240")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23287")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23335")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23383")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23431")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23479")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23527")>,
 <selenium.webdriver.remote.webelement.WebElement (session="4dfd5fb7c5592e003cf985fe6fd8a769", element="f.C04C1E8B1B18EC5902DD0CC7AE480832.d.3C11A8C42F25A5CDA12AC4213390E56B.e.23575")>]

In [279]:
# 8) ver1
titles_list = []
for i in titles:
    # titles[i] 대신 i를 쓰고, stirp 오타를 strip으로 수정했습니다.
    titles_list.append(i.text.strip())

titles_list

['홋카이도 시로 SHIRO 스나가와 본점 : SHIRO 모두의 공장(みんなの工場) 향수 체험 & 시로 카페',
 "[호주] 브리즈번 시티, 골드코스트 디저트 추천 'Shiro Gelato & Snack'",
 '[KIRA]SHIRO: 자연의 선물로 일상을 빛내다 / 매장정보 공유',
 '일본 후쿠오카 쇼핑 리스트 SHIRO 시로 향수 매장 가격 면세 할인 방법',
 'SHIRO |시로 성수 한국 1호점 오픈',
 '[일본] SHIRO 디퓨저 얼그레이 & 화이트티 고급스러운 향의 시로향수 일본 여행 필수템!',
 'SHIRO 시로 공장에서 만드는 나만의 화장품',
 '[시로/헤어오일추천] SHIRO WHITE TEA 시로 화이트티 헤어오일 30ML 사용 후기',
 '시로 SHIRO 서울 1호점인 성수 플래그십 매장 주말 방문 후기',
 '시로 피치 피오니 오드 팔판 신상 향수 SHIRO',
 '교토-오사카 5박6일 #11 우메다한큐백화점 시로(SHIRO)향수 구매',
 '일본여행 필수품 일본향수 시로shiro 성수매장 오픈날짜 영업시간 한국한정 스즈란',
 'SHIRO | 깔끔하고 선물하기 넘 좋은 시로 향수',
 '일본 뷰티 브랜드 SHIRO: 자연을 담은 미니멀리즘의 매력',
 '책임있는 태도가 만든 ‘시로SHIRO’의 팝업 스토어',
 'Shiro 시로 향수 추천 / 내돈내산 / 리빙 마이 스토리 향수',
 '도쿄 긴자 미츠코시 백화점 향수 추천 : 시로(SHIRO) 제로 사봉 가격, 면세, 향 추천',
 '도쿄 #2.2 | 시부야 로컬 즐기기 츠케멘 야스베에, 시로(Shiro) 향수, 포터(Porter), 시부야요코초',
 '성수 SHIRO 시로 향수 팝업 오프라인 매장 방문 후기',
 '일본 향수 브랜드를 찾는다면, SHIRO 시로 향수 추천',
 '[도쿄향수]시로 SHIRO表参道本店 시부야점',
 '일본 현지인이 사용하는 로컬 브랜드 (SHIRO) 향수 후쿠오카 이와타야(IWATAYA) 백화점 매장 방문 구매 후기',
 '[후쿠오카/SHIRO 향수] 시로 향수, 화이트릴리, 프리지아미스트, 위싱유(WHITE LILY, FREESIA MIST, WISHING YOU)',
 '시로 SHIRO 성수 매장 후기 | 일본 향수 화장품 브랜드, 한국 한정 은방울꽃향, 제품추천',
 'SHIRO(시로), 롯데백화점 명동본점에 국내 3호점 오픈 명동본점 한정 ‘레이어링 프래그런스’ 5종 출시',
 '[삿포로 Day1] 흔하지 않은 일본 쇼핑리스트 추천: SHIRO 향수(Feat. 여행은...향기를 남기고)',
 '후쿠오카 비비안웨스트우드 손수건, SHIRO, 세리아 | 한큐백화점',
 '#후기: 일본여행쇼핑 내돈내산,Shiro 화이트 릴리 오 드 퍼퓸 향수 추천',
 '시로(SHIRO) 성수 플래그십 스토어 방문 후기',
 '성수 시로 매장 | 시로 SHIRO',
 '시로(SHIRO)핸드세럼, 바디미스트 후기(일본구매)',
 '시로 성수, 시로(SHIRO) 향수 후기, 시로 팝업 매장 / 사봉,얼그레이,화이트티 후기',
 '[시로/SHIRO] 화이트 릴리 핸드세럼 향기와 보습을 동시에 잡은 감성 케어 후기',
 '떠오르는 일본 뷰티 브랜드ㅣSHIRO 시로 OSAJI 오사지 KANEBO 가네보 SABORINO 사보리노',
 '긴자 미츠코시 :: SHIRO 시로향수, 게스트카드5%할인, 택스프리',
 '일본 향수 브랜드 추천, SHIRO 시로 성수 플래그쉽 스토어 매장 시향 후기',
 '[성수팝업] 시로(shiro) | 시로 향수 만들기, 내돈내산',
 '[에어팟프로 케이스 추천] 시로&마로(shiro&maro) 에어팟프로 케이스 구매 후기',
 '시로 성수 SHIRO 일본 향수 화장품 브랜드 | 사봉 오 드 퍼퓸 구매 후기',
 'SHIRO 일본 향수 브랜드 시로 오 드 퍼퓸 : 화이트 티, 미모사',
 '일본 화장품 SHIRO 시로 아이스민트 바디미스트 더위 졸음 싹 날려줘요',
 'SHIRO 향수 freesia mist, spice of life / SHIRO 헤어오일',
 'Tokyo.2023 : 도쿄여행 - 시로향수 사봉 SHIRO SAVON',
 '성수 SHIRO 시로향수 플래그십 스토어 방문',
 '일본 쇼핑리스트 시로 SHIRO 향수 프리지아 미스트 리뷰',
 '일본향수 SHIRO 시로향수 후쿠오카 한큐백화점 이와타야백화점 시향 후기',
 '세절역카페 시로 SHIRO, 푸딩 덕후라면 무조건 가야 하는 응암동카페',
 '일본 브랜드 시로 SHIRO 더현대서울 팝업스토어 후기(일정,위치,선물포장)',
 '일본 시로 향수 면세 텍스리펀 가격 | 삿포로 스텔라플레이스 SHIRO 쇼핑리스트',
 '삿포로 스텔라플레이스 일본 SHIRO 시로 향수 구매 후기 (사봉/화이트릴리/얼그레이)+ 텍스프리 가능',
 'SHIRO _ 시로의 추천템 TOP3 (사봉, 프리지아, 얼그레이)',
 '[SHIRO] 일본 시로 향수 자연주의 / 성수동 향수 추천',
 '일본 선물 추천 시로 SHIRO 향수 사봉 얼그레이 후기',
 '후쿠오카 이와타야백화점 Shiro 시로향수 프리지아 미스트 오드퍼퓸 내돈내산 리뷰',
 '시로 SHIRO 바디미스트 사봉 바디미스트 얼그레이 바디미스트 화이트 티 바디미스트',
 '성수 시로 SHIRO 일본 시로 향수를 성수동에서! 서울 데이트 커스텀향수만들기',
 '향에 진심이라면 꼭 가봐야 할 곳｜성수 SHIRO 시로 팝업 향수 만들기 체험 후기',
 '일본 도쿄 긴자 미츠코시 백화점 쇼핑 시로 SHIRO 향수&핸드크림 쇼핑리스트 +할인 꿀팁',
 '도쿄여행_도쿄쇼핑추천 SHIRO 핸드크림 바디로션 / 시로 택스리펀',
 'SHIRO(시로), ‘루바브 하마나스’ 리뉴얼 및 여름 한정 ‘아이스 민트’ 새 라인업 출시']

In [282]:
len(titles)

60

In [283]:
# 9) ver1
titles_df = pd.DataFrame({"블로그 제목":titles_list},
                        index = range(1,len(titles_list)+1))
titles_df.index.name = "No"
titles_df

                                               블로그 제목
No
1   홋카이도 시로 SHIRO 스나가와 본점 : SHIRO 모두의 공장(みんなの工場) 향...
2   [호주] 브리즈번 시티, 골드코스트 디저트 추천 'Shiro Gelato & Snack'
3              [KIRA]SHIRO: 자연의 선물로 일상을 빛내다 / 매장정보 공유
4           일본 후쿠오카 쇼핑 리스트 SHIRO 시로 향수 매장 가격 면세 할인 방법
5                              SHIRO |시로 성수 한국 1호점 오픈
6   [일본] SHIRO 디퓨저 얼그레이 & 화이트티 고급스러운 향의 시로향수 일본 여행...
7                           SHIRO 시로 공장에서 만드는 나만의 화장품
8   [시로/헤어오일추천] SHIRO WHITE TEA 시로 화이트티 헤어오일 30ML ...
9                시로 SHIRO 서울 1호점인 성수 플래그십 매장 주말 방문 후기
10                        시로 피치 피오니 오드 팔판 신상 향수 SHIRO
11            교토-오사카 5박6일 #11 우메다한큐백화점 시로(SHIRO)향수 구매
12      일본여행 필수품 일본향수 시로shiro 성수매장 오픈날짜 영업시간 한국한정 스즈란
13                       SHIRO | 깔끔하고 선물하기 넘 좋은 시로 향수
14                  일본 뷰티 브랜드 SHIRO: 자연을 담은 미니멀리즘의 매력
15                      책임있는 태도가 만든 ‘시로SHIRO’의 팝업 스토어
16               Shiro 시로 향수 추천 / 내돈내산 / 리빙 마이 스토리 향수
17  도쿄 긴자 미츠코시 백화점 향수 추천 : 시로(SHIRO) 제로 사봉 가격, 면세,...
18  도쿄 #2.2 | 시부야 로컬 즐기기 츠케멘 야스베에, 시로(Shiro) 향수, 포...
19                    성수 SHIRO 시로 향수 팝업 오프라인 매장 방문 후기
20                    일본 향수 브랜드를 찾는다면, SHIRO 시로 향수 추천
21                           [도쿄향수]시로 SHIRO表参道本店 시부야점
22  일본 현지인이 사용하는 로컬 브랜드 (SHIRO) 향수 후쿠오카 이와타야(IWATA...
23  [후쿠오카/SHIRO 향수] 시로 향수, 화이트릴리, 프리지아미스트, 위싱유(WHI...
24  시로 SHIRO 성수 매장 후기 | 일본 향수 화장품 브랜드, 한국 한정 은방울꽃향...
25  SHIRO(시로), 롯데백화점 명동본점에 국내 3호점 오픈 명동본점 한정 ‘레이어링...
26  [삿포로 Day1] 흔하지 않은 일본 쇼핑리스트 추천: SHIRO 향수(Feat. ...
27              후쿠오카 비비안웨스트우드 손수건, SHIRO, 세리아 | 한큐백화점
28         #후기: 일본여행쇼핑 내돈내산,Shiro 화이트 릴리 오 드 퍼퓸 향수 추천
29                        시로(SHIRO) 성수 플래그십 스토어 방문 후기
30                                성수 시로 매장 | 시로 SHIRO
31                      시로(SHIRO)핸드세럼, 바디미스트 후기(일본구매)
32  시로 성수, 시로(SHIRO) 향수 후기, 시로 팝업 매장 / 사봉,얼그레이,화이트...
33     [시로/SHIRO] 화이트 릴리 핸드세럼 향기와 보습을 동시에 잡은 감성 케어 후기
34  떠오르는 일본 뷰티 브랜드ㅣSHIRO 시로 OSAJI 오사지 KANEBO 가네보 S...
35             긴자 미츠코시 :: SHIRO 시로향수, 게스트카드5%할인, 택스프리
36        일본 향수 브랜드 추천, SHIRO 시로 성수 플래그쉽 스토어 매장 시향 후기
37                 [성수팝업] 시로(shiro) | 시로 향수 만들기, 내돈내산
38   [에어팟프로 케이스 추천] 시로&마로(shiro&maro) 에어팟프로 케이스 구매 후기
39        시로 성수 SHIRO 일본 향수 화장품 브랜드 | 사봉 오 드 퍼퓸 구매 후기
40             SHIRO 일본 향수 브랜드 시로 오 드 퍼퓸 : 화이트 티, 미모사
41           일본 화장품 SHIRO 시로 아이스민트 바디미스트 더위 졸음 싹 날려줘요
42  SHIRO 향수 freesia mist, spice of life / SHIRO 헤어오일
43            Tokyo.2023 : 도쿄여행 - 시로향수 사봉 SHIRO SAVON
44                          성수 SHIRO 시로향수 플래그십 스토어 방문
45                   일본 쇼핑리스트 시로 SHIRO 향수 프리지아 미스트 리뷰
46           일본향수 SHIRO 시로향수 후쿠오카 한큐백화점 이와타야백화점 시향 후기
47            세절역카페 시로 SHIRO, 푸딩 덕후라면 무조건 가야 하는 응암동카페
48         일본 브랜드 시로 SHIRO 더현대서울 팝업스토어 후기(일정,위치,선물포장)
49      일본 시로 향수 면세 텍스리펀 가격 | 삿포로 스텔라플레이스 SHIRO 쇼핑리스트
50  삿포로 스텔라플레이스 일본 SHIRO 시로 향수 구매 후기 (사봉/화이트릴리/얼그레...
51              SHIRO _ 시로의 추천템 TOP3 (사봉, 프리지아, 얼그레이)
52                  [SHIRO] 일본 시로 향수 자연주의 / 성수동 향수 추천
53                    일본 선물 추천 시로 SHIRO 향수 사봉 얼그레이 후기
54      후쿠오카 이와타야백화점 Shiro 시로향수 프리지아 미스트 오드퍼퓸 내돈내산 리뷰
55     시로 SHIRO 바디미스트 사봉 바디미스트 얼그레이 바디미스트 화이트 티 바디미스트
56       성수 시로 SHIRO 일본 시로 향수를 성수동에서! 서울 데이트 커스텀향수만들기
57     향에 진심이라면 꼭 가봐야 할 곳｜성수 SHIRO 시로 팝업 향수 만들기 체험 후기
58  일본 도쿄 긴자 미츠코시 백화점 쇼핑 시로 SHIRO 향수&핸드크림 쇼핑리스트 +할...
59              도쿄여행_도쿄쇼핑추천 SHIRO 핸드크림 바디로션 / 시로 택스리펀
60  SHIRO(시로), ‘루바브 하마나스’ 리뉴얼 및 여름 한정 ‘아이스 민트’ 새 라...

In [263]:
# 8) ver2
def Blog_title(keyword: str) -> pd.DataFrame:
    
    title_list = []
    url = f"https://search.naver.com/search.naver?ssc=tab.blog.all&sm=tab_jum&query={keyword}"
    U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"}
    res = req.get(url, headers = U_A)
    soup = bs(res.text, "lxml")

    title = soup.select("span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1.sds-comps-text-weight-sm")

    for i in range(len(title)):
        title_list.append(title[i].text.strip())

    Blog_df = pd.DataFrame({"블로그 제목": title_list},
                            index = range(1, len(title)+1))
    Blog_df.index.name = "No"

    return Blog_df

In [264]:
len(title)

30

In [239]:
# 사용자 정의 함수 사용하여 DF 만들기
Blog_title("Shiro")

                                               블로그 제목
No
1   [호주] 브리즈번 시티, 골드코스트 디저트 추천 'Shiro Gelato & Snack'
2   홋카이도 시로 SHIRO 스나가와 본점 : SHIRO 모두의 공장(みんなの工場) 향...
3              [KIRA]SHIRO: 자연의 선물로 일상을 빛내다 / 매장정보 공유
4           일본 후쿠오카 쇼핑 리스트 SHIRO 시로 향수 매장 가격 면세 할인 방법
5                              SHIRO |시로 성수 한국 1호점 오픈
6   [일본] SHIRO 디퓨저 얼그레이 & 화이트티 고급스러운 향의 시로향수 일본 여행...
7                           SHIRO 시로 공장에서 만드는 나만의 화장품
8   [시로/헤어오일추천] SHIRO WHITE TEA 시로 화이트티 헤어오일 30ML ...
9                시로 SHIRO 서울 1호점인 성수 플래그십 매장 주말 방문 후기
10            교토-오사카 5박6일 #11 우메다한큐백화점 시로(SHIRO)향수 구매
11      일본여행 필수품 일본향수 시로shiro 성수매장 오픈날짜 영업시간 한국한정 스즈란
12                       SHIRO | 깔끔하고 선물하기 넘 좋은 시로 향수
13                  일본 뷰티 브랜드 SHIRO: 자연을 담은 미니멀리즘의 매력
14                        시로 피치 피오니 오드 팔판 신상 향수 SHIRO
15                      책임있는 태도가 만든 ‘시로SHIRO’의 팝업 스토어
16               Shiro 시로 향수 추천 / 내돈내산 / 리빙 마이 스토리 향수
17  도쿄 긴자 미츠코시 백화점 향수 추천 : 시로(SHIRO) 제로 사봉 가격, 면세,...
18  도쿄 #2.2 | 시부야 로컬 즐기기  츠케멘 야스베에, 시로(Shiro) 향수, ...
19                    성수 SHIRO 시로 향수 팝업 오프라인 매장 방문 후기
20                    일본 향수 브랜드를 찾는다면, SHIRO 시로 향수 추천
21                           [도쿄향수]시로 SHIRO表参道本店 시부야점
22  일본 현지인이 사용하는 로컬 브랜드 (SHIRO) 향수 후쿠오카 이와타야(IWATA...
23  [후쿠오카/SHIRO 향수] 시로 향수, 화이트릴리, 프리지아미스트, 위싱유(WHI...
24  시로 SHIRO 성수 매장 후기 | 일본 향수 화장품 브랜드, 한국 한정 은방울꽃향...
25  SHIRO(시로), 롯데백화점 명동본점에 국내 3호점 오픈              ...
26  [삿포로 Day1] 흔하지 않은 일본 쇼핑리스트 추천: SHIRO 향수(Feat. ...
27              후쿠오카 비비안웨스트우드 손수건, SHIRO, 세리아 | 한큐백화점
28         #후기: 일본여행쇼핑 내돈내산,Shiro 화이트 릴리 오 드 퍼퓸 향수 추천
29                        시로(SHIRO) 성수 플래그십 스토어 방문 후기
30                                성수 시로 매장 | 시로 SHIRO

In [234]:
Blog_title("삼성전자")[:10]

                                               블로그 제목
No
1             삼성전자 주가 311% 수익률이여 안녕, 가슴 아픈 삼성전자 매도 후기
2                        삼성전자 배당금  5월29일 통장 꽂히는 진짜 액수
3     삼성전자 주가, 코스피 지수 5% 폭락하고 있지만 마음이 편하고 계좌는 수익나는 이유
4   "특별배당까지 터졌다!" 2026 삼성전자 배당금 지급일 기준일 특별배당금 1만원전...
5              삼성전자 제치고 "1000% 폭등" 한 역대급 'AI 대장주'의 정체
6              삼성전자 SK하이닉스 레버리지 ETF, 매수 전 교육부터 막히는 이유
7                          “삼성전자 노조 결국 폭발했다…현재 협상 상황”
8                         삼성전자 SK하이닉스 주가 성과금 실제 받은 후기
9             "다 오른 줄 알았죠?" 삼성전자 SK하이닉스 주가 아직도 저평가라는데
10      삼성전자 최승호 노조위원장 프로필 나이 결혼 가족 자녀 아내 학력 고향 부서 직급

In [265]:
# 9) ver2 DF만들기
df_result = Blog_title("Shiro")

# 10) CSV파일로 저장
df_result.to_csv("data/Blog_title.csv", encoding="utf-8-sig")

In [285]:
# 11) 뒤로 두번 가기
driver.back()
driver.back()

In [286]:
# 12) 크롬창 종료 - 메모리 삭제
driver.quit()